feat: datafile accessor (WIP)
optimizely/javascript-sdk pull request #535
Opened 2020-07-24 23:13 UTC by pthompson127

Summary
----------
- Modified datafile manager to keep track of datafile string instead of parsing and creating an object
   - Datafile string parsing and validation will be done by `projectConfigManger`
- Add toDatafile() methods in `projectConfigManger` and `OptimizelyConfig`

Test Plan
----------
- Ran some sanity checks with test driver app
- (WIP) -> will need to run more tests and maybe modify some existing tests to account for changes

2020-07-28 00:34 UTC, mjc1283 commented on packages/optimizely-sdk/lib/core/project_config/project_config_manager.js
> +
I don't think we want `toDatafile` on project config manager.

2020-07-28 18:55 UTC, pthompson127 commented on packages/optimizely-sdk/lib/core/optimizely_config/index.js
> +OptimizelyConfig.prototype.toDatafile = function() {
done ✔️

2020-07-28 18:55 UTC, pthompson127 commented on packages/optimizely-sdk/lib/core/optimizely_config/index.js
> +  this.featuresMap = this.__getFeaturesMap(configObj, this.experimentsMap);
done ✔️

2020-07-28 18:56 UTC, pthompson127 commented on packages/optimizely-sdk/lib/core/project_config/project_config_manager.js
> +import optimizelyConfig from '../optimizely_config';
done ✔️

2020-07-28 18:56 UTC, pthompson127 commented on packages/optimizely-sdk/lib/core/project_config/project_config_manager.js
> +      datafileManagerConfig.datafile = this.__datafileObj;
done ✔️

2020-07-28 18:56 UTC, pthompson127 commented on packages/optimizely-sdk/lib/core/project_config/project_config_manager.js
> +
done ✔️

2020-07-28 20:26 UTC, mjc1283 commented on packages/optimizely-sdk/lib/core/project_config/index.js
> +
I found an issue with this code that I suggested. When we already have a string because user passed in string, we will be parsing it and then re-`stringify`-ing it here. To avoid this unneccessary `stringify`, let's do this:
```js
export function createProjectConfig(datafileObj, datafileStr=null) {
  // ...
  projectConfig.__datafileStr = datfileStr === null ? JSON.stringify(datafileObj) : datafileStr;
  // ...
}
```

Then, below in `tryCreatingProjectConfig`:

```js
// ...
var createArgs = [newDatafileObj];
if (typeof config.datafile === 'string') {
  // We know config.datafile is a valid JSON datafile string because it was validated above
  createArgs.push(config.datafile)
}
var newConfigObj = this.createProjectConfig(...createArgs);
// ...
```

2020-07-28 20:32 UTC, mjc1283 commented on packages/optimizely-sdk/lib/core/project_config/index.js
> + *
Please add a short description of what `toDatafile` returns.

2020-07-28 20:33 UTC, mjc1283 commented on packages/optimizely-sdk/lib/core/optimizely_config/index.js
> +OptimizelyConfig.prototype.getDatafile = function() {
Please add a JSDoc comment with the return type.

2020-07-28 20:40 UTC, mjc1283 commented on packages/optimizely-sdk/lib/core/optimizely_config/index.js
> -// Get Experiment Ids which are part of rollouts
I don't think there's any material difference in `getRolloutExperimentIds` or `getFeaturesMap`, rather they appear in this diff because they were reordered within the file. Could you restore them to the original order just to confirm that?

2020-07-28 20:45 UTC, mjc1283 commented on packages/optimizely-sdk/.eslintrc.js
> +    ecmaVersion: 2018,
Oops...I thought your branch was based on https://github.com/optimizely/javascript-sdk/tree/mcarroll/optimizely-sdk-typescript, so I suggested adding some newer syntax. But I see now this PR is against master. I suppose the easiest thing now is to wait until we can merge https://github.com/optimizely/javascript-sdk/tree/mcarroll/optimizely-sdk-typescript into master before merging these changes.

We can address this later, as the first step for this PR should be separating out and pushing through the datafile manager changes.

2020-08-25 16:57 UTC, msohailhussain commented
FSC builds passing link:
Client Node: https://travis-ci.com/github/optimizely/fullstack-sdk-compatibility-suite/builds/181326549
Client browser: https://travis-ci.com/github/optimizely/fullstack-sdk-compatibility-suite/builds/181329335

2020-09-05 00:22 UTC, mjc1283 requested changes

2020-09-08 19:11 UTC, msohailhussain commented on packages/optimizely-sdk/lib/core/optimizely_config/index.js
> +  OptimizelyConfig: OptimizelyConfig
unable to stub, that's why passing object.

2020-09-08 19:11 UTC, msohailhussain commented on packages/optimizely-sdk/lib/core/project_config/index.js
> +  var newConfigObj = this.createProjectConfig(...createProjectConfigArgs);
This was causing to call real function instead of stubbed function, that's why `this` is mandatory here.

2020-09-09 16:45 UTC, mjc1283 approved these changes

2020-09-09 17:10 UTC, merged