feat: Convert custom_attribute_condition_evaluator to TS
optimizely/javascript-sdk pull request #561
Opened 2020-09-01 23:58 UTC by yavorona

## Summary

- Convert `custom_attribute_condition_evaluator` module from JS to TS.

## Test plan
- Existing unit tests and local bundle

2020-09-02 16:22 UTC, mjc1283 commented on packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.ts
> +};
Let's be more specific here. You can check out the structure of condition objects in the datafile by creating audiences with different condition types. 

Condition objects have `type`, `name`, `match`, and `value` properties. The functions in this module use `name`, `match`, and `value`.

2020-09-02 16:26 UTC, mjc1283 commented on packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.ts
> + * @returns {?boolean}
Should this just be `boolean`, not `?boolean`?

2020-09-02 16:30 UTC, mjc1283 commented on packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.ts
> +// TODO: Find place for UserAttributes and Condition types to live in
We could create a shared types module at lib/shared_types.ts, and put this there.

It would be nice if somehow we could import `UserAttributes` from there and use it here, as well as also in lib/index.d.ts. I had some trouble figuring that out, it may not be possible. If so I think we can just duplicate the definition (have one in lib/index.d.ts, and one in lib/shared_types.ts which is imported by out TS modules).

2020-09-02 19:18 UTC, yavorona commented on packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.ts
> +// TODO: Find place for UserAttributes and Condition types to live in
I also tried to  use `UserAttributes` in lib/index.d.ts from lib/shared_types.ts i, but could not figure it out how to make it work, so left lib/index.d.ts as is and followed your suggestion.

2020-09-02 21:49 UTC, mjc1283 requested changes

2020-09-02 21:49 UTC, mjc1283 commented on packages/optimizely-sdk/lib/shared_types.ts
> +export type Condition = {
`Condition` can live in the custom_attribute_condition_evaluator module

2020-09-02 21:49 UTC, mjc1283 commented on packages/optimizely-sdk/lib/shared_types.ts
> +   match: string;
The evaluator has the ability to handle when `match` is missing (in that case it is treated as an exact match), so let's capture that here:
```suggestion
   match?: string;
```

2020-09-02 21:49 UTC, mjc1283 commented on packages/optimizely-sdk/lib/shared_types.ts
> +   value: any;
```suggestion
   value: string | number | boolean;
```

2020-09-02 21:49 UTC, mjc1283 commented on packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.ts
> +const EVALUATORS_BY_MATCH_TYPE = {};
Let's add a type annotation on this object - otherwise it seems reading a property of it results in `any` (check the type of `evaluatorForMatch` on line 76). How about:
```suggestion
type ConditionEvaluator = (condition: Condition, userAttributes: UserAttributes) => boolean | null;
const EVALUATORS_BY_MATCH_TYPE: { [conditionType: string]: ConditionEvaluator | undefined } = {};
```

2020-09-02 21:49 UTC, mjc1283 commented on packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.ts
> +export function evaluate(condition: Condition, userAttributes: UserAttributes, logger: LoggerFacade): boolean | null {
This is a good opportunity to clean up logging in this module.

- Let's change all these functions so that they use a logger defined inside this module (like `const logger = getLogger(MODULE_NAME);`, and then remove the `logger` argument from the list of parameters.
- Call the logger method corresponding to the desired level, rather than passing in level (`logger.debug(...)` instead of `logger.log(LOG_LEVEL.DEBUG, ...)`

2020-09-02 22:00 UTC, yavorona commented on packages/optimizely-sdk/lib/shared_types.ts
> +   value: any;
@mjc1283 I noticed that when we set attribute to `has any value`, the `value` in that case becomes `null`, so I think we should capture it here as well: `value: string | number | boolean | null`. What do you think?

2020-09-04 23:14 UTC, mjc1283 requested changes
Looks way better, thank you! Just one requested change then this should be ready to merge!

2020-09-05 00:21 UTC, mjc1283 approved these changes

2020-09-05 00:40 UTC, merged