Add semver in ts
optimizely/javascript-sdk pull request #563
Opened 2020-09-10 10:45 UTC by ozayr-zaviar

## Summary
- Semver added in optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.ts
- compareVersion function added in optimizely-sdk/lib/utils/attributes_validator/index.ts

## Test plan
- Semver test cases added in optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.test.js
- compareVersion function test cases added in optimizely-sdk/lib/utils/attributes_validator/index.test.js

2020-09-10 14:07 UTC, oakbani requested changes
Initial Review

2020-09-11 09:55 UTC, oakbani commented on packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.ts
> +  if (result == null)
Move above validations to another method as discussed. Yon can then remove these validations from all other places.

2020-09-11 09:55 UTC, oakbani commented on packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.ts
> +  if (result == null)
===? Also at other places.

2020-09-11 09:55 UTC, oakbani commented on packages/optimizely-sdk/lib/utils/attributes_validator/index.ts
> + function isPreReleaseVersion(version: unknown): boolean {
assign string to version param. And remove typeof check below

2020-09-11 09:55 UTC, oakbani commented on packages/optimizely-sdk/lib/utils/attributes_validator/index.ts
> +    const userVersionBuildIndex = version.indexOf(VERSION_TYPE.IS_BUILD);
you are checking version twice if it includes IS_PRE_RELEASE or not. See ruby for reference. You can optimize and simplify this method.

2020-09-11 11:35 UTC, yasirfolio3 commented on packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.tests.js
> +          app_version: '1.9',
remove this once the suggested tests have been implemented.

2020-09-11 11:35 UTC, yasirfolio3 commented on packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.tests.js
> +    it('should return false if the user-provided value is greater than the condition value', function() {
instead of writing the same test code again and again, can we use loops with test values inside an array, how it's implemented in `go` and `php` Pr's. This comment is applicable for all new tests.

2020-09-11 11:35 UTC, yasirfolio3 commented on packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.tests.js
> +  describe('semver less than match type', function() {
test 
2.0.0 and 2.0.1 returns false
2.0.1 and 2.0.0 returns true
two similar versions return false
1.9 and 2.0.0 returns false
2.0.0 and 1.9 returns true

Keep the null tests and ignore the cases that already exist.

2020-09-11 11:35 UTC, yasirfolio3 commented on packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.tests.js
> +  describe('semver equal to match type', function() {
test 
2.0.0 and 2.0.1 returns false
2.0.1 and 2.0.0 returns false
2.0.1 and 2.0.1 returns true
1.9 and 1.9.1 returns true
1.9.1 and 1.9 returns false

Keep the null tests and ignore the cases that already exist.

2020-09-11 11:35 UTC, yasirfolio3 commented on packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.tests.js
> +  describe('semver less than equal to match type', function() {
test 
2.0.0 and 2.0.1 returns false
2.0.1 and 2.0.0 returns true
2.0.1 and 2.0.1 returns true
1.9 and 1.9.1 returns true
1.9.1 and 1.9 returns true

Keep the null tests and ignore the cases that already exist.

2020-09-11 11:35 UTC, yasirfolio3 commented on packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.tests.js
> +  describe('semver greater than equal to match type', function() {
test 
2.0.0 and 2.0.1 returns true
2.0.1 and 2.0.0 returns false
2.0.1 and 2.0.1 returns true
1.9 and 1.9.1 returns true
1.9.1 and 1.9 returns false

Keep the null tests and ignore the cases that already exist.

2020-09-11 11:35 UTC, yasirfolio3 commented on packages/optimizely-sdk/lib/utils/attributes_validator/index.tests.js
> +          ['2.0.1', '2.0.1'],
please add tests with:
1. build-version
1. pre-release and build-version

2020-09-11 11:35 UTC, yasirfolio3 commented on packages/optimizely-sdk/lib/utils/attributes_validator/index.tests.js
> +      it('should return 1 target version is greater than user version are equal', function() {
please fix this comment.

2020-09-11 11:35 UTC, yasirfolio3 commented on packages/optimizely-sdk/lib/utils/attributes_validator/index.tests.js
> +          ['2.0', '3.0.1'],
add a test that compares:
2.0.0 with 2.1

2020-09-11 11:35 UTC, yasirfolio3 commented on packages/optimizely-sdk/lib/utils/attributes_validator/index.tests.js
> +      it('should return 1 target version is greater than user version are equal', function() {
please fix this comment.

2020-09-11 11:35 UTC, yasirfolio3 commented on packages/optimizely-sdk/lib/utils/attributes_validator/index.tests.js
> +          ['2.3.5', '2.3.1'],
this is already covered.

2020-09-11 11:35 UTC, yasirfolio3 commented on packages/optimizely-sdk/lib/utils/attributes_validator/index.tests.js
> +      it('should return 1 target version is greater than user version are equal', function() {
These cases have been already covered above?

2020-09-11 13:13 UTC, ozayr-zaviar commented on packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.tests.js
> +          app_version: '2.0',
There is another structure. Kindly review it and if needed I can replace it with ruby.

2020-09-11 13:21 UTC, ozayr-zaviar commented on packages/optimizely-sdk/lib/utils/attributes_validator/index.ts
> +    const userVersionBuildIndex = version.indexOf(VERSION_TYPE.IS_BUILD);
version.includes(VERSION_TYPE.IS_PRE_RELEASE) in if is for checking existence of pre-release while the other is to get index of that pre-release

2020-09-11 14:08 UTC, oakbani requested changes
Please address these comments

2020-09-11 14:08 UTC, oakbani commented on packages/optimizely-sdk/lib/utils/semantic_version/index.ts
> +      else if (!userVersionParts[idx].match(/^[0-9]+$/)) {
use a method instead of regex

2020-09-11 14:08 UTC, oakbani commented on packages/optimizely-sdk/lib/utils/semantic_version/index.ts
> +
EOF line

2020-09-11 14:08 UTC, oakbani commented on packages/optimizely-sdk/lib/utils/semantic_version/index.tests.js
> + * Copyright 2016, 2018-2020, Optimizely
Only 2020

2020-09-11 14:08 UTC, oakbani commented on packages/optimizely-sdk/lib/utils/semantic_version/index.tests.js
> +      it('should return 1 target version is greater than user version are equal', function() {
nit. fix it clause

2020-09-11 14:08 UTC, oakbani commented on packages/optimizely-sdk/lib/utils/semantic_version/index.tests.js
> +      it('should return 1 target version is greater than user version are equal', function() {
looks duplicate of above

2020-09-11 14:12 UTC, ozayr-zaviar commented on packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.ts
> +const SEMVER_GREATER_OR_EQUAL_THAN_MATCH_TYPE = 'semverge';
Suggest what should I replace it with

2020-09-14 06:36 UTC, ozayr-zaviar commented on packages/optimizely-sdk/lib/utils/semantic_version/index.ts
> +      else if (!userVersionParts[idx].match(/^[0-9]+$/)) {
there is an issue with built-in method it accepts "-2" or ".2" as a number too.

2020-09-14 06:37 UTC, ozayr-zaviar commented on packages/optimizely-sdk/lib/utils/semantic_version/index.ts
> +      const userVersionReleaseIndex = version.indexOf(VERSION_TYPE.IS_PRE_RELEASE);
It is the same as python and swift. Should I convert it?

2020-09-14 07:24 UTC, ozayr-zaviar commented on packages/optimizely-sdk/lib/utils/semantic_version/index.ts
> +      const userVersionReleaseIndex = version.indexOf(VERSION_TYPE.IS_PRE_RELEASE);
converted according to ruby

2020-09-14 07:48 UTC, yasirfolio3 commented on packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.tests.js
> +        ['2.0', '2.0.0'],
please compare 2.0 with 2.0.1 here.

2020-09-14 07:52 UTC, ozayr-zaviar commented on packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.tests.js
> +        ['2.0', '2.0.0'],
added

2020-09-14 07:57 UTC, yasirfolio3 commented on packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.tests.js
> +    var semverleCondition = {
you have missed these two scenarios:
1.9 and 1.9.1 returns true
1.9.1 and 1.9 returns true

2020-09-14 14:34 UTC, oakbani requested changes
Please fix the IT statements in all of the tests.

2020-09-14 14:34 UTC, oakbani commented on packages/optimizely-sdk/lib/utils/semantic_version/index.ts
> + * Copyright 2016, 2018-2020, Optimizely
Only 2020. as it is  a new file

2020-09-14 14:34 UTC, oakbani commented on packages/optimizely-sdk/lib/utils/semantic_version/index.ts
> + * Evaluate if provided version contains pre-release "-"
doesn't belong to the method below this doc string

2020-09-14 14:34 UTC, oakbani commented on packages/optimizely-sdk/lib/utils/semantic_version/index.ts
> +    return content.match(/^[0-9]+$/) != null ? true : false;
avoid regex. Use some other approach https://stackoverflow.com/questions/175739/built-in-way-in-javascript-to-check-if-a-string-is-a-valid-number

2020-09-14 14:34 UTC, oakbani commented on packages/optimizely-sdk/lib/utils/semantic_version/index.ts
> +    if (typeof targetPrefix === 'string' && typeof targetSuffix === 'string') {
reverse the condition of the main IF such that you return null on the top. And bring all logic before the last else outside if. In short, reduce nesting. The code will become easier to read

2020-09-14 14:34 UTC, oakbani commented on packages/optimizely-sdk/lib/utils/semantic_version/index.ts
> +  }
empty line at the end of page

2020-09-14 14:34 UTC, oakbani commented on packages/optimizely-sdk/lib/utils/semantic_version/index.tests.js
> +      it('should return 1 when target version is greater than user version are equal', function() {
should return 1 when user version  is greater than target version

2020-09-14 14:34 UTC, oakbani commented on packages/optimizely-sdk/lib/utils/semantic_version/index.tests.js
> +          var result = semanticVersion.compareVersion(targetVersion, userVersion)
avoid var. Use const or let.

2020-09-14 14:34 UTC, oakbani commented on packages/optimizely-sdk/lib/utils/semantic_version/index.tests.js
> +      it('should return -1 when targe version is less than user version', function() {
should return -1 when user version is less than target version

2020-09-14 14:34 UTC, oakbani commented on packages/optimizely-sdk/lib/utils/semantic_version/index.tests.js
> +          assert.equal(result, null, `Got result ${result}. Failed for target version: ${targetVersion} and user version: ${userVersion}`);
assert.isNull

2020-09-14 14:34 UTC, oakbani commented on packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.tests.js
> +    it('should return true if the user-provided version is equal than the condition version', function() {
this statement doesn't match the testcase

2020-09-14 14:34 UTC, oakbani commented on packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.tests.js
> +    it('should return false if the user-provided version is greater than the condition version', function() {
is not greater

2020-09-14 14:34 UTC, oakbani commented on packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.tests.js
> +    it('should return true if the user-provided version is less than the condition version', function() {
is greater than or equal to

2020-09-14 14:34 UTC, oakbani commented on packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.tests.js
> +    it('should return true if the user-provided version is equal than the condition version', function() {
equal to the

2020-09-14 16:04 UTC, oakbani approved these changes
Looks good.

2020-09-14 19:05 UTC, msohailhussain requested changes
initial feedback

2020-09-14 19:05 UTC, msohailhussain commented on packages/optimizely-sdk/lib/utils/semantic_version/index.ts
> +        return true;
how it can be true?

2020-09-14 19:05 UTC, msohailhussain commented on packages/optimizely-sdk/lib/utils/semantic_version/index.ts
> +        return true;
how it can be true

2020-09-14 19:05 UTC, msohailhussain commented on packages/optimizely-sdk/lib/utils/semantic_version/index.ts
> +      targetPrefix = version.substring(0, version.indexOf(VERSION_TYPE.IS_PRE_RELEASE));
why not using split?

2020-09-14 19:05 UTC, msohailhussain commented on packages/optimizely-sdk/lib/utils/semantic_version/index.ts
> +    const targetVersionParts = targetPrefix.split(".")
Can you remove empty entries?

2020-09-15 02:53 UTC, ozayr-zaviar commented on packages/optimizely-sdk/lib/utils/semantic_version/index.ts
> +      targetPrefix = version.substring(0, version.indexOf(VERSION_TYPE.IS_PRE_RELEASE));
we need to split one the first occurrence of "-" only while split in js split on all "-".

2020-09-15 02:53 UTC, ozayr-zaviar commented on packages/optimizely-sdk/lib/utils/semantic_version/index.ts
> +        return true;
Implemented according to ruby SDK

2020-09-15 02:53 UTC, ozayr-zaviar commented on packages/optimizely-sdk/lib/utils/semantic_version/index.ts
> +        return true;
Implemented according to ruby SDK

2020-09-15 05:18 UTC, closed without merging