sem-ver implemented
optimizely/javascript-sdk pull request #566
Opened 2020-09-15 05:18 UTC by msohailhussain

## Summary
- The "what"; a concise description of each logical change
- Another change

The "why", or other context.

## Test plan

## Issues
- "THING-1234" or "Fixes #123"

2020-09-15 21:06 UTC, mnoman09 requested changes
Overall looks good. Added some comments.

2020-09-15 21:06 UTC, mnoman09 commented on packages/optimizely-sdk/lib/utils/semantic_version/index.tests.js
> +          ['2.9', '2.9.1']
Add this test where targetSV = 2.1.3 and userver= 2.1.3+build and it should return 0 see this [test](https://github.com/optimizely/java-sdk/blob/2ffd6d9b0c3ad3900a5d93df27f8783024a39f9d/core-api/src/test/java/com/optimizely/ab/config/audience/SemanticVersionTest.java#L193)

2020-09-16 01:42 UTC, ozayr-zaviar commented on packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.tests.js
> +  describe('less than or equal to match type', function() {
ge and le evaluators does not not support alpha beta. Alpha and beta are only for semver

2020-09-16 01:52 UTC, ozayr-zaviar commented on packages/optimizely-sdk/lib/utils/semantic_version/index.tests.js
> +          ['2.9', '2.9.1']
2.1.3 > 2.1.3+build

2020-09-16 01:54 UTC, ozayr-zaviar commented on packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.tests.js
> +      match: 'le',
No version in evaluators (gt, lt, ge, le, etc)

2020-09-16 01:57 UTC, ozayr-zaviar commented on packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.ts
> +  if (conditionValue === null || !isSafeInteger(conditionValue)) {
Consistency in previous written evaluators like greaterThanEvaluator, lessThanEvaluator etc will be lost.

2020-09-16 07:28 UTC, mnoman09 commented on packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.tests.js
> +  describe('less than or equal to match type', function() {
obviously that's what I meant to add few beta alpha cases for semantic versioning in this file too.

2020-09-16 07:34 UTC, mnoman09 commented on packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.tests.js
> +      match: 'le',
same as above. I know what gt lt GE etc is  I was talking about semantic version

2020-09-16 07:36 UTC, mnoman09 commented on packages/optimizely-sdk/lib/utils/semantic_version/index.tests.js
> +          ['2.9', '2.9.1']
No this is a corner case that we covered in all other sdks. you can see java link I shared above.

2020-09-16 08:32 UTC, mnoman09 commented
lgtm

2020-09-16 08:33 UTC, mnoman09 approved these changes
lgtm

2020-09-16 19:16 UTC, closed without merging

2020-09-16 20:37 UTC, mjc1283 commented on packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.ts
> +  if (conditionValue === null || !isSafeInteger(conditionValue)) {
I agree with @mnoman09. If there is repeated logic for checking user inputs for numeric comparison conditions, let's use a shared helper function. If the logic is not exactly the same or it is awkward to share, don't worry about it.

2020-09-16 20:37 UTC, mjc1283 commented on packages/optimizely-sdk/lib/utils/enums/index.ts
> +}
TypeScript has `enum` and `const enum` declarations. Some can be compiled into constant values leading to smaller code size. Please check the [documentation for enums](https://www.typescriptlang.org/docs/handbook/enums.html). Let's not use an object with long property names unless necessary, to avoid bloating the code.

2020-09-16 20:37 UTC, mjc1283 commented on packages/optimizely-sdk/lib/utils/semantic_version/index.ts
> +  export function compareVersion(conditionsVersion: string, userProvidedVersion: string): number | null {
Please add a documentation comment

2020-09-16 20:37 UTC, mjc1283 commented on packages/optimizely-sdk/lib/utils/semantic_version/index.ts
> +      return null;
Style preference is to always use brackets with if statements.

2020-09-16 20:37 UTC, mjc1283 commented on packages/optimizely-sdk/lib/utils/semantic_version/index.ts
> +      }
Please try to simplify the control flow, there are a lot of nested conditionals.

2020-09-16 20:37 UTC, mjc1283 commented on packages/optimizely-sdk/lib/utils/semantic_version/index.ts
> +    return content.match(/^[0-9]+$/) != null ? true : false;
Is this equivalent?
```suggestion
    return /^\d+$/.test(content);
```
(see: [Regular Expression docs for JS](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Character_Classes))

Also: I suggest declaring regular expression once higher up in module scope, then reference here (`DIGIT_STRING_REGEXP.test(content)`).

2020-09-16 20:37 UTC, mjc1283 commented on packages/optimizely-sdk/lib/utils/semantic_version/index.ts
> +    return version.includes(' ');
What about other space characters (tab, newline, etc.)? Should we use space regexp character class?
```suggestion
    return /\s/.test(version);
```
- Minor concern: `String.prototype.includes` is not supported in very old JS environments.
- Is there any performance difference between `String.prototype.includes` and regular expression `test` method?

2020-09-16 20:37 UTC, mjc1283 commented on packages/optimizely-sdk/lib/utils/semantic_version/index.ts
> +      targetPrefix = version.substring(0, version.indexOf(VERSION_TYPE.IS_PRE_RELEASE));
`IS_PRE_RELEASE` sounds like a boolean. I prefer `PRE_RELEASE_VERSION_DELIMITER`.

2020-09-16 20:37 UTC, mjc1283 commented on packages/optimizely-sdk/lib/utils/semantic_version/index.ts
> +        targetPrefix = version.substring(0, version.indexOf(VERSION_TYPE.IS_BUILD));
`BUILD_VERSION_DELIMITER`

2020-09-16 20:37 UTC, mjc1283 commented on packages/optimizely-sdk/lib/utils/semantic_version/index.ts
> +   *                    null if given version is in invalid format
Would consumer code be clearer if we had an interface for semantic version components?
```ts
interface SemanticVersionComponents {
  major: number;
  minor: number;
  patch: number;
  preRelease?: number
  build?: number
}
```

Then:
```ts
function splitVersion(version: string): SemanticVersionComponents | null {
```