feat: Create index.d.ts file for decision_service
optimizely/javascript-sdk pull request #568
Opened 2020-09-15 19:07 UTC by yavorona

## Summary
Create `index.d.ts` file for decision_service module

## Test plan

2020-09-15 19:12 UTC, mikeng13 commented on packages/optimizely-sdk/lib/core/decision_service/index.d.ts
> + * Copyright 2018-2020, Optimizely
Should just be 2020

2020-09-15 19:12 UTC, mikeng13 commented on packages/optimizely-sdk/lib/core/decision_service/index.d.ts
> +    __datafileStr: string;
Shouldn't document private properties

2020-09-15 19:12 UTC, mikeng13 commented on packages/optimizely-sdk/lib/core/decision_service/index.d.ts
> +  interface Event {
A lot of these entities are being defined in #567 already. We should reuse them.

2020-09-16 22:40 UTC, mjc1283 requested changes
Requesting changes to locate type definitions in the appropriate module and import them into the consumers.

2020-09-16 22:40 UTC, mjc1283 commented on packages/optimizely-sdk/lib/core/decision_service/index.d.ts
> +  interface ConfigObj {
This should be imported from the project config module (see PR https://github.com/optimizely/javascript-sdk/pull/567)

2020-09-16 22:40 UTC, mjc1283 commented on packages/optimizely-sdk/lib/core/decision_service/index.d.ts
> +  export interface UserProfileService {
Are `UserProfileService` and/or `UserProfile` needed in any other modules? There might be a more natural place for these to live.

2020-09-16 22:40 UTC, mjc1283 commented on packages/optimizely-sdk/lib/core/decision_service/index.d.ts
> +  interface Event {
Agree, for all the entity types that are related to or located in project config.

2020-09-16 22:40 UTC, mjc1283 commented on packages/optimizely-sdk/lib/core/decision_service/index.d.ts
> +  type ConditionTree<Leaf> = Leaf | unknown[];
Should be imported from `condition_tree_evaluator`

2020-09-16 22:40 UTC, mjc1283 commented on packages/optimizely-sdk/lib/index.d.ts
> -
This, as well as `UserProfile`, still need to be exported out of this file. We can't break compatibility with what we previously were exporting.

2020-09-17 16:08 UTC, yavorona commented on packages/optimizely-sdk/lib/core/decision_service/index.d.ts
> +  export interface UserProfileService {
I moved them back based on the comment below.

2020-09-17 17:15 UTC, mjc1283 requested changes
LGTM but this depends on #567. If you want to merge it first, let's put more of a stub or skeleton in project_config/index.d.ts which can be filled in later by #567

2020-09-17 17:15 UTC, mjc1283 commented on packages/optimizely-sdk/lib/core/decision_service/index.d.ts
> +  export interface UserProfileService {
> We are importing them from a root-level module to here, which is an anti-pattern.

Agreed. Let's keep them in decision service like you originally had, and consider moving them later on if it makes sense.

2020-09-17 17:15 UTC, mjc1283 commented on packages/optimizely-sdk/lib/core/project_config/index.d.ts
> +type ConditionTree<Leaf> = Leaf | unknown[];
Import from `condition_tree_evaluator`

2020-09-17 17:38 UTC, yavorona commented on packages/optimizely-sdk/lib/core/decision_service/index.d.ts
> +  export interface UserProfileService {
Sounds good. `UserAttributes` would also need to be moved here for now to avoid anti-pattern.

2020-09-21 17:56 UTC, mjc1283 requested changes
Still waiting for update after #567 is complete

2020-09-23 22:46 UTC, mjc1283 approved these changes

2020-09-23 22:46 UTC, mjc1283 commented on packages/optimizely-sdk/lib/core/decision_service/index.d.ts
> +    decisionSource: string;
We might want to use an `enum` for this. Can be updated later if so.

2020-09-23 22:51 UTC, merged