Semver added
optimizely/javascript-sdk pull request #571
Opened 2020-09-16 19:17 UTC by ozayr-zaviar

## Summary
- Semantic version added
- Greater than or equal (ge) and less than or equal (le) evaluator added

## Test plan
- All relevant test cases added

2020-09-17 19:20 UTC, msohailhussain commented on packages/optimizely-sdk/lib/utils/semantic_version/index.ts
> +    return new RegExp(/^\d+$/).test(content);
remove `RegExp`
`/^\d+$/.test(content)`

2020-09-17 19:22 UTC, msohailhussain commented on packages/optimizely-sdk/lib/utils/semantic_version/index.ts
> +    return new RegExp(/\s/).test(version);
`/\s/.test(version)`

2020-09-17 19:31 UTC, msohailhussain commented on packages/optimizely-sdk/lib/utils/semantic_version/index.ts
> +  function splitVersion(version: string): string[] | null {
https://github.com/optimizely/javascript-sdk/pull/566#discussion_r489739380

2020-09-17 19:34 UTC, msohailhussain commented on packages/optimizely-sdk/lib/utils/semantic_version/index.ts
> +  function splitVersion(version: string): string[] | null {
@mjc1283 I think, parsing condition would be bit difficult if we return SemVer interface like you said in the comment.
One of the reason, we are allowing all variations. Version can have the following forms. 
major
major.minor
major.minor.patch
major.minor.patch.pre-release
major.minor.patch.pre-release+build
major.minor.patch+build

2020-09-17 19:57 UTC, msohailhussain commented on packages/optimizely-sdk/lib/utils/semantic_version/index.ts
> +    const isPreReleaseInconditionsVersion = isPreReleaseVersion(conditionsVersion);
I think we don't really need this variable, let me think. btw
`x isPreReleaseInConditionsVersion`

2020-09-18 18:25 UTC, mjc1283 requested changes

2020-09-18 18:25 UTC, mjc1283 commented on packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.ts
> +function validateValues(condition: Condition, userAttributes: UserAttributes): boolean {
```suggestion
function validateValuesForNumericCondition(condition: Condition, userAttributes: UserAttributes): boolean {
```

2020-09-18 18:25 UTC, mjc1283 commented on packages/optimizely-sdk/lib/utils/semantic_version/index.ts
> +/**
This file has several style/formatting issues. Please see other files and follow the same style for indentation, brackets on the same line as `if` statements, always use brackets with `if` statements. I will try update the linter to enforce these.

2020-09-21 16:34 UTC, mjc1283 approved these changes

2020-09-21 17:43 UTC, merged