feat: added declaration file for event builder index.d.ts
optimizely/javascript-sdk pull request #573
Opened 2020-09-22 18:27 UTC by msohailhussain

## Summary
- Added declaration file under optimizely-sdk/lib/core/event_builder/index.d.ts 

## Test plan
- All unit tests must work fine.

2020-09-22 18:29 UTC, msohailhussain commented
This PR is based on project config declaration branch, before merging into master, we'll have to rebase once project config declaration file PR is merged.

2020-09-22 21:18 UTC, yavorona commented on packages/optimizely-sdk/lib/core/event_builder/index.d.ts
> +    buildImpressionEvent(config: ImpressionConfig): ImpressionEvent;
I think `buildConversionEvent` and `buildImpressionEvent` should live in its own `event_helpers.d.ts` file as these methods are imported separately from `event_builder`

2020-09-23 05:37 UTC, msohailhussain commented on packages/optimizely-sdk/lib/core/event_builder/index.d.ts
> +    buildImpressionEvent(config: ImpressionConfig): ImpressionEvent;
yeah you are right, i missed it.

2020-09-24 16:33 UTC, yavorona commented on packages/optimizely-sdk/lib/core/event_builder/event_helpers.d.ts
> +  import { EventTags, UserAttributes } from '@optimizely/optimizely-sdk';
please rebase and update these imports. `UserAttributes` is now live in `shared_types.ts`. EventTags can also be moved there and be imported here.

2020-09-24 16:33 UTC, yavorona commented on packages/optimizely-sdk/lib/core/event_builder/index.d.ts
> +  import { EventTags, UserAttributes } from '@optimizely/optimizely-sdk';
Same comment as above.

2020-09-24 22:43 UTC, mjc1283 requested changes

2020-09-24 22:43 UTC, mjc1283 commented on packages/optimizely-sdk/lib/core/event_builder/event_helpers.d.ts
> +  interface ImpressionEvent {}
It seems wrong to keep these empty, presumably the caller would do something with it. Even if it's passing it on to event processor. The event processor exposes type definitions, so we should be able to match or use those.

2020-09-24 22:43 UTC, mjc1283 commented on packages/optimizely-sdk/lib/core/event_builder/event_helpers.d.ts
> +  import { EventTags, UserAttributes } from '@optimizely/optimizely-sdk';
Agree, please make this change.

2020-09-24 22:43 UTC, mjc1283 commented on packages/optimizely-sdk/lib/core/event_builder/event_helpers.d.ts
> +    buildImpressionEvent(config: ImpressionConfig): ImpressionEvent;
These functions should be exported directly from this module, not within an `EventHelpers` interface

2020-09-24 22:43 UTC, mjc1283 commented on packages/optimizely-sdk/lib/core/event_builder/index.d.ts
> +    getImpressionEvent(options: ImpressionOptions): EventLoggingEndpoint;
These functions should be exported directly from this module, not within an `EventBuilder` interface

2020-09-25 23:57 UTC, mjc1283 approved these changes

2020-09-26 00:27 UTC, yavorona commented on packages/optimizely-sdk/lib/core/event_builder/index.d.ts
> +    attributes: import('../../shared_types').UserAttributes;
`attributes`, `eventKey`, and `logger` are optional attributes. please add `?` to it:
```
attributes?: import('../../shared_types').UserAttributes;
eventKey?: eventKey;
logger?: LogHandler;
```

2020-09-26 00:32 UTC, yavorona commented on packages/optimizely-sdk/lib/core/event_builder/index.d.ts
> +    attributes: import('../../shared_types').UserAttributes;
`attributes` and `eventTags` are optional attributes.

2020-09-26 00:36 UTC, yavorona requested changes
Looks great except for a couple of minor comments. @mjc1283 please give :+1:   if you agree

2020-09-28 15:40 UTC, yavorona approved these changes

2020-09-28 16:18 UTC, merged