feat: Convert optimizely module to TS
optimizely/javascript-sdk pull request #576
Opened 2020-09-25 06:06 UTC by yavorona

## Summary

- Convert `optimizely` module from JS to TS.

## Test plan
- Existing unit tests and local bundle

2020-09-28 20:49 UTC, yavorona commented on packages/optimizely-sdk/lib/shared_types.ts
> + * Temprorary placement of LogTierV1EventProcessorConfig
I originally saved `LogTierV1EventProcessorConfig` in `event-processor/src/eventProcessor.ts`, which resulted in travis lint failure due to event-processor package not being set up https://travis-ci.org/github/optimizely/javascript-sdk/builds/731087456, so I moved it here for now

2020-09-28 20:55 UTC, yavorona commented on packages/optimizely-sdk/lib/core/project_config/index.js
> +  return getExperimentStatus(projectConfig, experimentKey) === EXPERIMENT_RUNNING_STATUS;
existed previously `this....`  resulted in browser test failures. I do not think we needed it here in the first place.
LMKWYT @mjc1283

2020-09-28 23:58 UTC, mjc1283 requested changes
- I recommended some small refactors to modernize the code
- `shared_types` is getting pretty big, which could be a sign of poor organization. Are there any types in there that should live in the modules that they're used in?
- The `as` type casts on the return value in the feature variable getter methods - there might be a way to make this more elegant using user-defined type guard functions. But no need to spend a lot of time on that rabbit hole right now.

2020-09-28 23:58 UTC, mjc1283 commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +  private eventProcessor: eventProcessor.EventProcessor;
It is weird that we don't consistently follow this double-underscore naming convention. Let's take this opportunity to clean it up. Since we have the `private` keyword, we don't need the naming convention anymore to hint that they're private.

2020-09-28 23:58 UTC, mjc1283 commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +  constructor(config: projectConfig.ProjectConfig) {
I think `ProjectConfig` and the config object here are two separate things. Let's have a separate interface for the values accepted by the `Optimizely` constructor.

2020-09-28 23:58 UTC, mjc1283 commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +      function(this: Optimizely, configObj: projectConfig.ProjectConfig) {
I think we can use an arrow function instead of `bind`

2020-09-28 23:58 UTC, mjc1283 commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +  return this.__isOptimizelyConfigValid && !!this.projectConfigManager.getConfig();
Indentation

2020-09-28 23:58 UTC, mjc1283 commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +    this.eventProcessor.process(impressionEvent as eventProcessor.ProcessableEvent);
We should define in our `ImpressionEvent` interface what is returned from `buildImpressionEvent`. Then the type checker will let us know if that's incompatible with the `ProcessableEvent` expected by the event processor.

2020-09-28 23:58 UTC, mjc1283 commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +    } as LogTierV1EventProcessorConfig);
The `as LogTierV1EventProcessorConfig` could be covering up some errors. I recommend removing it.

2020-09-28 23:58 UTC, mjc1283 commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +      this.__emitNotificationCenterTrack(eventKey, userId, attributes as UserAttributes, eventTags);
Similar to above comments, let's not use type casting with `as`.

2020-09-28 23:58 UTC, mjc1283 commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +          function(this: Optimizely, feature: FeatureFlag): void {
Recommend arrow function

2020-09-28 23:58 UTC, mjc1283 commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +          }
Recommend changing to `forEach` instead of loop with index

2020-09-28 23:58 UTC, mjc1283 commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +      featureFlag.variables.forEach(function (this: Optimizely, variable: FeatureVariable) {
Recommend arrow function.

2020-09-28 23:58 UTC, mjc1283 commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +        function(this: Optimizely, readyTimeoutId: string ) {
Recommend arrow function

2020-09-28 23:58 UTC, mjc1283 commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +    const onReadyTimeout = function(this: Optimizely) {
Recommend arrow function

2020-09-28 23:58 UTC, mjc1283 commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +    return Promise.race([this.__readyPromise, timeoutPromise]) as Promise<{ success: boolean; reason?: string | undefined; }>;
Recommend removing `as` type cast

2020-09-28 23:58 UTC, mjc1283 commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +      eventTags = this.__filterEmptyValues(eventTags as EventTags);
Recommend removing `as` type cast

2020-09-28 23:58 UTC, mjc1283 commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +   *                                                config Obj is null
Interesting - looks like at some point, this function was changed, but they didn't update the comment. It is not returning `string | null`, it is actually doing the type cast (calling `projectConfig.getTypeCastValue`). Probably the right return type is `unknown`.

2020-09-28 23:58 UTC, mjc1283 commented on packages/optimizely-sdk/lib/core/project_config/index.d.ts
> +export function getTypeCastValue<T>(variableValue: string, type: string, logger: LogHandler): T;
Looking a little closer at `getTypeCastValue`, I think this could be improved (not necessary to do in this PR):

- The second argument`type` can be defined as an `enum`.
- Not sure the generic `T` is helpful here. I could see it helping if we wanted to restrict it to the feature variable types like `T extends string | number | boolean`, but with JSON variables, we're calling `JSON.parse`, the return type of which is broader. I would go with `unknown` instead of the generic `T`.

2020-09-29 00:34 UTC, yavorona commented on packages/optimizely-sdk/lib/shared_types.ts
> + * Temprorary placement of LogTierV1EventProcessorConfig
`LogTierV1EventProcessorConfig` is the interface that includes `maxQueueSize`, which is not included in `LogTierV1EventProcessor` that is being used in this case. I used `{ ... } as LogTierV1EventProcessorConfig` as a temporary solution until we implement it in the event-processor.

2020-09-29 17:41 UTC, yavorona commented on packages/optimizely-sdk/lib/core/project_config/entities.ts
> +  variableKeyMap?: {[key: string]: FeatureVariable}
you are right, this should not be optional.

2020-09-29 18:03 UTC, yavorona commented on packages/optimizely-sdk/lib/core/project_config/index.d.ts
> +  experimentKeyMap:{[key: string]: Experiment};
in the Optimizely class constructor, the logger is being used from the config object as `this.logger = config.logger`, so I think we would need to have it included here. Same applies to attributes such as clientEngine, clientVersion, errorHandler, eventDispatcher, isValidInstance, datafile, jsonSchemaValidator, sdkKey, and other ones. Excluding any of these properties will result in the compiler error.  @mjc1283 Please LMK if you think there is a better way to go about it.

2020-09-29 20:07 UTC, yavorona commented on packages/optimizely-sdk/lib/core/project_config/project_config_manager.js
> +  createProjectConfigManager: createProjectConfigManager,
Yes, and also to distinguish between `ProjectConfigManager` interface and the method that returns `ProjectConfigManager` similarly to how we defined notification_center.

2020-09-29 21:52 UTC, yavorona commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +    } as LogTierV1EventProcessorConfig);
`LogTierV1EventProcessorConfig` is the interface that includes `maxQueueSize`, which is not included in `LogTierV1EventProcessor` that is being used in this case. I used `{ ... } as LogTierV1EventProcessorConfig` as a temporary solution until we implement it in the event-processor.

2020-09-29 22:01 UTC, yavorona commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +      eventTags = this.__filterEmptyValues(eventTags as EventTags);
I removed it by updating the signature of the  `__filterEmptyValues` to 
```
__filterEmptyValues(map: EventTags | undefined): EventTags | undefined { ... }
```

2020-09-29 22:05 UTC, yavorona commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +      this.__emitNotificationCenterTrack(eventKey, userId, attributes as UserAttributes, eventTags);
`this.__emitNotificationCenterTrack` in this case should have been accepting attributes and eventTags as optional parameters. I updated its signature and removed `as` type casting here.

2020-09-30 00:04 UTC, yavorona commented on packages/optimizely-sdk/lib/shared_types.ts
> +  [key: string]: string | number | null;
I changed `EventTags` type to match the event-processor, which did not cause any issues in optimizely-sdk. However, I still think we should include `boolean` as an acceptable value. LMKWYT @mjc1283

2020-09-30 00:07 UTC, yavorona commented on packages/optimizely-sdk/lib/shared_types.ts
> +  variationKeyMap?: {[key: string]: Variation}
No, it should not be.

2020-09-30 18:53 UTC, yavorona commented
> * I recommended some small refactors to modernize the code
> * `shared_types` is getting pretty big, which could be a sign of poor organization. Are there any types in there that should live in the modules that they're used in?
> * The `as` type casts on the return value in the feature variable getter methods - there might be a way to make this more elegant using user-defined type guard functions. But no need to spend a lot of time on that rabbit hole right now.

The biggest part of the `shared_files` contains Optimizely Config Entities, which originally lived in our published index.d.ts file. 
If I keep it there, we would not be able to access it in our optimizely module where is it being used. Same happens if I move Optimizely Config Entities to project_config_manager, where it is also being used. @mjc1283  LMK if you think there is a better place for them to live.
 I haven’t found a good way to avoid using `as` type casts in our feature variable getters, but I will spend more time to think about it!

2020-10-01 00:07 UTC, yavorona commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +    } as LogTierV1EventProcessorConfig);
It is now removed. The compiler error from missing `maxQueueSize` in `LogTierV1EventProcessor` constructor was avoided by assigning the object to another variable before passing it to `LogTierV1EventProcessor`.

2020-10-01 00:09 UTC, yavorona commented on packages/optimizely-sdk/lib/index.d.ts
> +  export type EventTags = {
Per our discussion, `EventTags` should not accept boolean as a value

2020-10-01 22:46 UTC, mjc1283 requested changes
Looks really good!

2020-10-01 22:46 UTC, mjc1283 commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +    stringInputs?: unknown,
Looking at the callers, it appears we always pass an object. This will simplify the implementation:

```suggestion
    // Later we could make these camelCase, snake_case is weird
    stringInputs: Record<'feature_key' | 'user_id' | 'variable_key' | 'experiment_key', unknown>
```

2020-10-02 19:14 UTC, yavorona commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +    stringInputs?: unknown,
Made some modification to avoid missing properties compiler error and added `event_key`:
`Partial<Record<'feature_key' | 'user_id' | 'variable_key' | 'experiment_key' | 'event_key', unknown>>`

2020-10-02 20:13 UTC, yavorona commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +import { EventDispatcher } from '@optimizely/js-sdk-event-processor';
Found incompatibility in our EventDispatcher interface with the one defined in event processor. 
The callback in `dispatchEvent` method is updated from `callback: () => void` to `callback: (response: { statusCode: number; }) => void`. I noted this change in the log.

2020-10-05 19:17 UTC, mjc1283 approved these changes
Great work!

2020-10-05 19:17 UTC, mjc1283 commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +      if (typeof stringInputs === 'object' && stringInputs !== null) {
I think this check is not needed anymore - `stringInputs` has to be a non-null object.

2020-10-05 19:17 UTC, mjc1283 commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +      resolveTimeoutPromise = resolve;
Missing indentation

2020-10-05 20:37 UTC, yavorona commented on packages/optimizely-sdk/lib/core/notification_center/index.d.ts
> +}
Works great!

2020-10-05 21:06 UTC, merged