converted entry level modules to ts
optimizely/javascript-sdk pull request #590
Opened 2020-10-06 05:53 UTC by ozayr-zaviar

## Summary
- Converted `packages\optimizely-sdk\lib\index.node.js` to TS
- Converted `packages\optimizely-sdk\lib\index.browser.js` to TS
- Converted `packages\optimizely-sdk\lib\index.react_native.js` to TS

## Test plan
- All existing unit tests should pass
- All existing test cases on FSC should pass

2020-10-06 18:43 UTC, msohailhussain requested changes
Please address and fix all issues.

2020-10-06 18:43 UTC, msohailhussain commented on packages/optimizely-sdk/lib/index.browser.ts
> +import { LocalStoragePendingEventsDispatcher } from '@optimizely/js-sdk-event-processor';
why left blank line?

2020-10-06 18:43 UTC, msohailhussain commented on packages/optimizely-sdk/lib/index.browser.ts
> +interface Config {
document it. we should export as well? not sure.

2020-10-06 18:43 UTC, msohailhussain commented on packages/optimizely-sdk/lib/index.browser.ts
> +    const optimizelyConfig = assign(
why changed to `optimizelyConfig`. `OptimizelyConfig` is different than what is expected here.

2020-10-06 18:43 UTC, msohailhussain commented on packages/optimizely-sdk/lib/index.browser.ts
> +    ) as OptimizelyConfig;
this is not correct.

2020-10-06 18:43 UTC, msohailhussain commented on packages/optimizely-sdk/lib/index.browser.ts
> +const createInstance = function (config: Config): Optimizely | null {
`function(config: Config)` should be without space.

2020-10-06 18:43 UTC, msohailhussain commented on packages/optimizely-sdk/lib/index.react_native.ts
> +interface Config {
this is being used in all index level files, we should move it to shared_types.

2020-10-06 18:43 UTC, msohailhussain commented on packages/optimizely-sdk/lib/shared_types.ts
> +export interface OptimizelyConfig {
Isn't it defined [here](https://github.com/optimizely/javascript-sdk/blob/master/packages/optimizely-sdk/lib/optimizely/index.ts#L56). 
Please use the right term. `[OptimizelyConfig](https://github.com/optimizely/javascript-sdk/blob/master/packages/optimizely-sdk/lib/core/optimizely_config/index.js)` is different.

2020-10-06 22:12 UTC, msohailhussain requested changes
please address.

2020-10-06 22:12 UTC, msohailhussain commented on packages/optimizely-sdk/lib/index.browser.ts
> +const __internalResetRetryState = function (): void {
we have default indentation without `space` please fix at all places.

2020-10-06 22:12 UTC, msohailhussain commented on packages/optimizely-sdk/lib/index.react_native.ts
> +import * as configValidator from './utils/config_validator';
why not modified in other files?

2020-10-06 22:12 UTC, msohailhussain commented on packages/optimizely-sdk/lib/shared_types.ts
> +export interface Config {
add documentation for both `Config` and `ConfigObj`

2020-10-07 16:30 UTC, zashraf1985 requested changes
Looks good overall. I have some concerns on the naming of certain variables and Interfaces. Secondly, as a general rule of typescript conversion. Please feel free to simplify some code to use latest javascript constructs. A lot of code can be modernized and simplified  as now we are using typescript. For example: using spread operators instead of assign, using arrow functions where they make code look simpler etc.

2020-10-07 16:30 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/index.browser.ts
> +import { LocalStoragePendingEventsDispatcher } from '@optimizely/js-sdk-event-processor';
Its probably a line break between module imports and internal imports

2020-10-07 16:30 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/index.browser.ts
> +    const internalConfig = assign(
Since you  are now in TS, you dont need to use assign. you can probably use spread syntax to override values.

2020-10-07 16:30 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/index.browser.ts
> +    ) as ConfigObj;
This conversions `as ConfigObj` might not be needed. Are you sure its throwing error without this.?

2020-10-07 16:30 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/index.node.ts
> +    const internalConfig = assign(
You can use spread operator here too instead of assign. Also rename internalConfig to something better

2020-10-07 16:30 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/shared_types.ts
> +export interface ConfigObj {
I see why you need two different configs/options but `ConfigObj` is not a good name. Two sets of feedback on this one.
1. One can be inherited from the other because outer options are a subset of internal options.
2. Names should be relevant. `Config` makes sense if its the only interface we use. `ConfigObj` does not make sense at all. And when we have two different objects with many similar properties, both `Config` and `ConfigObj` look like inappropriate choices. One choice could be `SDKOptions` for the outer interface and `OptimizelyOptions` for the internal . You can give it a thought and try to come up with better and more appropriate names.

2020-10-07 16:30 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/index.react_native.ts
> + * @return {Optimizely} the Optimizely object
this doc comment should be updated to reflect that it can also return null.

2020-10-08 11:36 UTC, ozayr-zaviar commented on packages/optimizely-sdk/lib/index.browser.ts
> +    ) as ConfigObj;
Yes it is throwing error without `as ConfigObj`

2020-10-09 02:52 UTC, yavorona commented on packages/optimizely-sdk/lib/index.browser.ts
> +    const modifiedConfig = {...additionalEntities, ...config, ...optimizelyLoggers}  as OptimizelyOptions;
I think can avoid using `as` type cast here by updating `isValidInstance` in `SDKOptions` object to not be optional.

2020-10-09 02:56 UTC, yavorona commented on packages/optimizely-sdk/lib/index.browser.ts
> +          function () {
Recommend using arrow function here

2020-10-09 03:00 UTC, yavorona commented on packages/optimizely-sdk/lib/index.node.ts
> +    const modifiedConfig = {...additionalEntities, ...config, ...optimizelyLoggers}  as OptimizelyOptions;
Same as in browser entry module: we can avoid using `as` type cast here by updating `isValidInstance` in `SDKOptions` object to not be optional.

2020-10-09 03:02 UTC, yavorona commented on packages/optimizely-sdk/lib/index.react_native.ts
> +    const modifiedConfig = {...additionalEntities, ...config, ...optimizelyLoggers}  as OptimizelyOptions;
Same as comment above: we can avoid using `as` type cast here by updating `isValidInstance` in `SDKOptions` object to not be optional.

2020-10-14 18:58 UTC, msohailhussain commented on packages/optimizely-sdk/lib/index.browser.ts
> +    const modifiedConfig = {...additionalEntities, ...config, ...optimizelyLoggers};
`updatedConfig`

2020-10-14 18:58 UTC, msohailhussain commented on packages/optimizely-sdk/lib/index.browser.ts
> +    const additionalEntities = {
need to change variable name.

2020-10-14 19:45 UTC, zashraf1985 requested changes
Detailed comments provided in browser entry file also apply to the other two entry points. I have NOT duplicated comments to all three entry points.

2020-10-14 19:45 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/index.browser.ts
> +    const modifiedConfig = {...additionalEntities, ...config, ...optimizelyLoggers};
the names `additionalEntities` and `optimizelyLoggers` do not make much sense. Instead of building interim objects, you can add those directly when building the `modifiedConfig` or `updatedConfig` object. something like
```
const modifiedConfig = {
  clientEngine: enums.JAVASCRIPT_CLIENT_ENGINE,
  eventBatchSize: DEFAULT_EVENT_BATCH_SIZE,
  eventFlushInterval: DEFAULT_EVENT_FLUSH_INTERVAL,
  eventDispatcher: eventDispatcher,
  ...config,
  logger: logger,
  errorHandler: getErrorHandler(),
}
```

2020-10-14 19:45 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/index.browser.ts
> +      modifiedConfig.eventBatchSize = DEFAULT_EVENT_BATCH_SIZE;
declaring this object above with such detail and then mutating some of the elements makes it confusing. more cleaner code could be to assign `eventBatchSize` to a local variable and then declare the `optimizelyOptions` once at the end.

2020-10-14 19:45 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/index.browser.ts
> +      modifiedConfig.eventFlushInterval = DEFAULT_EVENT_FLUSH_INTERVAL;
The same comment about `eventBatchSize` applies here too

2020-10-14 19:45 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/index.browser.ts
> +        const unloadEvent = 'onpagehide' in window ? 'pagehide' : 'unload';
Nonblocking: Can we move these string values somewhere inside constants

2020-10-14 19:45 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/index.browser.ts
>            },
```suggestion
          optimizely.close,
```

2020-10-14 19:45 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/index.browser.ts
>  export default {
since this is now converted to TS. The ones that are not renamed while exporting do not need name and value pair. It can now be.
```
export default {
  logging: loggerPlugin,
  errorHandler: defaultErrorHandler,
  eventDispatcher: defaultEventDispatcher,
  enums,
  setLogger: setLogHandler,
  setLogLevel,
  createInstance,
  __internalResetRetryState,
};

2020-10-14 19:45 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/index.d.ts
> +  export type SDKOptions = import ('./shared_types').SDKOptions;
I am not sure about this but you can give it a try. Since `SDKOptions` is not used here, you can perhaps export it directly by doing something like
`export { SDKOptions } from './sharedTypes`
I am not totally sure about it. I might be totally wrong.

2020-10-14 19:45 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/index.browser.ts
> +    const modifiedConfig = {...additionalEntities, ...config, ...optimizelyLoggers};
Also you can probably name it `optimizelyOptions` instead of `modifiedConfig`

2020-10-14 19:45 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/shared_types.ts
> + * Config required to create optimizely object
Probably change it to `Options required`

2020-10-14 19:45 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/shared_types.ts
> +}
I believe we should probably add one line documentation comment to each option here. This might help while autogenerating docs

2020-10-14 19:45 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/shared_types.ts
> +  logger: LogHandler;
NIT: Sort them alphabetically maybe?

2020-10-14 19:45 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/shared_types.ts
> +  isValidInstance: boolean;
NIT: Sort them alphabetically maybe?

2020-10-16 16:53 UTC, mjc1283 requested changes
Mostly LGTM, two small requests

2020-10-16 16:53 UTC, mjc1283 commented on packages/optimizely-sdk/lib/index.browser.ts
> +          optimizely.close,
Have you tested this change? I think it won't work. `close` is not bound to `optimizely`, so when it is invoked it may not have the right `this` value.

2020-10-16 16:53 UTC, mjc1283 commented on packages/optimizely-sdk/lib/shared_types.ts
> +}
I think `OptimizelyOptions` should be defined in `lib/optimizely/index.ts`.

2020-10-19 17:47 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/index.browser.ts
> +          optimizely.close,
Good catch! I asked uzair to change it this way to make it look simple and clean but it didn't occur to me that it will mess up with `this`. @ozayr-zaviar ! please change it back to what it was or an arrow function whatever makes sense.

2020-10-19 17:57 UTC, mjc1283 approved these changes

2020-10-19 18:36 UTC, msohailhussain approved these changes
lgtm

2020-10-19 18:46 UTC, zashraf1985 approved these changes
LGTM! Great Work @ozayr-zaviar

2020-10-19 18:51 UTC, merged