feat: Upgrade TypeScript to v4.0.3 in optimizely-sdk package
optimizely/javascript-sdk pull request #597
Opened 2020-10-09 00:36 UTC by yavorona

## Summary
- Upgrade TypeScript `optimizely-sdk` package to v4.0.3
- Use default export object for `fns` module to avoid stubbing issue

## Test plan
 - Existing unit tests
## Issues

2020-10-09 20:29 UTC, spham1412 requested changes
One question: since you added default export, the `import { function } from 'fns';` should work as it as, isn't it?

2020-10-09 20:29 UTC, spham1412 commented on packages/optimizely-sdk/lib/utils/fns/index.ts
> +}
You can just do:

```
export default {
  assign,
  currentTimestamp,
  isSafeInteger,
  keyBy,
  uuid,
  isNumber,
}
```

2020-10-09 20:29 UTC, spham1412 commented on packages/optimizely-sdk/lib/utils/event_processor_config_validator/index.ts
> +import fns from '../fns';
Since you added the default export, the old implementation should work as it is, no need to change to import the whole `fns`?

2020-10-09 21:14 UTC, yavorona commented on packages/optimizely-sdk/lib/utils/event_processor_config_validator/index.ts
> +import fns from '../fns';
Default object export does not allow destructured imports in this case.

2020-10-12 16:17 UTC, mjc1283 commented on packages/optimizely-sdk/lib/utils/fns/index.ts
> +const assign = function(target: any, ...sources: any[]): any {
Why do these need to be declared with `const`, instead of `function`?

2020-10-12 17:49 UTC, yavorona commented on packages/optimizely-sdk/lib/utils/fns/index.ts
> +const assign = function(target: any, ...sources: any[]): any {
Good point. No need for that.

2020-10-12 17:50 UTC, mjc1283 approved these changes

2020-10-12 18:01 UTC, spham1412 approved these changes

2020-10-12 18:06 UTC, merged