feat(flag-decisions): Add support for sending flag decisions
optimizely/javascript-sdk pull request #599
Opened 2020-10-13 16:50 UTC by yavorona

## Summary
- Add experiment/feature flag key, and  decision type to impression events.
- Send events for ALL decision types if sendFlagDecisions is enabled.
- Add metadata field to capture metadata.flagKey, metadata.ruleKey, metadata.ruleType, metadata.variationKey

## Test plan
* All FSC and unit tests

2020-10-16 16:20 UTC, yavorona commented
This pr depends on https://github.com/optimizely/javascript-sdk/pull/601.

2020-10-21 20:35 UTC, mjc1283 requested changes
My main suggestion is to try passing around the decision object that includes as much as possible (experiment, variation, rule key, rule type, etc.). The potential benefit is to reduce the number of additional parameters and repeated checking for null/empty string.

2020-10-21 20:35 UTC, mjc1283 commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +  setForcedVariation(experimentKey: string, userId: string, variationKey: string): boolean {
Is this an unrelated fix, or does it matter to flag decisions?

2020-10-23 20:18 UTC, yavorona commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +  setForcedVariation(experimentKey: string, userId: string, variationKey: string): boolean {
Let's keep it as it was, it should not matter to flag decisions. I updated `DecisionService.prototype.setForcedVariation` to avoid confusion.

2020-10-26 20:36 UTC, mjc1283 requested changes
This looks great! The changes in the `Optimizely` class are so much cleaner 💯 .

Requesting changes for adding a few unit tests in the `decision` module.

2020-10-26 21:03 UTC, yavorona commented on packages/optimizely-sdk/lib/core/project_config/index.js
> +  if (variationKey !== '' && experiment.variationKeyMap.hasOwnProperty(variationKey)) {
Good point. I will remove it.

2020-10-27 17:38 UTC, mjc1283 approved these changes
Please add an entry to CHANGELOG.md. Otherwise, LGTM.

2020-10-27 23:42 UTC, pawels-optimizely approved these changes
lgtm

2020-10-28 17:28 UTC, merged