feat: add decide api user context
optimizely/javascript-sdk pull request #617
Opened 2020-11-10 03:23 UTC by yavorona

## Summary
- Added user context and `createUserContext` in optimizely. 

## Test plan
Unit tests to be added

## Issues
[OASIS-6970](https://optimizely.atlassian.net/browse/OASIS-6970)

2020-12-02 19:07 UTC, yavorona commented on packages/optimizely-sdk/lib/optimizely/index.tests.js
> -            eventBuilder: eventBuilder,
Seems  unnecessary to provide `eventBuilder` to create Optimizely instance.

2020-12-02 19:10 UTC, yavorona commented on packages/optimizely-sdk/lib/optimizely_user_context/index.tests.js
> +          //TODO: figure out stubbing of eventDispatcher
Works when tested locally. Just need to figure out how to properly stub it.

2020-12-02 22:57 UTC, mjc1283 requested changes
Feel free to break this into several PRs for separate parts of the implementation.

2020-12-02 22:57 UTC, mjc1283 commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +      this.logger.log(LOG_LEVEL.DEBUG, sprintf(LOG_MESSAGES.INVALID_DECIDE_OPTIONS, MODULE_NAME));
I believe the logger has format string support built in, there's no need to call `sprintf` here. Try this:
```suggestion
      this.logger.debug(LOG_MESSAGES.INVALID_DECIDE_OPTIONS, MODULE_NAME);
```
A lot of the log statements in this model do not use this because they predate this support being added in the logger.

2020-12-02 22:57 UTC, mjc1283 commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +    options?: OptimizelyDecideOptions[]
Would it simplify the code to provide a default, then we know `options` is always an array?
```suggestion
    options: OptimizelyDecideOptions[] = [],
```

2020-12-02 22:57 UTC, mjc1283 commented on packages/optimizely-sdk/lib/optimizely_decision/index.ts
> +  private reasons: string[];
I don't think these should be private - these decisions go back to the end user, they need access to these things, right?

Making them `readonly` might be useful, also.

Since there are no non-static methods, I don't see a strong need to make this a class, rather than an interface. But I don't mind it much either.

2020-12-02 22:57 UTC, mjc1283 commented on packages/optimizely-sdk/lib/optimizely_user_context/index.tests.js
> +          //TODO: figure out stubbing of eventDispatcher
IMO, this does not need to be tested here. It's the responsibility of other modules, not `OptimizelyUserContext`. Using a fake Optimizely client will make it easier to orchestrate the tests you do need. `OptimizelyUserContext` should return whatever decision came from the inner client.

2020-12-02 22:57 UTC, mjc1283 commented on packages/optimizely-sdk/lib/optimizely_user_context/index.tests.js
> +          optimizely,
I'm confused - where is a value assigned to `optimizely`? I see it declared on 39 but not assigned. How do tests work if `optimizely` is `undefined`?

2020-12-02 22:57 UTC, mjc1283 commented on packages/optimizely-sdk/lib/optimizely_user_context/index.tests.js
> +        });
It's better to create a fake optimizely object that fulfills the same interface rather than creating a real one. OptimizelyUserContext and its unit tests should be isolated from the real Optimizely implementation.

2020-12-02 22:57 UTC, mjc1283 commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +  private defaultDecideOptions?: OptimizelyDecideOptions[];
From how this is used in `getAllDecideOptions`, it seems better to save them as an object with boolean properties, like
```ts
private defaultDecideOptions: { [key: OptimizelyDecideOptions]: boolean | undefined }
```

2020-12-02 22:57 UTC, mjc1283 commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +    const allDecideOptions = this.defaultDecideOptions ?? [];
We don't want to mutate `this.defaultDecideOptions`:
```suggestion
    const allDecideOptions = [...this.defaultDecideOptions] ?? [];
```
Also, could remove the last part if we ensure `this.defaultDecideOptions` is an array.

2020-12-02 22:57 UTC, mjc1283 commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +          if (!allDecideOptions.includes(option) && OptimizelyDecideOptions[option]) {
Even though the array length is always small, it irks me that we are searching with `includes` every time. Since we're repeatedly looking up options, we could create an object for fast lookups - perhaps another private property.

2020-12-02 22:57 UTC, mjc1283 commented on packages/optimizely-sdk/lib/shared_types.ts
> +}
Let's make sure this is usable when running the SDK from regular JS, not TS. `enum`s are not only types, they have a runtime representation too. Perhaps it's fine, but something to be aware of. I believe everything else in this module is a pure type definition that gets erased.

2020-12-03 22:00 UTC, yavorona commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +      this.logger.log(LOG_LEVEL.DEBUG, sprintf(LOG_MESSAGES.INVALID_DECIDE_OPTIONS, MODULE_NAME));
I think this would require a bit more work than just changing it as shown above. Right now we have logger as `ConsoleLogHandler`, where it would require changing it to `OptimizelyLogger` to support built-in format string. I will create a separate ticket to have it updated.

2020-12-04 22:09 UTC, yavorona commented on packages/optimizely-sdk/lib/shared_types.ts
> +}
I think moving it to `@optimizely/optimizely-sdk/lib/utils/enums` module might be a better idea!

2020-12-10 23:48 UTC, closed without merging