Uzair/sdk options refactor
optimizely/javascript-sdk pull request #621
Opened 2020-11-11 11:41 UTC by ozayr-zaviar

## Summary
- `SDKOptions` updated to `Config`

## Test plan
- All existing test cases should paas.
- All FSC test cases should pass.

2020-11-16 17:47 UTC, mjc1283 requested changes

2020-11-16 17:47 UTC, mjc1283 commented on packages/optimizely-sdk/lib/shared_types.ts
>    datafile?: string;
We must maintain the same exact `Config` interface that was previously available.
```suggestion
  datafile?: object | string;
```

2020-11-17 18:37 UTC, mjc1283 requested changes

2020-11-17 18:37 UTC, mjc1283 commented on packages/optimizely-sdk/lib/index.d.ts
> +  export type Config = import ('./shared_types').Config;
Please add this for backwards compatibility, in case a user was importing & using `SDKOptions`:

```ts
  // Keep this alias for backwards compatibility
  export type SDKOptions = Config;
```

2022-03-24 18:01 UTC, zashraf1985 commented
This is not needed any more as it will be covered by a better fix in #745

2022-03-24 18:01 UTC, zashraf1985 commented
This is not needed any more as it will be covered by a better fix in #745

2022-03-24 18:01 UTC, closed without merging