feat: Implement createUserContext for decide API
optimizely/javascript-sdk pull request #632
Opened 2020-12-04 21:33 UTC by yavorona

## Summary
- Implemented `createUserContext` in optimizely client
- Created `OptimizelyUserContext` class and implement `setAttribute` method
- Cleaned up existing unit tests
- Included `decideConfig` for future decide API testing

## Test
- Manual testing + unit tests

## Issues
- [OASIS-6942](https://optimizely.atlassian.net/browse/OASIS-6942)

2020-12-05 00:32 UTC, jaeopt requested changes
UserContext looks good. 
A couple of changes suggested.

2020-12-05 00:32 UTC, jaeopt commented on packages/optimizely-sdk/lib/optimizely_user_context/index.ts
> +    return this.attributes;
Can we return a copy of attributes? 
The attributes can be changed by setAttribute while decide using it.

2020-12-05 00:32 UTC, jaeopt commented on packages/optimizely-sdk/lib/optimizely_user_context/index.ts
> +    this.attributes = attributes ?? {};
Can we keep a copy of the given attributes here, so that any changes in the caller attributes after creating userContext are not reflected.

2020-12-05 00:32 UTC, jaeopt commented on packages/optimizely-sdk/lib/optimizely_user_context/index.tests.js
> +});
Can we have one more test validating that changing caller attributes after createUserContext is not reflected in the create userContext?

2020-12-05 00:35 UTC, mjc1283 approved these changes
LGTM!

2020-12-05 00:35 UTC, mjc1283 commented on packages/optimizely-sdk/lib/utils/enums/index.ts
> +  FLAG: 'flag',
Does this need to be added now, or a later PR?

2020-12-05 04:26 UTC, yavorona commented on packages/optimizely-sdk/lib/utils/enums/index.ts
> +  FLAG: 'flag',
In the next pr. Will remove it from here. Thanks!

2020-12-08 17:54 UTC, jaeopt approved these changes
LGTM

2020-12-08 22:53 UTC, merged