feat: implement decide API
optimizely/javascript-sdk pull request #634
Opened 2020-12-08 18:50 UTC by yavorona

## Summary

Included from previously approved pr:
- Implemented `createUserContext` in optimizely client
- Created `OptimizelyUserContext` class and implement `setAttribute` method
- Cleaned up existing unit tests
- Included `decideConfig` for future decide API testing

#### New in this pr:
 - Implemented decide API
 - Implemented partial Decide Reasons

## Test
- Manual testing + unit tests

## Issues
- [OASIS-6934](https://optimizely.atlassian.net/browse/OASIS-6934)

2020-12-08 21:29 UTC, jaeopt requested changes
Looks good. A couple of changes and more tests suggested.

2020-12-08 21:29 UTC, jaeopt commented on packages/optimizely-sdk/lib/optimizely/index.tests.js
> +
Can we add validation for decision flag notification?

2020-12-08 21:29 UTC, jaeopt commented on packages/optimizely-sdk/lib/optimizely_decision/optimizely_decision.ts
> +    variables: null,
Variable should be empty {} instead of null

2020-12-08 21:29 UTC, jaeopt commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +  decide(
Can we make sure "decide", "decideAll" and "decideForKey" API in optimizely not open to public?
They should access those APIs via OptimizelyUserContext always.

2020-12-08 22:51 UTC, mjc1283 commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +  decide(
We can exclude them from the top-level type definitions.

2020-12-08 23:27 UTC, mjc1283 requested changes

2020-12-08 23:27 UTC, mjc1283 commented on packages/optimizely-sdk/lib/optimizely/index.tests.js
> +          eventDispatcher: eventDispatcher,
Using a real event dispatcher could cause event requests to be sent during test runs - we don't want that. We should pass in a fake event dispatcher.

2020-12-08 23:27 UTC, mjc1283 commented on packages/optimizely-sdk/lib/optimizely/index.tests.js
> +            eventDispatcher: eventDispatcher,
Same comment re: real event dispatcher.

2020-12-08 23:27 UTC, mjc1283 commented on packages/optimizely-sdk/lib/optimizely/index.tests.js
> +          var expectedImpressionEvent = {
IMO, asserting the whole structure of this object is a lot. We could do it one test, and then in the others, we could just check a few properties, or check that `dispatchEvent` was called.

2020-12-08 23:27 UTC, mjc1283 commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +      }
Perhaps we could log a warning here if we encounter an invalid value - @jaeopt WDYT?

2020-12-08 23:27 UTC, mjc1283 commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +    const allDecideOptions = {...this.defaultDecideOptions};
Looks better! 👍

2020-12-08 23:27 UTC, mjc1283 commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +      featureFlag?.variables.forEach(variable => {
We already have `feature` declared on 1474. Are these the same? Can we just use that one?

2020-12-08 23:27 UTC, mjc1283 commented on packages/optimizely-sdk/lib/optimizely_decision/optimizely_decision.ts
> +  variables: { [variableKey: string]: unknown } | null;
If following @jaeopt 's suggestion that this is an empty object when there is "no decision", we can remove `| null`;

2020-12-08 23:27 UTC, mjc1283 commented on packages/optimizely-sdk/lib/shared_types.ts
> +//TODO: Move OptimizelyDecideOptions to @optimizely/optimizely-sdk/lib/utils/enums
Why move it there?

2020-12-09 00:41 UTC, yavorona commented on packages/optimizely-sdk/lib/optimizely/index.tests.js
> +          eventDispatcher: eventDispatcher,
`dispatchEvent` of eventDispatcher is being stubbed in the outer `beforeEach` function, so I think we should be fine. @mjc1283 let me know if you think otherwise

2020-12-09 00:49 UTC, yavorona commented on packages/optimizely-sdk/lib/optimizely/index.tests.js
> +            eventDispatcher: eventDispatcher,
Please see my response above

2020-12-09 01:44 UTC, yavorona commented on packages/optimizely-sdk/lib/shared_types.ts
> +//TODO: Move OptimizelyDecideOptions to @optimizely/optimizely-sdk/lib/utils/enums
Thinking it might be a good idea to expose it for clients use. LMKWYT @mjc1283

2020-12-09 17:09 UTC, mjc1283 commented on packages/optimizely-sdk/lib/shared_types.ts
> +//TODO: Move OptimizelyDecideOptions to @optimizely/optimizely-sdk/lib/utils/enums
Good point 👍

2020-12-09 17:32 UTC, mjc1283 approved these changes

2020-12-09 17:32 UTC, mjc1283 commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +import { OptimizelyDecision, newErrorDecision } from '../optimizely_decision/optimizely_decision';
Consider: since there is only one file, we could name it `optimizely_decision/index.ts`, then it can be imported like `import {...} from '../optimizely_decision';`

2020-12-09 18:25 UTC, jaeopt requested changes
Decide notification format should be changed.

2020-12-09 18:25 UTC, jaeopt commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +      decisionEventDispatched: decisionEventDispatched,
This notification data is different from the format defined in the TDD. Can you fix it?
Also can we have a test case to validate the notification contents for decide call?

2020-12-09 21:58 UTC, jaeopt requested changes
Remove "source" from notification. Other than that, all looks good.

2020-12-09 21:58 UTC, jaeopt commented on packages/optimizely-sdk/lib/optimizely/index.tests.js
>                  source: 'feature-test',
remove "source"

2020-12-09 21:58 UTC, jaeopt commented on packages/optimizely-sdk/lib/optimizely/index.tests.js
> +                source: 'feature-test',
remove "source"

2020-12-09 22:17 UTC, jaeopt approved these changes
LGTM

2020-12-09 22:28 UTC, merged