feat: Implement IGNORE_USER_PROFILE_SERVICE flag in decide options
optimizely/javascript-sdk pull request #642
Opened 2021-01-12 21:25 UTC by yavorona

## Summary
- Implemented IGNORE_USER_PROFILE_SERVICE flag in decide options

## Test plan
- Fixed affected unit tests
- Added unit test coverage with IGNORE_USER_PROFILE_SERVICE decide option
- Manual Testing
- 
## Note
This pr is to be finalized once https://github.com/optimizely/javascript-sdk/pull/640 is merged

2021-01-13 19:56 UTC, jaeopt requested changes
Looks good. See a few changes suggested.

2021-01-13 19:56 UTC, jaeopt commented on packages/optimizely-sdk/lib/optimizely/index.tests.js
> +      describe('with IGNORE_USER_PROFILE_SERVICE flag in decide options', function() {
This test looks good. Can you do the same test with "IGNORE_USER_PROFILE" in defaultDecideOptions?

2021-01-13 19:56 UTC, jaeopt commented on packages/optimizely-sdk/lib/core/decision_service/index.js
> + * @param  {OptimizelyDecideOptions[]}              options           Decide options
Fix this type. Not an array.

2021-01-13 19:56 UTC, jaeopt commented on packages/optimizely-sdk/lib/core/decision_service/index.js
> +  if (!shouldIgnoreUPS) {
This should be used to bypass "saveUserProfile" as well.
I see a test case confirming this save bypass. Wondering how the test passed :)

2021-01-13 23:01 UTC, yavorona commented on packages/optimizely-sdk/lib/core/decision_service/index.js
> +  if (!shouldIgnoreUPS) {
I believe in this case "saveUserProfile" should not be called since we are returning stored variation. I added `if (!shouldIgnoreUPS) {..}` statement to where it is being called below in case where no stored variation exists.

2021-01-14 00:48 UTC, jaeopt approved these changes
LGTM

2021-01-15 20:12 UTC, mjc1283 approved these changes

2021-01-15 20:15 UTC, merged