feat: Convert logger module to TS
optimizely/javascript-sdk pull request #658
Opened 2021-03-23 22:10 UTC by yavorona

## Summary
- Convert `index.js` and `index.react_native.js`to TS
- Remove `enums.js` since it is not consumed by any module

## Test plan
Existing unit tests

2021-04-16 16:17 UTC, zashraf1985 requested changes

2021-04-16 16:17 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/core/bucketer/index.tests.js
> +import * as logger from '../../plugins/logger';
Does importing by name work?

2021-04-16 16:17 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/logger/index.ts
> +    () => {};
can this be removed?

2021-04-23 23:08 UTC, yavorona commented on packages/optimizely-sdk/lib/core/bucketer/index.tests.js
> +import * as logger from '../../plugins/logger';
good point, imported as individual export

2021-04-23 23:11 UTC, yavorona commented on packages/optimizely-sdk/lib/plugins/logger/index.ts
> +    () => {};
`NoOpLogger`is consumed by react-native logger, not sure if it is a good idea to remove it

2021-04-23 23:13 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/logger/index.ts
> +    () => {};
Oh no. I m just talking about the empty arrow function wrapped inside the log function. Think that extra empty arrow function might be redundant

2021-04-23 23:21 UTC, yavorona commented on packages/optimizely-sdk/lib/plugins/logger/index.ts
> +    () => {};
Oh that is true, it is not needed here and is now removed

2021-04-26 13:40 UTC, zashraf1985 approved these changes
LGTM! Approved with a few optional suggestions

2021-04-26 13:40 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/logger/index.react_native.ts
> +
I dont know why github is showing `no newline at end of file` error even though it appears that there is a new line there. Can you check.

2021-04-26 13:40 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/logger/index.ts
> + * Copyright 2021, Optimizely
Shouldn't this include previous years too. Technically, this is a new file but logically this is a rename. Just a suggestion, feel free to do whatever makes sense to you here

2021-04-26 17:13 UTC, merged