feat: Convert decision service to TS
optimizely/javascript-sdk pull request #659
Opened 2021-03-24 23:40 UTC by yavorona

## Summary
- Convert `decision_service` module to TS

## Test plan
Existing unit tests + local bundle

2021-04-16 00:33 UTC, zashraf1985 requested changes

2021-04-16 00:33 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/core/project_config/index.ts
> + * Copyright 2016-2020, Optimizely
NIT: update 2021

2021-05-14 00:21 UTC, yavorona commented on packages/optimizely-sdk/lib/core/decision_service/index.ts
> +  private getUserProfile(userId: string): UserProfile | undefined {
`?` cannot be used in the return type, so I updated it to return `UserProfile | null`, LMKWYT.

2021-05-14 00:28 UTC, yavorona commented on packages/optimizely-sdk/lib/core/decision_service/index.ts
> +    if (rolloutDecision.variation !== null) {
I think you meant `rolloutDecision.variation`, it is now updated.

2021-05-14 15:58 UTC, yavorona commented on packages/optimizely-sdk/lib/core/audience_evaluator/index.js
> +};
This is needed here in particular to avoid having to convert the entire `audience_evaluator` module.
We have also been doing this to avoid stubbing issues when converting to TS. (example: `notification_center`, `event_processor`, `optimizely_config`)

2021-05-14 16:18 UTC, yavorona commented on packages/optimizely-sdk/lib/core/decision_service/index.ts
> +  UNSTABLE_conditionEvaluators: unknown;
This was here before my time. :)

2021-05-17 15:59 UTC, zashraf1985 approved these changes
LGTM!

2021-05-17 15:59 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/core/decision_service/index.ts
> +   * @return {UserProfile|undefined} the stored user profile or undefined if one isn't found
NIT: Need to update the type from `undefined` to `null` here

2021-05-20 18:43 UTC, merged