Pnguen/convert event builder to ts
optimizely/javascript-sdk pull request #680
Opened 2021-06-08 00:31 UTC by yavorona

## Summary
- Convert `event_builder` module to TS

## Test plan
Existing unit tests

2021-06-10 16:50 UTC, keppel2 commented on packages/optimizely-sdk/lib/core/event_builder/event_helpers.ts
> +    id: string | null;
Could this be `id:? string;` ?

2021-06-11 22:01 UTC, zashraf1985 requested changes

2021-06-11 22:01 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/core/event_builder/index.ts
> +  variationKey = variationKey ? variationKey: '';
```suggestion
  variationKey = variationKey || '';
```

2021-06-11 22:03 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/core/event_builder/event_helpers.ts
> +    id: string | null;
@keppel2 you are right by intuition but JS and and TS are weird languages. `id?` is equivalent to `string | undefined` but not equivalent to `string | null`.

2021-06-11 22:48 UTC, yavorona commented on packages/optimizely-sdk/lib/core/event_builder/event_helpers.ts
> +  tags: EventTags | undefined;
Not sure about this change. I think declaring this property as optional may not be the right way since we always pass tags to `buildConversionEvent` method. Its value can be of type `EventTags` or `undefined` because we filter out its null values before passing it to buildConversionEvent or it may simply be undefined because user did not specify it in `track` call. @zashraf1985 Please LMKWYT

2021-06-16 17:52 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/core/event_builder/event_helpers.ts
> +  tags: EventTags | undefined;
I think it makes sense. Ignore my comment on this

2021-06-16 17:58 UTC, zashraf1985 approved these changes
LGTM!

2021-06-16 17:58 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/core/event_builder/event_helpers.ts
> +
Super NIT: Extra line break

2021-06-16 22:32 UTC, merged