feat: Convert  project config manager module to TS
optimizely/javascript-sdk pull request #684
Opened 2021-06-22 22:05 UTC by yavorona

## Summary
- Convert `project_config_manager.js` to TS
- Additional Changes:
    - Originally project_config_manager module used `HttpPollingDatafileManager` imported from `@optimizely/js-sdk-datafile-manager` package to create a new instance of datafileManager during instantiation of ProjectConfigManager class. HttpPollingDatafileManager is an abstract class, and TS does not allow to create an instance of an abstract class. To solve this issue, a new `DefaultHttpPollingDatafileManager` class was derived from HttpPollingDatafileManager and was used in lieu of HttpPollingDatafileManager.

## Test plan
Existing unit tests

2021-07-26 19:20 UTC, zashraf1985 requested changes

2021-07-26 19:20 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/core/project_config/project_config_manager.ts
> +    if (this.datafileManager) {
Why did you add this extra check in the typescript version. datafile manager is not expected to be null here because promise can only be fulfilled after its initialization

2021-07-26 19:20 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/core/project_config/project_config_manager.ts
> +  private readyPromise: Promise<{ success: boolean; reason?: string }>;
Suggestion (Non binding): I see you using `{ success: boolean; reason?: string }` type at many places in the file. What do you think about declaring a type at the top and reusing it for simplicity. Totally up to your preference.

2021-07-26 19:20 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/core/project_config/project_config_manager.ts
> +    if (this.datafileManager) {
Again, why do you need a check here?

2021-07-26 19:20 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/core/project_config/project_config_manager.ts
> +        });
```suggestion
        this.updateListeners.forEach((listener) => listener(configObj));
```

2021-07-26 19:20 UTC, zashraf1985 commented on packages/optimizely-sdk/typings/@optimizely/js-sdk-datafile-manager.d.ts
> +}
The indentation looks off. it should be 2 spaces per tab.

2021-07-26 21:39 UTC, yavorona commented on packages/optimizely-sdk/lib/core/project_config/project_config_manager.ts
> +    try {
It was in the original implementation here: 
https://github.com/optimizely/javascript-sdk/pull/684/files#diff-8c34af3f23d5d0c9fa26e08c7ea42c8d71342761c3ac3d7669fff4e3c6127027L55

2021-07-26 21:48 UTC, yavorona commented on packages/optimizely-sdk/lib/core/project_config/project_config_manager.ts
> +    if (this.datafileManager) {
True but TS compiler is not smart enough to know it. It requires this check prior to calling `this.datafileManager.get()` since the initial value of it is null.

2021-07-26 21:49 UTC, yavorona commented on packages/optimizely-sdk/lib/core/project_config/project_config_manager.ts
> +    if (this.datafileManager) {
Same as above.

2021-07-27 16:30 UTC, zashraf1985 approved these changes
Great Work! LGTM!

2021-07-27 20:22 UTC, merged