feat: Use enum to define type in getTypeCastValue
optimizely/javascript-sdk pull request #695
Opened 2021-07-26 16:39 UTC by yavorona

## Summary
Use enum to define type in getTypeCastValue in project_config

## Issues
[OASIS-7189](https://optimizely.atlassian.net/browse/OASIS-7189)

2021-07-26 16:56 UTC, keppel2 commented on packages/optimizely-sdk/lib/core/project_config/index.ts
> +
Is this necessary?

2021-07-26 18:44 UTC, zashraf1985 requested changes

2021-07-26 18:44 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/core/project_config/index.ts
> -          variable.type = FEATURE_VARIABLE_TYPES.JSON;
why is this explicit cast needed for the `json` value but it works otherwise for other values without casting?

2021-07-26 21:16 UTC, yavorona commented on packages/optimizely-sdk/lib/core/project_config/index.ts
> -          variable.type = FEATURE_VARIABLE_TYPES.JSON;
I believe there is no otherwise cases of setting a value of `variable.type` besides this one. The FEATURE_VARIABLE_TYPES.JSON is type `string` and `variable.type` is expected to be `VariableType` so we needed to case it here

2021-07-27 16:31 UTC, zashraf1985 approved these changes
Looks Good!

2021-07-27 20:23 UTC, merged