feat(OptimizelyConfig): Add new fields to OptimizelyConfig
optimizely/javascript-sdk pull request #698
Opened 2021-08-11 06:12 UTC by yasirfolio3

## Summary
The following new public properties are added to OptimizelyConfig:
- sdkKey
- environmentKey
- attributes
- audiences
- events
- experimentRules and deliveryRules to OptimizelyFeature
- audiences to OptimizelyExperiment

## Test plan
All FSC tests OPTIMIZELY_CONFIG_V2 tests should pass.

2021-08-11 06:32 UTC, keppel2 commented on packages/optimizely-sdk/lib/core/optimizely_config/index.ts
> +    this.sdkKey = configObj.sdkKey ? configObj.sdkKey : '';
You can use `configObj.sdkKey ?? '';` if you want.

2021-08-11 06:49 UTC, keppel2 commented on packages/optimizely-sdk/lib/core/optimizely_config/index.ts
> +        // Checks if item is list of conditions means if it is sub audience
`// Checks if item is list of conditions means it is sub audience`

2021-08-11 14:45 UTC, zashraf1985 requested changes

2021-08-11 14:45 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/core/optimizely_config/index.ts
> -  Rollout,
NIT: arrange these in alphabetical order

2021-08-11 14:45 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/core/optimizely_config/index.ts
> +  private static audienceConditionalOperators: string[] = ['and', 'or', 'not'];
This can probably moved to ENUMS?

2021-08-11 14:45 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/core/optimizely_config/index.ts
> +    this.sdkKey = configObj.sdkKey ? configObj.sdkKey : '';
```suggestion
    this.sdkKey = configObj.sdkKey || '';
```

2021-08-11 14:45 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/core/optimizely_config/index.ts
> +    const finalAudiences: OptimizelyAudience[] = [];
why call it `finalAudiences`? can you simply call it `audiences`

2021-08-11 14:45 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/core/optimizely_config/index.ts
> +    const typedAudienceIds: { [id: string]: boolean } = {};
instead of a key, val pair, you could keep it an array of string ids and could use `typedAudienceIds.include(id)` to check if an id exists.

2021-08-11 14:45 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/core/optimizely_config/index.ts
> +      if (!typedAudienceIds[oldAudience.id] && oldAudience.id != '$opt_dummy_audience') {
`oldAudience` can be simple named `audience` here.

2021-08-11 14:45 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/core/optimizely_config/index.ts
> +      if (!typedAudienceIds[oldAudience.id] && oldAudience.id != '$opt_dummy_audience') {
if you use array instead of object, you can simple do `!typedAudienceIds.includes(audience.id)` here.

2021-08-11 14:45 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/core/optimizely_config/index.ts
> +    return serializedAudience;
NOT reviewing this code. will leave it to @msohailhussain and @jaeopt as they have more context about this particular peice

2021-08-11 23:37 UTC, yavorona requested changes

2021-08-11 23:37 UTC, yavorona commented on packages/optimizely-sdk/lib/shared_types.ts
> +  audiences: unknown[] | string;
Should just be `string`

2021-08-11 23:37 UTC, yavorona commented on packages/optimizely-sdk/lib/core/optimizely_config/index.ts
> +    experiments: Experiment[] | undefined
This should not be expected undefined as every rollout object should contain `experiments`. @msohailhussain please correct if I am wrong.

2021-08-11 23:37 UTC, yavorona commented on packages/optimizely-sdk/lib/core/optimizely_config/index.ts
> +    if (!experiments) {
If above is true, this if statement is unnecessary.

2021-08-11 23:37 UTC, yavorona commented on packages/optimizely-sdk/lib/core/optimizely_config/index.ts
> +    if (!featureId) {
This statement seems unnecessary as we should expect a valid `featureId`, right?

2021-08-12 05:12 UTC, msohailhussain requested changes
please address

2021-08-12 21:59 UTC, yavorona reviewed
Looks good except for couple of minor comments and failing browser stack tests.

2021-08-12 21:59 UTC, yavorona commented on packages/optimizely-sdk/lib/core/optimizely_config/index.ts
> +    variationsMap = variations.reduce((OptlyVariationsMap: { [key: string]: OptimizelyVariation }, variation) => {
`optlyVariationsMap` instead of `OptlyVariationsMap`

2021-08-12 21:59 UTC, yavorona commented on packages/optimizely-sdk/lib/core/optimizely_config/index.ts
> +      (OptlyVariablesMap: OptimizelyVariablesMap, featureVariable) => {
`optlyVariablesMap` instead of `OptlyVariablesMap`

2021-08-12 22:26 UTC, zashraf1985 approved these changes

2021-08-13 16:18 UTC, jaeopt requested changes
Overall looks great! 
- One comment about using OptimizelyConfig types internally. 
- Also I do not see duplicate-key warning about experimentsMap in OptimizelyConfig and deprecation warning about experimentsMap in OptimizelyFeature.

2021-08-13 16:18 UTC, jaeopt commented on packages/optimizely-sdk/lib/core/project_config/index.ts
> +  attributes: OptimizelyAttribute[];
I think it's not a good idea to use "OptimizelyAttribute" or other "OptimizelyXYZ" types in here. 
Even if they look identical for now, we should separate them as public types only.

2021-08-13 18:32 UTC, yasirfolio3 commented on packages/optimizely-sdk/lib/core/project_config/index.ts
> +  attributes: OptimizelyAttribute[];
makes sense.

2021-08-13 18:48 UTC, yasirfolio3 commented on packages/optimizely-sdk/lib/core/project_config/index.ts
> +  attributes: OptimizelyAttribute[];
makes sense, thanks.

2021-08-13 18:50 UTC, yasirfolio3 commented
> Overall looks great!
> 
> * One comment about using OptimizelyConfig types internally.
> * Also I do not see duplicate-key warning about experimentsMap in OptimizelyConfig and deprecation warning about experimentsMap in OptimizelyFeature.

Had already added for `OptimizelyFeature` here: https://github.com/optimizely/javascript-sdk/pull/698/files#diff-2f8a7f1ccf360ce99abd03c811c59f9488fa24db24f8578d808e813e75192acdR330 

Also added for OptimizelyConfig Interface here but forgot about the class which i have added now. Comment on the interface can be seen here: https://github.com/optimizely/javascript-sdk/pull/698/files#diff-2f8a7f1ccf360ce99abd03c811c59f9488fa24db24f8578d808e813e75192acdR347

2021-08-13 19:14 UTC, yavorona approved these changes

2021-08-13 19:33 UTC, msohailhussain approved these changes

2021-08-13 20:15 UTC, jaeopt approved these changes
LGTM
nit - add a period (.) at the end of "This experimentsMap is for experiments of legacy projects only" in multiple places.

2021-08-13 22:47 UTC, merged