build(json-schema): update version to remove high-severity [https://s…
optimizely/javascript-sdk pull request #721
Opened 2021-11-16 09:50 UTC by makiri1993

…nyk.io/vuln/SNYK-JS-JSONSCHEMA-1920922]

## Summary
Updated the version of the lib json-schema

There is a vulnerability which was fixed in version 0.4.0 

Prototype Pollution  https://snyk.io/vuln/SNYK-JS-JSONSCHEMA-1920922

2021-11-24 22:02 UTC, zashraf1985 requested changes
Looks Good! I ran the checks and they pass. If you can address the following, we are good to go.
1. Added a comment about the registry where its picking the dependency from.
2. Can you submit the 'Contributor License Agreement' here
https://docs.google.com/forms/d/e/1FAIpQLSf9cbouWptIpMgukAKZZOIAhafvjFCV8hS00XJLWQnWDFtwtA/viewform

Thanks for contributing.

2021-11-24 22:02 UTC, zashraf1985 commented on packages/optimizely-sdk/package-lock.json
> +      "resolved": "https://nexus.es.ecg.tools/repository/npm-all/json-schema/-/json-schema-0.4.0.tgz",
Just curios why is it fetching the dependency from here instead of `registry.npmjs.org`

2021-11-25 12:39 UTC, makiri1993 commented on packages/optimizely-sdk/package-lock.json
> +      "resolved": "https://nexus.es.ecg.tools/repository/npm-all/json-schema/-/json-schema-0.4.0.tgz",
Done

2021-11-25 12:40 UTC, makiri1993 commented
Agreement is submitted and I updated the package-lock :)

Do you have an eta when a new version with this fix will be released?

2021-11-25 18:42 UTC, zashraf1985 commented
> Agreement is submitted and I updated the package-lock :)
> 
> Do you have an eta when a new version with this fix will be released?

Thanks for doing this! I am  targeting Monday, but expect to be by mid of next week at the worst.

2021-11-28 17:04 UTC, zashraf1985 approved these changes

2021-11-28 17:04 UTC, merged