fix: Checking variation in flagvariation map instead of checking it only in experiment
optimizely/javascript-sdk pull request #729
Opened 2021-12-14 17:32 UTC by mnoman09

## Summary
- Checking variation in flagvariation map for forced decision

## Test plan

## Issues
- "THING-1234" or "Fixes #123"

2021-12-14 21:37 UTC, jaeopt requested changes
Change looks good. We need a unit test covering the case.

2021-12-14 22:40 UTC, msohailhussain approved these changes
lgtm. please address jae's comments.

2021-12-15 00:21 UTC, zashraf1985 requested changes
There is a weird pattern of passing in config from outside was introduced here which will make this `findValidatedForcedDecision` API unusable from outside. Please see if you can find a better way to do it or let me know, we can try to figure something out together

2021-12-15 00:21 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/optimizely_user_context/index.ts
> +      variation = getFlagVariationByKey(config, flagKey, variationKey);
Why did this had to change? this looks like a weird pattern to pass in config from outside.

2021-12-15 00:21 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/optimizely_user_context/index.ts
> +    config: ProjectConfig,
This is a very weird pattern. why do we need to pass in config from outside when we have access to optimizely instance.

2021-12-15 00:21 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/optimizely/index.ts
> -  }
why remove this and move to `project_config` and pass that in separately?

2021-12-15 00:21 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/core/decision_service/index.ts
> +            }
As far as i understand, this was the only change needed here. i am unable to understand why were other changes made at all.

2021-12-15 05:54 UTC, msohailhussain commented on packages/optimizely-sdk/lib/optimizely/index.ts
> -  }
As per my understanding, `project_config` is used for mapping all datafile properties and their k/v mappings. Optimizely class is not for this purpose. I have not seen any single mapping in this class. That's why removed it and add it at proper location where you can see all other getter and setters.

2021-12-15 05:55 UTC, msohailhussain commented on packages/optimizely-sdk/lib/optimizely_user_context/index.ts
> +    config: ProjectConfig,
optimizelyInstance.config may have different version if we try to access it from the optimizely instance. That's why the config we capture in the start of any API, we use it across all methods.

2021-12-15 06:11 UTC, msohailhussain commented on packages/optimizely-sdk/lib/core/decision_service/index.ts
> +            }
Secondly, `optimizely_instance`'s access is not available in decide_service, that's why moved to `project_config`

2021-12-15 06:43 UTC, zashraf1985 approved these changes
Based on @msohailhussain 's explanation and based on the fact that we have done the same in other SDKs, i am approving this. But i have serious concerns in general on the cyclic dependencies we are creating in the SDKs. This is definitely going to come back and bite us later. We need to think about redesigning without these cyclic dependencies later.
@jaeopt @dustin-sier @The-inside-man

2021-12-16 00:04 UTC, jaeopt requested changes
Question about a test case. Can you check?

2021-12-16 00:04 UTC, jaeopt commented on packages/optimizely-sdk/lib/optimizely_user_context/index.tests.js
> +        assert.deepEqual(decision, fakeDecision);
It looks like checking fakeDecision vs fakeDecision, which is always true. Can you confirm?

2021-12-17 14:06 UTC, mnoman09 commented on packages/optimizely-sdk/lib/optimizely_user_context/index.tests.js
> +        assert.deepEqual(decision, fakeDecision);
you are right. It's my mistake I copied the test from above decide tests and in all those tests same thing is happening. I don't know why.

2021-12-20 18:54 UTC, jaeopt approved these changes
LGTM

2021-12-21 06:29 UTC, merged