chore: prepare for release 4.9.0
optimizely/javascript-sdk pull request #731
Opened 2022-01-06 07:30 UTC by yasirfolio3

## Summary
- Prepare for release 4.9.0

2022-01-06 17:38 UTC, jaeopt requested changes
Error in CHANGELOG

2022-01-06 17:38 UTC, jaeopt commented on packages/optimizely-sdk/CHANGELOG.MD
> +* Add a set of new APIs for overriding and managing user-level flag, experiment and delivery rule decisions. These methods can be used for QA and automated testing purposes. They are an extension of
Add [#705] the first PR to the list. Also, fix format - the opening parenthesis is missing.

2022-01-07 10:35 UTC, yasirfolio3 commented on packages/optimizely-sdk/CHANGELOG.MD
> +* Add a set of new APIs for overriding and managing user-level flag, experiment and delivery rule decisions. These methods can be used for QA and automated testing purposes. They are an extension of
Hey, since `705` was part of the `4.8.0` release, i removed it from this PR. Have now removed the commit containing that change, thanks for confirming 👍

2022-01-07 17:35 UTC, jaeopt approved these changes
LGTM

2022-01-12 21:39 UTC, jaeopt approved these changes
LGTM

2022-01-13 16:59 UTC, jaeopt approved these changes
LGTM

2022-01-14 19:56 UTC, jaeopt approved these changes
LGTM

2022-01-15 00:53 UTC, merged