refact: Integrate utils package
optimizely/javascript-sdk pull request #749
Opened 2022-03-28 05:50 UTC by ozayr-zaviar

## Summary
- Integrate utils package in optimizely-sdk package.

## Test plan
- All unit tests and FSC should pass.

2022-03-28 17:25 UTC, zashraf1985 requested changes
Looks great Overall! I have a couple of requests other than the explicit comments.
1. Can you update the copyright header wherever applicable.
2. Please add description to the PR.

2022-03-28 17:25 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/utils/fns/index.ts
>  export default {
Can you add the new additions to `default` exports as well.

2022-04-12 23:20 UTC, zashraf1985 requested changes
This is getting really close. A couple of more changes to go.
1. Move NotificationCenter interface and types from utils to `NotificationCenter` module.
2. Copyright should be updated to reflect only the years in which the file was changed. For example a file containing `2016, 2018` will be changed to `2016, 2018, 2022`. A file containing `2016, 2018-2021` will be changed to `2016, 2018-2022`. Use commas to separate the years where there is a break in between. Use dashes where there is continuity.

2022-04-12 23:20 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/utils/fns/index.ts
> +export enum NOTIFICATION_TYPES {
NOTIFICATION_TYPES and NotificationCenter interface can be moved to `NotificationCenter` module?

2022-04-13 19:42 UTC, zashraf1985 requested changes

2022-04-13 19:42 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/core/notification_center/index.ts
> +export enum NOTIFICATION_TYPES {
move this to `utils/enums.ts`

2022-04-13 19:42 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/core/notification_center/index.ts
> +export interface NotificationCenter {
remove this as this interface is already available in shared_types

2022-04-14 22:32 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/core/notification_center/index.ts
> +export interface NotificationCenter {
There has to be a name conflict because this file now exports a class and an interface both with the same name. can you fix this

2022-04-19 01:04 UTC, zashraf1985 approved these changes
LGTM!

2022-04-20 21:02 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/core/audience_evaluator/index.tests.js
> + * Copyright 2016, 2018-2022, Optimizely
2016, 2018-2020, 2022,

2022-04-20 21:02 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.tests.js
> + * Copyright 2018-2021, Optimizely, Inc. and contributors                   *
2018-2020, 2022,

2022-04-20 21:05 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/core/notification_center/index.ts
> +  NOTIFICATION_TYPES
Best practice should include trailing comma I believe (reduces changes reflected in git diff for future commits) but that's a nit-pick.

2022-04-20 21:06 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/core/project_config/index.ts
>  import fns from '../../utils/fns';
Can consolidate this line into above import as well.

2022-04-20 21:07 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/core/project_config/project_config_manager.tests.js
> + * Copyright 2019-2022 Optimizely
2019-2020, 2022

2022-04-20 21:08 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/core/project_config/project_config_manager.tests.js
> +import { sprintf } from '../../utils/fns';
We should consider adding listing for consistent import ordering if we don't have that yet.

2022-04-20 21:09 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/plugins/event_processor/forwarding_event_processor.ts
> + * Copyright 2021, 2022, Optimizely
2021-2022,

2022-04-20 21:09 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/plugins/event_processor/forwarding_event_processor.ts
> +  private notificationCenter?: NotificationSender;
Is `notificationCenter` variable name still most sensible, or should that be changed to `notificationSender`?

2022-04-20 21:10 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/utils/attributes_validator/index.tests.js
> + * Copyright 2016, 2018-2022, Optimizely
2016, 2018-2020, 2022,

2022-04-20 21:11 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/utils/attributes_validator/index.ts
> + * Copyright 2016, 2018-2022, Optimizely
2016, 2018-2020, 2022,

2022-04-20 21:11 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/utils/config_validator/index.tests.js
> + * Copyright 2016, 2018-2022, Optimizely
2016, 2018-2020, 2022,

2022-04-20 21:11 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/utils/config_validator/index.ts
> + * Copyright 2016, 2018-2022, Optimizely
2016, 2018-2020, 2022,

2022-04-20 21:12 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/utils/fns/index.ts
> + * Copyright 2017, 2019-2022, Optimizely
2017, 2019-2020, 2022,

2022-04-20 21:14 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/event_processor/forwarding_event_processor.ts
> +  private notificationCenter?: NotificationSender;
I agree! It makes sense to change the variable name too

2022-04-20 21:15 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/utils/fns/index.ts
> +import v4 from 'uuid';
We may want to consider documenting this `uuid` library addition in the PR summary as well and/or official documentation since it's a new dependency.

2022-04-20 21:17 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/utils/json_schema_validator/index.tests.js
> + * Copyright 2016-2022, Optimizely
2016-2020, 2022,

2022-04-20 21:20 UTC, opti-jnguyen commented
@ozayr-zaviar - nice job, besides some of the small nitpicks I noted above, I think this is great.

2022-04-21 16:14 UTC, ozayr-zaviar commented on packages/optimizely-sdk/lib/core/project_config/index.ts
>  import fns from '../../utils/fns';
getting error `Module '"../../utils/fns"' has no exported member 'fns'. Did you mean to use 'import fns from "../../utils/fns"' instead` if consolidating with the above line.

2022-04-26 19:05 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/utils/fns/index.ts
> +import v4 from 'uuid';
We are not adding a new library. It was already part of the overall package. The only difference is, earlier it was being included as a transitive dependency through `utils` npm package. We have already documented this and other libraries used by all the packages in the README.

2022-04-26 19:07 UTC, zashraf1985 requested changes

2022-04-26 19:07 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/event_processor/forwarding_event_processor.ts
> +  private notificationCenter?: NotificationSender;
@ozayr-zaviar Can you make this change. Can you change the variable name from `notificationCenter` to `notificationSender` too?

2022-04-28 17:15 UTC, zashraf1985 commented
@ozayr-zaviar Can you update this branch with master. Looks like there are some conflicts after you merged your GIT actions PR

2022-05-04 23:42 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/core/audience_evaluator/index.tests.js
> +import { sprintf } from '../../utils/fns';
Any thoughts on using path aliases in the optimizely-sdk/tsconfig.json file to make these imports a bit easier to read?

Example tsconfig.js:

```
"paths": {
  "*": [ "./typings/*" ],
  "@utils": [ "./lib/utils/*" ],
},
```

Usage:

```
import { sprint } from '@utils/fns'
```

2022-05-04 23:46 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/plugins/event_processor/forwarding_event_processor.ts
> +import { NotificationSender } from '../../core/notification_center';
Same comment as above, we should consider configuring tsconfig.json to add a path alias for the utils directory.

2022-05-04 23:47 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/plugins/event_processor/forwarding_event_processor.ts
> +  constructor(dispatcher: EventDispatcher, notificationCenter?: NotificationSender) {
notifcationCenter should be refactored to notificationSender, no?

2022-05-04 23:48 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/plugins/event_processor/forwarding_event_processor.ts
> +export function createForwardingEventProcessor(dispatcher: EventDispatcher, notificationCenter?: NotificationSender): EventProcessor {
Consider `notificationCenter` => `notificationSender`

2022-05-04 23:51 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/utils/fns/index.ts
> +export function isValidEnum(enumToCheck: { [key: string]: any }, value: number | string): boolean {
Is the lint warning here being ignored purposefully?

2022-05-04 23:57 UTC, opti-jnguyen requested changes
Items to be reviewed:

1. Path alias implementation for `utils` (import "@utils").
2. Should `notificationCenter` be refactored to `notificationSender`?
3. utils/fns/index.ts > Is line 82's linting warning being ignored on purpose?

Items for later:
- Consider import order linting.

2022-05-06 05:36 UTC, ozayr-zaviar commented on packages/optimizely-sdk/lib/utils/fns/index.ts
> +export function isValidEnum(enumToCheck: { [key: string]: any }, value: number | string): boolean {
For now, the warning has been suppressed but the `any` type will be removed in another refactor activity described in the`TODO`.

2022-05-13 21:28 UTC, zashraf1985 requested changes
@ozayr-zaviar can you update the @utils path alias every where.. i see many files are still using `../../utls`

2022-05-16 04:39 UTC, zashraf1985 requested changes

2022-05-16 04:39 UTC, zashraf1985 commented on packages/optimizely-sdk/jest.config.js
> +  // "roots": [
Remove commented code

2022-05-16 04:39 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/utils/fns/index.ts
> +/*
Move these comments to notificationcenter where you moved the code that was below these comments originally.

2022-05-16 16:41 UTC, opti-jnguyen approved these changes
LGTM

2022-05-23 13:18 UTC, opti-jnguyen commented
Saw latest two commits - LGTM!

2022-05-23 22:56 UTC, merged