chore: removed travis yml and added git action support
optimizely/javascript-sdk pull request #753
Opened 2022-04-14 13:41 UTC by ozayr-zaviar

## Summary
- We remove travis yaml from javascript-sdk and moved all the stages to git action.

NOTE:
Please update [this](https://github.com/optimizely/ruby-sdk/blob/21005c3085d670e6b3b9c2993ac194163c146c0d/.github/workflows/ruby.yml#L11), [this](https://github.com/optimizely/ruby-sdk/blob/21005c3085d670e6b3b9c2993ac194163c146c0d/.github/workflows/ruby.yml#L14) and [this](https://github.com/optimizely/ruby-sdk/blob/21005c3085d670e6b3b9c2993ac194163c146c0d/.github/workflows/ruby.yml#L20) line branch name to master before merging.

## Test plan
All tests should pass

2022-04-18 21:31 UTC, msohailhussain requested changes
please address comments and also revert links to master.

2022-04-18 21:31 UTC, msohailhussain commented on .github/workflows/javascript.yml
> +    - uses: actions/checkout@v2
v3

2022-04-18 21:31 UTC, msohailhussain commented on .github/workflows/javascript.yml
> +      BROWSER_STACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
rename it to BROWSERSTACK_USERNAME

2022-04-18 21:31 UTC, msohailhussain commented on .github/workflows/javascript.yml
> +      BROWSER_STACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
same here.

2022-04-18 21:31 UTC, msohailhussain commented on .github/workflows/javascript.yml
> +    - uses: actions/checkout@v2
update across all checkouts to v3.

2022-04-18 21:31 UTC, msohailhussain commented on .github/workflows/javascript.yml
> +    - uses: actions/checkout@v2
update

2022-04-18 21:31 UTC, msohailhussain commented on .github/workflows/javascript.yml
> +        parallel: true
what does it mean parallel build?

2022-04-18 21:31 UTC, msohailhussain commented on packages/optimizely-sdk/package.json
> +    "coveralls": "nyc --reporter=lcov npm test",
why is this removed?

2022-04-20 15:01 UTC, ozayr-zaviar commented on .github/workflows/javascript.yml
> +        parallel: true
we are running unit test on multiple node versions and multiple posts on coveralls are required, thats why we are sending those posts in parallel.

2022-04-20 15:04 UTC, ozayr-zaviar commented on packages/optimizely-sdk/package.json
> +    "coveralls": "nyc --reporter=lcov npm test",
The previous `precoveralls` and `cover` is required to post coveralls from travis but it is not working on git actions so we post using 3rd party git action `coverallsapp/github-action@master` and is no longer require here.

2022-04-22 06:20 UTC, msohailhussain approved these changes
lgtm

2022-04-22 16:16 UTC, jaeopt approved these changes
LGTM

2022-04-26 19:59 UTC, msohailhussain commented on .github/workflows/integration_test.yml
> +        echo "TRAVIS_BRANCH=${{ github.head_ref }}" >> $GITHUB_ENV
remove it from all places.

2022-04-26 23:10 UTC, merged