refact: Integrate logging package
optimizely/javascript-sdk pull request #755
Opened 2022-04-26 15:12 UTC by ozayr-zaviar

## Summary
- Integrate logging package in optimizely-sdk package.

## Test plan
- All unit tests and FSC should pass.

2022-06-08 16:09 UTC, zashraf1985 requested changes
Looks Great! Added a question. Also please double check all the copyright header changes too.

2022-06-10 00:13 UTC, ozayr-zaviar commented on packages/optimizely-sdk/lib/index.browser.ts
> +import logHelper from './modules/logging/logger';
Karma browser test was not able to locate the package unless it is defined in the default.

2022-06-10 19:15 UTC, zashraf1985 approved these changes
LGTM! @opti-jnguyen @mikechu-optimizely it will be helpful if you guys can also take a look and provide feedback on this.

2022-06-15 15:57 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/index.browser.ts
> +import logHelper from './modules/logging/logger';
This comment applies to most of the files below that import the logging module as both `logging` and `logging/logger`.

Let me know if I'm misunderstanding something.

2022-06-15 16:10 UTC, opti-jnguyen commented
Added a couple comments @ozayr-zaviar - let me know what you think.

cc: @zashraf1985

2022-06-16 17:36 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/index.browser.ts
> +import logHelper from './modules/logging/logger';
I asked the same question and looks like he is having some trouble using these in tests when he directly imports these. Lets me try debugging it with uzair together and see if we can simplify this.

2022-06-23 13:49 UTC, opti-jnguyen approved these changes
Minus the small non-blocking notes from my comments, LGETM!

2022-08-02 01:21 UTC, merged