feat: Add ODP Segments support in Audience Evaluation
optimizely/javascript-sdk pull request #765
Opened 2022-06-02 23:22 UTC by zashraf1985

## Summary
Added ODP Segments support in Audience evaluation

## Test plan
- Added New unit tests
- Existing Tests should pass

2022-06-07 23:36 UTC, jaeopt requested changes
Qualified-type support looks good! I'd like to see UserContext passed down to audience evaluators. See my comments and let's chat about it.

2022-06-07 23:36 UTC, jaeopt commented on packages/optimizely-sdk/lib/core/audience_evaluator/index.ts
> +    segments: string[] = [],
add 'segments' in doc comments

2022-06-07 23:36 UTC, jaeopt commented on packages/optimizely-sdk/lib/core/audience_evaluator/index.ts
> +  evaluateConditionWithUserAttributes(userAttributes: UserAttributes, segments: string[], condition: Condition): boolean | null {
update doc comments

2022-06-22 22:41 UTC, jaeopt requested changes
Looks good! A couple of small changes suggested.

2022-06-22 22:41 UTC, jaeopt commented on packages/optimizely-sdk/lib/optimizely_user_context/index.ts
> +  private qualifiedSegments: string[] = [];
Can we open {get, set} for this prop to public?  They can override it with own segments for debugging or other purposes?

2022-06-22 22:41 UTC, jaeopt commented on packages/optimizely-sdk/lib/core/audience_evaluator/odp_segment_condition_evaluator/index.ts
> +  //return user.getQualifiedSegments().indexOf(condition.value as string) > -1;
remove this comment

2022-06-22 22:41 UTC, jaeopt commented on packages/optimizely-sdk/lib/core/audience_evaluator/index.tests.js
> +        it('shoud evaluate to true if segment is found', () => {
```suggestion
        it('should evaluate to true if segment is found', () => {
```
fix same for others below

2022-07-14 18:18 UTC, jaeopt approved these changes
LGTM

2022-08-11 14:19 UTC, opti-jnguyen commented
@zashraf1985 - I believe I fixed the import issues, however although the Git Actions shows all tests passing there seems to be 2 failing / 2 pending checks still. What am I missing?

2022-08-14 15:13 UTC, merged