hellofresh: use map instead of object
optimizely/javascript-sdk pull request #766
Opened 2022-06-15 18:10 UTC by PepijnSenders

## Summary

This PR refactors the datafile maps to use Map() instead of object. The datafile at HelloFresh is quite sizeable and doing all these object lookups and remappings are bad for performance. Map is up to 5 times faster in big objects!

2022-06-16 18:25 UTC, zashraf1985 commented
Thanks for the contribution @PepijnSenders !! There are many unit tests failing. While we review, if you have time can you take a look at why unit tests are failing.

2022-06-16 20:15 UTC, PepijnSenders commented
@zashraf1985 yea I figured, if you think it's a good change I can go ahead and fix those tests.

2022-06-17 01:02 UTC, zashraf1985 commented
> @zashraf1985 yea I figured, if you think it's a good change I can go ahead and fix those tests.

It is a good change for sure. We developed Javascript SDK a few years ago in plain common JS. We gradually added bundling and typescript and are still in the process of gradually upgrading and optimizing. This is an ongoing process and there is a lot of room for optimization. We always appreciate and welcome contributions like this.

2022-06-22 16:53 UTC, PepijnSenders commented
btw @zashraf1985 some of these tests are failing not because of my PR but because of your CI

2022-06-24 18:43 UTC, PepijnSenders commented
@zashraf1985 all tests are fixed now :), would have been amazing if your specs were written in TS lol

2022-07-01 19:14 UTC, mikechu-optimizely commented
Our test suite included some older versions of browsers that we're swapping out.  We're upgrading that suite now via another PR.  We'll then update this branch and merge it afterwards.  

Local testing looks good so far.

Thanks for hanging in there with us.

@PepijnSenders Can you sign our [Contributor License Agreement (CLA)](https://docs.google.com/a/optimizely.com/forms/d/e/1FAIpQLSf9cbouWptIpMgukAKZZOIAhafvjFCV8hS00XJLWQnWDFtwtA/viewform) when you have a moment?

2022-07-01 23:43 UTC, zashraf1985 requested changes
Thanks again for the contribution. I had one pass through it today and added some comments . It will be great if you can find some time to take a look at those. Can you also update your branch with the latest master.

2022-07-04 18:09 UTC, PepijnSenders commented on packages/optimizely-sdk/lib/core/decision_service/index.ts
> +          experiment.key
What about adding prettier to your setup? 😸

2022-07-11 16:49 UTC, PepijnSenders commented on packages/optimizely-sdk/lib/core/decision_service/index.ts
> +    user: OptimizelyUserContext
@zashraf1985 this is not according to your prettier configuration, I formatted all the files.

2022-07-11 16:53 UTC, PepijnSenders commented on packages/optimizely-sdk/lib/core/decision_service/index.ts
> +    user: OptimizelyUserContext
@zashraf1985 this is not the case according to this prettier file: https://github.com/optimizely/javascript-sdk/blob/master/packages/optimizely-sdk/.prettierrc#L7

2022-07-11 16:58 UTC, PepijnSenders commented on packages/optimizely-sdk/lib/core/decision_service/index.ts
> +      }
`.get()` might return `undefined`, so you want to make sure it exists before you set it.

2022-08-17 18:01 UTC, opti-jnguyen commented
Merged recent changes from javascript-sdk master branch into this PR, however some issues remain regarding:

- [ ] `audiencesById.get` failing in `optimizely-sdk/lib/core/audience_evaluator/index.ts`
- [ ] New ODP segments feature test failing for test "should contain all expected unique odp segments in allSegments"

Will need to fix these and ensure `npm run test` succeeds before proceeding.

2022-08-23 14:41 UTC, opti-jnguyen commented
@PepijnSenders - thank you for the contribution! After internal testing there's a couple issues that are preventing us from merging at this time:

1. Testing usage of the Map implementation on very large datafile sizes (>2 MB) resulted in slower runtimes of >=10% on average vs. the original object implementation. Methods of testing included manual testing with `performance.now()` and testing leveraging existing unit tests.

2. General risk due to changing the original implementation without much ancillary benefit.

---

Going forward we'll be making an attempt at experimenting between using Map and object using your implementation as inspiration and benchmarking differences as we go and implement according based on the results we see.

For the time being though, we'll be closing this PR but feel free to raise an issue if you have any comments, questions, or found different benchmarks when testing yourself. Thank you!

2022-08-23 14:41 UTC, closed without merging