ODP Datafile Parsing
optimizely/javascript-sdk pull request #775
Opened 2022-08-05 09:38 UTC by opti-jnguyen

## Summary
- Parses datafile for new ODP-specific fields including 'publicKey' and 'host.
- 

## Test plan
- New tests implemented with new test datafile for ODP integrated with and without audience segments.
- Tests cover project config creation with new test datafiles and check for new allSegments, publicKeyForOdp, and hostForOdp variables.

## Issues
- OASIS-8390

---

Note: Prettier caused many whitespace changes to be applied. To see only the related changes, click the gear icon and select "Hide whitespace changes" in the diff.

2022-08-05 22:34 UTC, jaeopt requested changes
Looks good! A couple of changes suggested.

2022-08-05 22:34 UTC, jaeopt commented on packages/optimizely-sdk/lib/core/project_config/index.ts
> +    projectConfig.allSegments = projectConfig.allSegments.concat(getAudienceSegments(projectConfig.audiencesById[audience]))
Can we filter out redundant segments from multiple audiences?

2022-08-05 22:34 UTC, jaeopt commented on packages/optimizely-sdk/lib/core/project_config/index.tests.js
> +                  "match": "not-qualified"
This test is a little strange. We do not have "not-qualified" match type. If intentional error testing, it'll be more clear with a different name to avoid confusion like "invalid".

2022-08-05 22:34 UTC, jaeopt commented on packages/optimizely-sdk/lib/tests/test_data.js
> +  ],
Let's have one more test case like `{key = odp, a = 1, b = true}, {key=x, a=y}` to validate it can tolerate future changes ("key" is the only field required).

2022-08-05 22:34 UTC, jaeopt commented on packages/optimizely-sdk/lib/core/project_config/index.ts
> +    projectConfig.allSegments = projectConfig.allSegments.concat(getAudienceSegments(projectConfig.audiencesById[audience]))
Add a test case for this redundant segments.

2022-08-05 23:34 UTC, zashraf1985 requested changes
Looks Great! Suggested one change.

2022-08-05 23:34 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/core/project_config/index.ts
> +  allSegments: string[];
you could use a set here to avoid duplicates

2022-08-05 23:34 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/core/project_config/index.ts
> +    projectConfig.allSegments = projectConfig.allSegments.concat(getAudienceSegments(projectConfig.audiencesById[audience]))
This might contain duplicates, if you use set it will take care of it automatically i believe.

2022-08-10 16:11 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/core/project_config/index.ts
> +    projectConfig.allSegments = projectConfig.allSegments.concat(getAudienceSegments(projectConfig.audiencesById[audience]))
Resolved here: https://github.com/optimizely/javascript-sdk/pull/775/commits/baa63ea428de6ff92fb8d98ccd7cae09caac3864

2022-08-10 16:11 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/core/project_config/index.tests.js
> +                  "match": "not-qualified"
Resolved here: https://github.com/optimizely/javascript-sdk/pull/775/commits/baa63ea428de6ff92fb8d98ccd7cae09caac3864

2022-08-10 16:11 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/tests/test_data.js
> +  ],
Resolved here: https://github.com/optimizely/javascript-sdk/pull/775/commits/baa63ea428de6ff92fb8d98ccd7cae09caac3864

2022-08-10 16:11 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/core/project_config/index.ts
> +  allSegments: string[];
Resolved here: https://github.com/optimizely/javascript-sdk/pull/775/commits/baa63ea428de6ff92fb8d98ccd7cae09caac3864

2022-08-10 16:11 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/core/project_config/index.ts
> +    projectConfig.allSegments = projectConfig.allSegments.concat(getAudienceSegments(projectConfig.audiencesById[audience]))
Resolved here: https://github.com/optimizely/javascript-sdk/pull/775/commits/baa63ea428de6ff92fb8d98ccd7cae09caac3864

2022-08-10 16:14 UTC, opti-jnguyen commented
@jaeopt , @zashraf1985 - updated to resolve your comments above. Let me know if the solution looks good to you or if I missed anything... thanks!

2022-08-10 17:56 UTC, jaeopt approved these changes
LGTM

2022-08-10 18:19 UTC, zashraf1985 approved these changes
Looks Great!

2022-08-10 20:47 UTC, merged