feat: Add ODP/ATS VuidManager
optimizely/javascript-sdk pull request #776
Opened 2022-08-15 17:57 UTC by mikechu-optimizely

## Summary
Full Stack client should create and manage a unique device or visitor ID (VUID), persistent and shared between multiple SDK instances.

## Test plan
Added new unit test spec files to base package

## Issues
OASIS-8412

2022-08-15 23:24 UTC, jaeopt requested changes
Looks good. A couple of suggestions.
I see some JS codes I cannot cover.

2022-08-15 23:24 UTC, jaeopt commented on packages/optimizely-sdk/tests/vuidManager.spec.ts
> +    expect(vuid.length).toBeGreaterThan(20);
Can check equalTo(32)

2022-08-15 23:24 UTC, jaeopt commented on packages/optimizely-sdk/tests/vuidManager.spec.ts
> +  });
expect(manager2.isVuid(vuid3)).toBeTruthy();

2022-08-16 15:13 UTC, mikechu-optimizely commented
This PR remains ready for @zashraf1985 's review as well.

2022-08-16 17:24 UTC, jaeopt approved these changes
LGTM

2022-08-16 18:24 UTC, zashraf1985 requested changes

2022-08-16 18:24 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/key_value_cache/browserAsyncStorageCache.ts
> +    return item === null ? Promise.resolve().then(() => '') : Promise.resolve(item);
```suggestion
    return Promise.resolve(item || null);
```

2022-08-16 18:24 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/key_value_cache/inMemoryAsyncStorageCache.ts
> +export default class InMemoryAsyncStorageCache implements PersistentKeyValueCache {
Why do we need this in memory? If we are looking for an in-memory cache for some other scenario, we should keep it synchronized. Forcing it to be async does not look like a good pattern. You are implementing a `PersistentKeyValueCache` as an `in-memory` which is a contradiction in itself. If you want both persistent and in-memory for different use cases, they should be different interfaces and implementations, one with promises and one synchronous

2022-08-16 18:24 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/key_value_cache/reactNativeAsyncStorageCache.ts
> +    return val ? val : '';
why are you returning empty string if async storage returns a falsy value? Shouldn't it return null in this case because it implies that key doesn't exist int he cache

2022-08-16 18:24 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/vuid_manager/index.ts
> +    }
Why are you getting `cachedValue` as dict. Shouldn't it be a `String` or `null` i.e `vuid` value directly?

2022-08-16 18:24 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/vuid_manager/index.ts
> +    const dict = new Map<string, string>([[this._keyForVuid, vuid]]);
Why do you need to create a map and save it. Why not simply use the cache as a key value store and set and get string values for vuid directly?

2022-08-16 21:07 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/plugins/vuid_manager/index.ts
> +    }
@jaeopt Do we need to cache a dictionary of VUIDs or just the vuid key-val?

2022-08-16 21:20 UTC, jaeopt commented on packages/optimizely-sdk/lib/plugins/vuid_manager/index.ts
> +    }
Can we keep the dictionary as is? Originally, we had other values in the dictionary (like a list of users bound with the vuid). It turns out that those values are not needed persistently, so removed. It looks like not clean to have the dict to keep the vuid only, but we may need to add props in future.

2022-08-16 21:40 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/vuid_manager/index.ts
> +    }
Thanks @jaeopt. Instead of serializing/deserializing and managing the whole dictionary ourselves, do you think it makes sense to use the cace prefix to differentiate the items from others. For example we can prefix all the entries for this cache with `vuid-manager-`. In this way, we will still be using a primary key value storage instead of pulling a value manually from our own custom dictionary which can grow large and cause potential performance issues. What do you guys think?

2022-08-16 22:01 UTC, jaeopt commented on packages/optimizely-sdk/lib/plugins/vuid_manager/index.ts
> +    }
Yeah, using prefix makes sense to simplify the access and also can be extended. I suggest to use "optimizely-" for the prefix for grouping all keys for us. Let's change it to a flat key-value with "optimizely-vuid" as a key in this case. I'll fix swift-sdk for consistency.

2022-08-16 22:02 UTC, jaeopt commented on packages/optimizely-sdk/lib/plugins/vuid_manager/index.ts
> +    }
@zashraf1985 @mikechu-optimizely

2022-08-17 17:46 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/plugins/vuid_manager/index.ts
> +    }
Oops. I missed this directive.  I will adjust my code and tests.

2022-08-17 21:25 UTC, zashraf1985 commented on packages/optimizely-sdk/tests/vuidManager.spec.ts
> +import { anyString, anything, instance, mock, resetCalls, verify, when } from 'ts-mockito';
This is good!

2022-08-17 21:42 UTC, zashraf1985 approved these changes
Looks Great!

2022-08-18 18:07 UTC, merged