feat: Add ODP LRU Cache
optimizely/javascript-sdk pull request #777
Opened 2022-08-19 10:39 UTC by opti-jnguyen

## Summary
A generic LRU cache to support efficient caching of the ODP segments results.

## Test plan
Added new unit tests files for Client/Server/React Native implementations.

## Issues
OASIS-8410

2022-08-19 15:26 UTC, opti-jnguyen commented
Originally created React Native specific variations for AsyncStorage consideration, but since we're only concerned with an in-memory LRU Cache, will remove LRU Cache code specific to React Native.

2022-08-22 17:53 UTC, jaeopt requested changes
Looks good! A few small changes suggested.

2022-08-22 17:53 UTC, jaeopt commented on packages/optimizely-sdk/lib/core/odp/lru_cache/LRUCacheElement.ts
> +export class LRUCacheElement<V> {
```suggestion
export class CacheElement<V> {
```
This element is a generic cache element, not only for LRU.

2022-08-22 17:53 UTC, jaeopt commented on packages/optimizely-sdk/lib/core/odp/lru_cache/LRUCache.ts
> +    private _timeout = 1000 * 600 // Milliseconds each entry has before it becomes stale
Default cache size depends on that it's for server (node) or client (browser). If we want to feed them per env, can we consider to remove this default value here?

2022-08-22 17:53 UTC, jaeopt commented on packages/optimizely-sdk/lib/core/odp/lru_cache/LRUCache.ts
> +        this._map.set(key, element)
Can we move this adding back to cache after "is_stale" check below?  We do not need to keep staled item.

2022-08-22 17:53 UTC, jaeopt commented on packages/optimizely-sdk/lib/core/odp/lru_cache/LRUCache.ts
> +     * Removes the element if it is stale.
I think peek will be more useful without side effect. Can we remove the stale clean up?

2022-08-22 17:53 UTC, jaeopt commented on packages/optimizely-sdk/lib/core/odp/lru_cache/LRUCache.ts
> +        }
Remove?

2022-08-23 18:30 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/core/odp/lru_cache/LRUCache.ts
> +     * Removes the element if it is stale.
@jaeopt - Main reason this was added because I noticed when using `peek()` at elements that should be stale returned a value.

2022-08-23 18:31 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/core/odp/lru_cache/LRUCache.ts
> +        }
@jaeopt - Should `peek()` return null if stale?

2022-08-23 18:52 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/core/odp/lru_cache/LRUCache.ts
> +        }
^ Resolved - will remove completely.

2022-08-24 21:28 UTC, jaeopt approved these changes
LGTM

2022-08-25 04:27 UTC, merged