feat: Add ODP GraphQL AP Interface
optimizely/javascript-sdk pull request #778
Opened 2022-08-22 18:04 UTC by mikechu-optimizely

## Summary
Add plugin to provide an internal service for ODP GraphQL server access. Should support 3 potential clients for Browser, Node, ReactNative

## Test plan
New .spec. files added unit tests

## Issues
OASIS-8487

2022-08-23 22:54 UTC, zashraf1985 requested changes
Looks great! Suggested a few changes. I assume `fetch` should work in all environments but it will be great if you can check it once for browser, node and react native.

2022-08-23 22:54 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/odp/graphql_manager.ts
> +    }
If you invert this check, it will work better. The current check will only log error if the whole path leading up to the `edges` is present. If anything is missing in between, it will consider it a success response and will try to parse it after the check and crash. You could probably check for negation and invert it so it will cover the null cases too

2022-08-23 22:54 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/odp/graphql_manager.ts
> +    } catch {
Can you catch the actuall error and print its details to the logs

2022-08-23 22:54 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/odp/odp_client.ts
> +    const fetchFailureMessage = 'Audience segments fetch failed';
This can be moved near the top of the file outside the function.

2022-08-23 22:54 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/odp/odp_client.ts
> +    const emptyResponse = undefined;
lets make it null. And you also dont need to define it. Simply return null explicitly where you want. that will be more readable

2022-08-23 22:54 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/odp/query_segments_parameters.ts
> +  public ApiKey: string | undefined;
javascript convention is camelCase for the vars. It would be apiKey. Same applies for other members of this class.

2022-08-23 22:54 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/odp/query_segments_parameters.ts
> +  constructor(parameters: { UserValue: string; ApiKey: string; UserKey: string; SegmentsToCheck: string[]; ApiHost: string }) {
variable names should be camelCase

2022-08-23 22:54 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/odp/query_segments_parameters.ts
> +  public ToJson(): string {
this function name should also be cameCase

2022-08-23 22:54 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/odp/query_segments_parameters.ts
> +  public ToJson(): string {
This is not converting it in json. It's probably converting it into the format expected by the graphQL call. If that is the case, then i will suggest changing the name of method.

2022-08-23 22:54 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/utils/json_schema_validator/index.ts
> +export function validate(jsonObject: unknown, validationSchema: JSONSchema4 = schema, shouldThrow = true): boolean {
NIT: shouldThrowOnError

2022-08-23 22:56 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/odp/graphql_manager.ts
> +    }
I am assuming `?` fails with undefined. If it fails consistently with `null` then it should work. A safe check would be
```if (!arsedSegments?.data?.customer?.audiences?.edges)```

2022-08-24 11:57 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/plugins/odp/graphql_manager.ts
> +    }
Yup. [Optional chaining](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html) will stop on nullish (null or undefined) expressions.

> At its core, optional chaining lets us write code where TypeScript can immediately stop running some expressions if we run into a null or undefined.

I'll invert the pattern as directed.

2022-08-24 12:00 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/plugins/odp/graphql_manager.ts
> +    }
I also see my check for `=== null` would not eval to true since optional chaining returns `undefined`

2022-08-24 12:10 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/plugins/odp/odp_client.ts
> +    const emptyResponse = undefined;
I tend to like self-documenting code which is why I declared and used a `const` here.   This gives the reader the understanding that I'm intentionally returning what amounts to a "no response".  

After further reading, I agree that the union type should have a `null` instead of `undefined`.  `undefined` gives the sense that nothing's been set yet, while `null` provides knowledge of an intentional "empty" return.  I'll alter this through the code in this PR.

2022-08-24 19:59 UTC, zashraf1985 approved these changes

2022-08-30 15:15 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/plugins/odp/graphql_manager.ts
> -    } catch (error: any) {
Looks like removing this is causing CI/CD to throw a linting error?

2022-08-30 20:10 UTC, zashraf1985 requested changes
Looks Great! Just added a few suggestions.

2022-08-30 20:10 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/utils/http_request_handler/request_handler_factory.ts
> +    if (type === 'node') {
These "node" and "browser" can go as enums

2022-08-31 21:22 UTC, zashraf1985 approved these changes

2022-08-31 21:27 UTC, merged