refactor: Consolidate datafile-manager package into optimizely-sdk
optimizely/javascript-sdk pull request #781
Opened 2022-08-31 13:34 UTC by ozayr-zaviar

## Summary
Integrated Datafile Manager package with Optimizely SDK to remove external dependency.

## Test plan
All existing unit tests and FSC tests should pass.

2022-09-02 12:57 UTC, mikechu-optimizely commented
Sorry about all the code collisions @ozayr-zaviar  😬

2022-09-22 18:43 UTC, zashraf1985 requested changes
Looks great! Suggested a few minor changes. Can you update lock file version to 2.

2022-09-22 18:43 UTC, zashraf1985 commented on packages/optimizely-sdk/karma.base.conf.js
> -    mode: 'production',
can you revert it back if it works?

2022-09-22 18:43 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/datafile_manager/browser_http_polling_datafile_manager.ts
> +
fix end of line

2022-09-22 18:43 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/datafile_manager/http_polling_datafile_manager.tests.js
> +    // sandbox.stub(datafileManager, 'NodeDatafileManager')
remove unneeded commented code.

2022-09-22 18:43 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/datafile_manager/react_native_http_polling_datafile_manager.ts
> +
fix end of line

2022-09-23 16:52 UTC, zashraf1985 approved these changes
Looks Great!

2022-09-23 17:59 UTC, merged