feat: Added ODP RestApi interface for sending Events to ODP
optimizely/javascript-sdk pull request #785
Opened 2022-09-12 15:00 UTC by mikechu-optimizely

## Summary
This module provides an internal service for ODP event REST API access.

## Test plan

- Added new unit tests to .spec
- All Existing Unit tests pass.
- All existing full-stack compatibility tests pass.

## Issues
- FSSDK-8386 (OASIS-8386 [to pass jira_ticket_reference_check])

2022-09-12 22:35 UTC, jaeopt requested changes
Looks good!
A few changes suggested. I'll review test cases again after splitting them into 2 groups.

2022-09-12 22:35 UTC, jaeopt commented on packages/optimizely-sdk/tests/odpClient.spec.ts
> +              },
It'll be a better test if we have a node with 'state': 'not-ready' as well.

2022-09-12 22:35 UTC, jaeopt commented on packages/optimizely-sdk/tests/odpClient.spec.ts
> +import { OdpEvent } from '../lib/plugins/odp/odp_event';
Can we splint tests into 2 files segmentFetch and odpEvent? In many cases, they should handle errors and responses in different ways. It'll be easier to follow if we split them.

2022-09-13 13:30 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/plugins/odp/odp_client.ts
> +      return RETRY_NOT_ADVISED;
Ah. Ok. I will typically create a constant, so other developers know my intention without reading the method doc or internal comments. I will export the constant too, so my tests are looking for the same value. 

I will revert to using an explicit `null` and remove the indicators/constants throughout.

2022-09-13 13:44 UTC, mikechu-optimizely commented on packages/optimizely-sdk/tests/odpClient.spec.ts
> +import { OdpEvent } from '../lib/plugins/odp/odp_event';
Sure.  I can separate. 

I was attempting to reuse common fixtures and organize via describe() blocks.

2022-09-14 23:22 UTC, jaeopt requested changes
All the changes look good!
A couple of small changes suggested.

2022-09-14 23:22 UTC, jaeopt commented on packages/optimizely-sdk/lib/plugins/odp/odp_client.ts
We also filter out the request when "segmentsToCheck" is empty. The ODP server will reject it as an error.
SDK need to return empty segments array for them locally. I do not see that in "graphql_manager". Please add the filter.

2022-09-15 17:24 UTC, zashraf1985 requested changes
Looks great overall! 

Super NIT: There are some places where `{type} | undefined` is used, i believe those can be changed to `{type}?`.

2022-09-15 17:24 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/odp/odp_event.ts
> +  private readonly _type: string;
My preference would be to not use these leading `underscores` because it's already typescript and we are explicitly using `private` modifier. What do you think?

2022-09-15 17:24 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/odp/odp_request_parameters.ts
> +  public apiKey: string | undefined;
```suggestion
  public apiKey?: string;
```

2022-09-15 17:24 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/odp/odp_request_parameters.ts
> +  public apiEndpoint: string | undefined;
```suggestion
  public apiEndpoint?: string;
```

2022-09-15 20:28 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/plugins/odp/odp_client.ts
@jaeopt Is this an ok solution to empty `segmentsToCheck`?

```javascript
if (parameters?.segmentsToCheck?.length === 0) {
  this._logger.log(LogLevel.WARNING, 'No segments to query');
  return null;
}
```

2022-09-15 20:33 UTC, jaeopt commented on packages/optimizely-sdk/lib/plugins/odp/odp_client.ts
@mikechu-optimizely  let's return an empty array (valid) as I see null as a fetch error.

2022-09-15 20:38 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/plugins/odp/odp_client.ts
> +  public async sendEvents(parameters: SendEventsParameters): Promise<number | null> {
That's a cool trick. 

Later I have `parameters.toJson();` which I'm not certain how I'd handle if deref-ing in the signature.

I'm committing a possible solution.  Tell me what you think.

2022-09-15 20:42 UTC, jaeopt commented on packages/optimizely-sdk/lib/plugins/odp/odp_client.ts
@mikechu-optimizely Also remove log since this a common case when no segments are used for any audiences.

2022-09-15 21:25 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/utils/http_request_handler/browser_request_handler.ts
> -const READY_STATE_DONE = 4;
@zashraf1985 Are you ok if we remove this in exchange for `XMLHttpRequest.DONE`?

2022-09-15 22:04 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/utils/http_request_handler/browser_request_handler.ts
> -const READY_STATE_DONE = 4;
I think that will actually be better.

2022-09-15 22:06 UTC, zashraf1985 approved these changes
LGTM!

2022-09-16 12:44 UTC, mikechu-optimizely commented
@jaeopt Shall I hold for your approval too?

2022-09-16 16:03 UTC, jaeopt requested changes
All changes for RestApi look good. A couple of suggestions for GraphQL Api.

2022-09-16 20:10 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/plugins/odp/odp_client.ts
>      }
I've added the check at the graphql_manager level too.  If you're okay with the redundancy, I'd like the check to also be on odp_client.

I'm happy to remove it, though.

2022-09-16 21:15 UTC, jaeopt requested changes
A couple of more suggestions about filtering invalid api params.

2022-09-16 21:15 UTC, jaeopt commented on packages/optimizely-sdk/lib/plugins/odp/graphql_manager.ts
>      }
Can we move this check up to before "odpClient.querySegments()" call? We should not call API with empty segmentsToCheck.

2022-09-16 21:15 UTC, jaeopt commented on packages/optimizely-sdk/lib/plugins/odp/odp_client.ts
> +
Return '' string here will be translated into a JSON error in the upper level.
I think we better remove all these redundant check here and requires apiKey/apiEndpoints/segmentsToCheck to have not-emtpy values.

2022-09-16 21:15 UTC, jaeopt commented on packages/optimizely-sdk/lib/plugins/odp/odp_client.ts
>      }
For consistency with segments-manager, we can move this validation to the upper level (event-manager) too.

2022-09-19 13:37 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/plugins/odp/odp_client.ts
>      }
I'd like to offer one last option for centralizing validation at this below-event-manager level.  

If this does not meet your approval, I will remove all validation at this level and depend upon event manager to solely.

2022-09-19 22:11 UTC, jaeopt requested changes
I see some complexity added with params pack/unpack. Also concerned about exceptions thrown while packaging. We can consider removing the pack/unpack. Let's chat.

2022-09-20 15:53 UTC, mikechu-optimizely commented
Abandoning this PR.

2022-09-20 15:53 UTC, closed without merging