feat: ODP REST API for Sending ODP Events
optimizely/javascript-sdk pull request #786
Opened 2022-09-21 13:16 UTC by mikechu-optimizely

## Summary
Adding module to provide an internal service for sending events to ODP's REST API.

## Test plan

- Added new unit tests to .spec
- All Existing Unit tests pass.
- All existing full-stack compatibility tests pass.

## Issues
- FSSDK-8386 (OASIS-8386 [to pass jira_ticket_reference_check])

2022-09-21 17:42 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/plugins/odp/graphql_manager.ts
> +    return json.join('');
@opti-jnguyen Is this what we settled on for building the GraphQL query?

2022-09-21 22:50 UTC, jaeopt requested changes
I see missing some error handlings. Also we can consider removing {GraphQLManager, RestApiManager} since most logic is in OdpClient. See my comments for more context.

2022-09-21 22:50 UTC, jaeopt commented on packages/optimizely-sdk/lib/plugins/odp/rest_api_manager.ts
> +    if (events.length === 0) {
Check null for apiKey and apiHost?  Not much done in this layer, so should be merged to the upper layer (OdpEventManager).

2022-09-21 22:50 UTC, jaeopt commented on packages/optimizely-sdk/lib/plugins/odp/rest_api_manager.ts
> +    this.errorHandler = errorHandler;
Do we use this errorHandler here and below? Can we remove it?

2022-09-21 22:50 UTC, jaeopt commented on packages/optimizely-sdk/lib/plugins/odp/odp_client.ts
> +    return response.statusCode ?? 0;
We need to log other errors (status 400+)

2022-09-21 22:50 UTC, jaeopt commented on packages/optimizely-sdk/lib/plugins/odp/odp_client.ts
> +    return response.body;
We need to log other errors (status 400+) too.

2022-09-21 22:50 UTC, jaeopt commented on packages/optimizely-sdk/lib/plugins/odp/graphql_manager.ts
> +    if (segmentsToCheck?.length === 0) {
Need to check null of apiKey and apiHost before empty segmentsToCheck.

2022-09-22 13:18 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/utils/http_request_handler/request_handler_factory.ts
> +      return null as unknown as RequestHandler;
I'm rolling back these changes and putting them in [PR 787](https://github.com/optimizely/javascript-sdk/pull/787).

2022-09-22 23:37 UTC, zashraf1985 requested changes
Great Work Overall! Requested a few changes.

2022-09-22 23:37 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/odp/graphql_manager.ts
> +  private toGraphQLJson(userKey: string, userValue: string, segmentsToCheck: string[]): string {
Since Its not using any instance variables, Is it ok to make it static or  move it out of the class somewhere on the top ?

2022-09-22 23:37 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/odp/graphql_manager.ts
> +  }
```suggestion
  private toGraphQLJson(userKey: string, userValue: string, segmentsToCheck: string[]): string => ([
    '{"query" : "query {customer"',
    `(${userKey} : "${userValue}") `,
    '{audiences',
    '(subset: [',
    ... segmentsToCheck?.map((segment, index) => 
      `\\"${segment}\\"${index < segmentsToCheck.length - 1 ? ',' : ''}`
    ) || '',
    '] {edges {node {name state}}}}}"}',
  ].join(''));
```

2022-09-22 23:37 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/odp/odp_event.ts
> +    this.data = data ?? new Map<string, any>();
Can we use `|` here to define possible types that can go here instead of any like `string | number | boolean` etc

2022-09-22 23:37 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/odp/rest_api_manager.ts
> +    this.requestHandler = RequestHandlerFactory.createHandler(this.logger);
Can we pass `requestHandler from outside and create a default one as a fallback only? Does factory handle creation of handler according to the platform?

2022-09-22 23:37 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/odp/rest_api_manager.ts
> +    return shouldRetry;
Sending back a boolean explicitly recommending to retry or not looks like a very good idea 👍

2022-09-22 23:37 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/utils/http_request_handler/browser_request_handler.ts
> +        if (request.readyState === XMLHttpRequest.DONE) {
👍

2022-09-22 23:37 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/utils/http_request_handler/request_handler_factory.ts
> +      return null as unknown as RequestHandler;
This is a good way to create a handler but the way javascript SDK makes use of tree shaking to include and exclude certain modules based on the entry, this can cause problem. We might need to change it to passing the request handlers all the way down from the entry points. what do you think?

2022-09-23 14:31 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/plugins/odp/rest_api_manager.ts
> +    return shouldRetry;
I stole it from @andrewleap-optimizely in the Python repo 😉

2022-09-23 15:02 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/plugins/odp/odp_event.ts
> +    this.data = data ?? new Map<string, any>();
Great point.  Python uses it's `Any` type and Java used `Object`. I think a union type makes sense for Typescript...but I worry I'll miss a primitive.  

I'm going to use `object` heir and we can pass `String`, `Number`, `Boolean` if needed.  What's your thought?

2022-09-23 15:19 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/plugins/odp/odp_event.ts
> +    this.data = data ?? new Map<string, any>();
Actually, maybe this is (as WebStorm suggested) a case to use Typescript's `unknown`  🤔

2022-09-23 16:03 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/odp/odp_event.ts
> +    this.data = data ?? new Map<string, any>();
Yes! If we want to keep it open, `unknown` is a good option.

2022-09-23 17:06 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/utils/http_request_handler/request_handler_factory.ts
> +      return null as unknown as RequestHandler;
@zashraf1985 Can we collaborate on your idea/solution on a call?

2022-09-23 17:28 UTC, jaeopt requested changes
Looks good! A few more small changes suggested.

2022-09-23 17:28 UTC, jaeopt commented on packages/optimizely-sdk/lib/plugins/odp/odp_event.ts
> +    this.data = data ?? new Map<string, any>();
Just a reminder that we need to validate the type of values (string, number, boolean and null), probably in OdpEventManager later.

2022-09-23 17:28 UTC, jaeopt commented on packages/optimizely-sdk/lib/plugins/odp/rest_api_manager.ts
> +    this.timeout = timeout;
I do not see this timeout used.

2022-09-23 17:28 UTC, jaeopt commented on packages/optimizely-sdk/lib/utils/http_request_handler/request_handler_factory.ts
> +      return new NodeRequestHandler(logger, timeout);
I understand this refactoring has been moved to a separate PR already?

2022-09-23 17:28 UTC, jaeopt commented on packages/optimizely-sdk/tests/restApiManager.spec.ts
> +  let mockErrorHandler: ErrorHandler;
Not used any more?

2022-09-23 17:28 UTC, jaeopt commented on packages/optimizely-sdk/tests/restApiManager.spec.ts
> +  const makeManagerInstance = () => new RestApiManager(instance(mockLogger), instance(mockOdpClient));
OdpClient is not used any more. TS does not complain about this error :)

2022-09-23 17:28 UTC, jaeopt commented on packages/optimizely-sdk/tests/restApiManager.spec.ts
> +  let mockOdpClient: IOdpClient;
Not used any more?

2022-09-23 17:28 UTC, jaeopt commented on packages/optimizely-sdk/tests/odpClientSendEvents.spec.ts
> +    new OdpClient(instance(mockLogger), instance(mockNodeRequestHandler));
We do not keep this any more, correct?  We can consider merging these tests to RestApiManager tests or removing them.

2022-09-26 13:17 UTC, mikechu-optimizely commented on packages/optimizely-sdk/tests/restApiManager.spec.ts
> +  let mockErrorHandler: ErrorHandler;
Sorry you went through this PR again on Fri @jaeopt .  I hadn't pushed all my changes.

2022-09-26 15:54 UTC, zashraf1985 approved these changes
Looks Great!

2022-09-26 16:09 UTC, jaeopt requested changes
Changes look good. I found a couple of cases inconsistent.

2022-09-26 16:09 UTC, jaeopt commented on packages/optimizely-sdk/lib/plugins/odp/graphql_manager.ts
> +      return null;
This looks good. I see one more error below (line 114) which is WARNING level. Can you fix it too for consistency?

2022-09-26 16:09 UTC, jaeopt commented on packages/optimizely-sdk/lib/plugins/odp/rest_api_manager.ts
>        shouldRetry = true;
Isn't this override logic in lines 82-87, always?

2022-09-26 17:29 UTC, jaeopt approved these changes
LGTM

2022-09-26 17:39 UTC, merged