feat: Added ODPEventManager implementation
optimizely/javascript-sdk pull request #789
Opened 2022-09-30 15:22 UTC by mikechu-optimizely

## Summary
Added `OdpEventManager` implementation.

## Test plan
- Unit tests added
- Existing tests continue to pass

## Jira
FSSDK-8443

2022-09-30 15:37 UTC, mikechu-optimizely commented
Looks like there are older unit tests (around tests/v1EventProcessor.react_native.spec.ts) that are now failing.  

Fortunately, this also matches what's going on on my local dev machine.   I'll try correcting these unit tests and create a predecessor PR that we can merge before this PR. 

I still think code reviews for Event Manager here can continue.

2022-10-03 15:09 UTC, mikechu-optimizely commented
This is ready for review @jaeopt & @zashraf1985 whenever you're available.  I'll appreciate your thorough review.

2022-10-03 19:49 UTC, zashraf1985 requested changes

2022-10-03 19:49 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/odp/odp_config.ts
> +  private _apiHost: string;
NIT: Since its typescript and we already have access modifiers available, i believe it is safe to remove these leading underscores for private members. what do you think?

2022-10-03 19:49 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/odp/odp_config.ts
> +    this._segmentsToCheck = segmentsToCheck ?? [] as string[];
NIT: It might actually work without explicit casting too, not sure though.

2022-10-03 19:49 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/odp/odp_config.ts
> +    this._odpServiceIntegrated = this._apiKey && this._apiHost ? ODP_CONFIG_STATE.INTEGRATED : ODP_CONFIG_STATE.UNDETERMINED;
This is being used at multiple places. May be move it to a funciton?

2022-10-03 19:49 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/odp/odp_config.ts
> +    return this._apiKey !== null && this._apiKey !== '' && this._apiHost !== null && this._apiHost !== '';
```suggestion
    return !!this._apiKey && !!this._apiHost;
```

2022-10-03 19:49 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/odp/odp_event_dispatcher.ts
> +  public constructor(odpConfig: OdpConfig,
Since there are so many options, it might be helpful and more user friendly to use an inline de structured object instead of expecting users to pass arguments in the correct places. What do you think?

2022-10-03 19:49 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/odp/odp_event_dispatcher.ts
> +    this.flushInterval = flushInterval && flushInterval > 0 ? flushInterval : DEFAULT_FLUSH_INTERVAL;
```suggestion
    this.queueSize = queueSize || DEFAULT_QUEUE_SIZE;
    this.batchSize = batchSize || DEFAULT_BATCH_SIZE;
    this.flushInterval = flushInterval || DEFAULT_FLUSH_INTERVAL;
```

2022-10-03 19:49 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/odp/odp_event_dispatcher.ts
> +    this.intervalId = setInterval(() => {
What is the need of empty interval callback. It will be helpful to add a detailed comment here explaining it.

2022-10-03 19:49 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/odp/odp_event_dispatcher.ts
> +    (async () => await this.processQueue())();
Since `start` does not have to wait for `processQueue`. The inline async and await do not seem to do much to me. Can simply calling `this.processQueue` serve the purpose? If there is a special reason to add async and away here, it will be helpful to have a detailed explanation in a comment.

2022-10-03 19:49 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/odp/odp_event_dispatcher.ts
> +    clearInterval(this.intervalId);
Just curios what purpose is this serving?

2022-10-03 19:49 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/odp/odp_event_dispatcher.ts
> +      this.intervalId = setInterval(() => this.processQueue(), this.flushInterval);
setInterval if for the case where you need a recurring callback at regular intervals till you clear it. Here since you are setting it every time and clearing it after one call, its more suitable to use `setTimeout`.

2022-10-03 19:49 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/odp/odp_event_dispatcher.ts
> +    this.state = STATE.RUNNING;
I believe this is redundant. what do you think?

2022-10-03 19:49 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/odp/odp_event_dispatcher.ts
> +      this.intervalId = setInterval(() => this.processQueue(), this.flushInterval);
Setting the next tick to flushInterval is risky because then you will miss all the events in between. For example the batch size was 10 and flush interval was 3 seconds. You initially got 5 events and flush interval passed and you flushed those and then you set interval for next 3 seconds. but in the next 2nd, 40 more events enqueued, those events will need to wait for the flush interval to pass because there is nobody looking for those events in between. this is why we needed an implementation where it either waits on `flush interval` or next event to be available whatever happens first. This is why we used blocking queue in java sdk.

My understanding can be totally wrong though.. what do you think?

2022-10-03 19:49 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/odp/odp_event_dispatcher.ts
> +    await this.processQueue();
What is the need to call this one more time here?

2022-10-03 19:49 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/odp/odp_event_manager.ts
> +    (async () => await this.eventDispatcher.enqueue(event))();
why is this inline async await needed? Can we simply call the method directly?

2022-10-04 12:38 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/plugins/odp/odp_config.ts
> +  private _apiHost: string;
Based on our Teams conversation: when getter or setter is in use, we'll accept underscore-prefixed names for backing fields. 

([resource](https://www.typescriptlang.org/docs/handbook/2/classes.html#getters--setters))

2022-10-04 13:16 UTC, mikechu-optimizely commented on packages/optimizely-sdk/tests/odpEventManager.spec.ts
> +  ),
More in the `data` like this
```js
new OdpEvent(
    't2',
    'a2',
    new Map([['id-key-2', 'id-value-2']]),
    new Map(Object.entries({
      'key-2': 'value2',
      'data_source': 'my-source',
    })),
  ),
```
or another `OdpEvent` like this
```js
new OdpEvent(
    't2',
    'a2',
    new Map([['id-key-2', 'id-value-2']]),
    new Map(Object.entries({
      'key-2': 'value2',
    })),
  ),
  new OdpEvent(
    't3',
    'a3',
    new Map([['id-key-3', 'id-value-3']]),
    new Map(Object.entries({
      'data_source': 'my-source',
    })),
  ),
```

2022-10-04 13:26 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/plugins/odp/odp_event_manager.ts
> +  public sendEvents(events: OdpEvent[]): void {
Oops. I took this from Java.  Sorry.

2022-10-04 16:11 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/plugins/odp/odp_event_manager.ts
> +    event.data = this.augmentCommonData(event.data);
@jaeopt , Can you direct me to some of the checks to perform in the Swift implementation or TDD so I can understand the types of validation? 

eg 
- only primatives
- must be non-null values
- no duplicates
- value length limitations
- total number of items in the collection, etc.

Also, what do we do with data items in the collection that is considered invalid?

2022-10-04 16:15 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/plugins/odp/odp_event_manager.ts
> +    event.data = this.augmentCommonData(event.data);
Oh I found it in the TDD at the end of section 3.4.1 (items 1-4 specifically 4a-c). Apologies.

2022-10-07 18:27 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/plugins/odp/odp_event_manager.ts
> +    }
This research and implementation of handling user agent data from the browser is proving to be quite complex.  

I'd like to move this to another Jira issue after talking it through with Zeeshan.   

This will allow us to move this PR forward and also help me architect this a true plugin so we don't increase the default bundle sizes.

2022-10-11 12:26 UTC, mikechu-optimizely commented
@zashraf1985, Thanks again for pair programming the round of reviews. I'm ready for another look by you and @jaeopt when you have a moment.

2022-10-11 16:20 UTC, jaeopt requested changes
Changes looks good. I see a possible failure in batching and a couple of suggestions to consider.

2022-10-11 17:29 UTC, zashraf1985 requested changes
The overall logic of event queue looks very good. I just have a concern in one asynchronous scenario that we can discuss on call. Also suggested a few minor changes here and there.

2022-10-11 17:29 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/odp/odp_event_dispatcher.ts
> +        await this.makeAndSendBatch();
We should not probably wait for this here and just fire and forget the actual request. This await will cause a weird synchronization problem. I can discuss this and explain it on the call better.

2022-10-11 17:29 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/odp/odp_event_manager.ts
> +      this.logger.log(LogLevel.DEBUG, `Invalid event data keys (${foundInvalidDataInKeys.join(', ')})`);
Is there a way to pass this dynamic string as parameters to log function to be concatenated later only if log level applies?

2022-10-11 17:29 UTC, zashraf1985 commented on packages/optimizely-sdk/lib/plugins/odp/odp_event_manager.ts
> +    eventDispatcher: OdpEventDispatcher,
I agree too. A simple merge should work. Just copy all the functions from the dispatcher to here. what do you think?

2022-10-11 17:30 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/plugins/odp/odp_config.ts
> +    return !!this._apiKey && !!this._apiHost;
Good eye.  I think I was copying Python too closely without full understanding of how it was used.  I think I'll remove `_odpServiceIntegrated`

2022-10-11 17:30 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/plugins/odp/odp_event_dispatcher.ts
> +    this.processQueue();
`start()` handles kicking off the timer to flush the queue no matter event count.

Here, I want to see if by adding a new event we have a batch to process.

2022-10-11 17:30 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/plugins/odp/odp_event_manager.ts
> +    eventDispatcher: OdpEventDispatcher,
Hmmm 🤔   Java had it as a subclass.  I tried replicating via a nested class in Typescript but it was really ugly and unclear.  

If you're okay with the additional time use, I can try not subclassing and maybe run it all under one class. I'll give it a try.

2022-10-11 17:30 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/plugins/odp/odp_event_manager.ts
> +    const validTypes: string[] = ['string', 'number', 'boolean', 'bigint'];
I was going through the Typescript primatives and just listing the ones that sort of made sense.  I'll remove `bigint`. Easy.

2022-10-11 17:30 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/plugins/odp/odp_event_manager.ts
> +    data.set('data_source_version', this.clientVersion);
Finding a good architectural solution to a complex JS Browser problem was taking longer than I thought needed.  

I'd like to move this to Jira FSSDK-8651 to not delay this merge.

2022-10-11 17:30 UTC, mikechu-optimizely commented on packages/optimizely-sdk/tests/odpEventManager.spec.ts
>        'key-3': 3.3,
I'll remove `bigint`.  It should be a rare case that we need to support numbers past [MAX_VALUE](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_VALUE).

2022-10-11 17:33 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/plugins/odp/odp_event_manager.ts
> +      data.set('data_source_version', this.clientVersion);
Sure I'll take a look.  That would save us a Jira ticket 😄

2022-10-11 17:41 UTC, jaeopt commented on packages/optimizely-sdk/lib/plugins/odp/odp_event_dispatcher.ts
> +    this.processQueue();
It looks like the timer set by start() will not be rescheduled after 1st interval if we do not get any event.
If the first event arrives at 11sec, then it won't be flushed until we have 10 events (otherwise never fired). Can you double check if my understanding is correct?

2022-10-11 17:46 UTC, jaeopt commented on packages/optimizely-sdk/lib/plugins/odp/odp_event_manager.ts
> +      this.logger.log(LogLevel.DEBUG, `Invalid event data keys (${foundInvalidDataInKeys.join(', ')})`);
Or consider to remove this too-kind debug message :) They will figure out which one is invalid if we show error.

2022-10-11 17:59 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/plugins/odp/odp_event_manager.ts
> +    eventDispatcher: OdpEventDispatcher,
odp_event_dispatcher.ts deleted

2022-10-11 18:03 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/plugins/odp/odp_event_dispatcher.ts
> +    this.processQueue();
Hmm maybe we should pair up on a call, so I understand your view.

In `setNewTimeout()` I'm going to `this.processQueue(**true**)`.  (vs the `this.processQueue()`)  I sort of wanted to have these as two methods processQueue and flushQueue so it was more clear

cc @zashraf1985

2022-10-11 18:48 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/plugins/odp/odp_event_manager.ts
> +      this.logger.log(LogLevel.DEBUG, `Invalid event data keys (${foundInvalidDataInKeys.join(', ')})`);
Removed.

2022-10-11 20:25 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/plugins/odp/odp_event_manager.ts
> +      data.set('data_source_version', this.clientVersion);
I searched the code and couldn't find where we're gathering an OS, OS version, device type.  

@zashraf1985 , Do you know if we have this already or should we move forward with FSSDK-8651?

2022-10-12 12:25 UTC, mikechu-optimizely commented
Good morning @jaeopt & @zashraf1985.  You'll never guess, but I'm ready for another code review.  👍 😄

2022-10-12 12:50 UTC, mikechu-optimizely commented on packages/optimizely-sdk/tests/odpEventManager.spec.ts
> +  });
@jaeopt  Is this a good test for ensuring flush intervals?

2022-10-12 16:19 UTC, zashraf1985 approved these changes
Looks Good! Great Work!

2022-10-12 16:40 UTC, jaeopt approved these changes
LGTM

2022-10-12 17:06 UTC, merged

2022-10-12 17:08 UTC, mikechu-optimizely commented
Thanks @jaeopt and @zashraf1985