Add Notification Registry for ODP Setting Updates
optimizely/javascript-sdk pull request #795
Opened 2023-01-27 13:52 UTC by opti-jnguyen

## Summary

(Copied from corresponding Java PR: https://github.com/optimizely/java-sdk/pull/501)

- NotificationRegistry is added to create default NotificationCenter for internal use for updating ODPConfig.
- This is to handle a corner case that if in any case user passes different `notificationCenter` to Optimizely and `ProjectConfigManager` then the Notification of `UpdateProjectConfig` will not trigger because its handler is getting added in the main `NotificationCenter` object.
- This will make sure `UpdateProjectConfig` will update `ODPConfig` every time irrespective of different NotificationCenter passed by user.

> Note: cachedConfig doesn't appear to be needed for JS implementation as getConfig() already returns a locally stored configObject: ProjectConfig in memory without the need to await for a return

## Test plan

- Added additional unit test to test NotificationRegistry
- All tests should pass.

## Issues
- [FSSDK-8779](https://jira.sso.episerver.net/browse/FSSDK-8779)

2023-01-27 14:14 UTC, mikechu-optimizely reviewed
Just some thoughts.  I'm not sure I'm the official code reviewer so....

2023-01-27 14:14 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/core/notification_center/notification_registry.ts
> +  public static getNotificationCenter(sdkKey?: string, logger?: LogHandler): NotificationCenter | null {
I think `string` can be null, but could we update the signature, removing the `?` to discourage passing a null value?  

What's your opinion on `logger: LogHandler = null` too?

2023-01-27 14:14 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/core/odp/odp_config.ts
> +  private _segmentsToCheck: Set<string>;
👍

2023-01-27 14:14 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/core/odp/odp_config.ts
> +    setA.forEach(item => {
Above L108, would a quick check for Set length equality help speed up a decision?

2023-01-27 14:14 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/core/odp/odp_config.ts
> +    let isEqual = true;
I like to go with a pessimistic/`false` initial value, imho.  Just a thought.

2023-01-27 14:14 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/core/odp/odp_config.ts
> +      if (!setB.has(item)) isEqual = false;
Do we want to `break` as soon as possible?

2023-01-27 14:14 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/shared_types.ts
> +  // odp manager
NIT: Do we want to shorten and remove comments?

2023-01-27 14:14 UTC, mikechu-optimizely commented on packages/optimizely-sdk/tests/odpManager.spec.ts
> +    // expect(manager.eventManager?.state).equal(STATE.RUNNING);
Is this assertion no longer valid/valuable?

2023-01-27 14:14 UTC, mikechu-optimizely commented on packages/optimizely-sdk/tests/odpSegmentApiManager.ts
> +    if (segments) expect(segments.size).toEqual(2);
Is this equivalent `expect(segments?.size).toEqual(2);`

2023-01-27 15:15 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/core/notification_center/notification_registry.ts
> +  private static _notificationCenters = new Map<string, NotificationCenter>();
Chatted w/Zeeshan about that last week and we came to the conclusion that we didn't due to the single-threaded synchronous nature of JS. Any thoughts on corner cases we may have missed?

2023-01-27 15:26 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/core/notification_center/notification_registry.ts
> +  public static getNotificationCenter(sdkKey?: string, logger?: LogHandler): NotificationCenter | null {
Right - I initially had considered making both non-nullable values but ended up following in the footsteps of the corresponding Java PR.

Either approach has its pros/cons. I'll make some changes based on the following thoughts:

- [ ] If `sdkKey` is not defined, we should also log an error indicating it's required.
- [ ] Since we use the default logger in case a logger isn't manually passed in, perhaps `logger: LogHandler = getLogger()` might work better? We'd also avoid having a union type of `LogHandler | null` as well.
- [ ] Also forgot to add a documentation comment on this function for that juicy tooltip - will have queue that up too.

2023-01-27 15:28 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/core/odp/odp_config.ts
> +    let isEqual = true;
I usually like to do that too, will reverse the conditional logic for this one.

2023-01-27 15:29 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/shared_types.ts
> +  // odp manager
True, for SDK Key and ODP Manager, for example, it's particularly redundant. Will remove those comments.

2023-01-27 15:31 UTC, opti-jnguyen commented on packages/optimizely-sdk/tests/odpManager.spec.ts
> +    // expect(manager.eventManager?.state).equal(STATE.RUNNING);
Thanks for the catch, was playing around with ODPManager-specific tests and this snuck into the PR by accident.

2023-01-27 15:38 UTC, opti-jnguyen commented on packages/optimizely-sdk/tests/odpSegmentApiManager.ts
> +    if (segments) expect(segments.size).toEqual(2);
Initially tried that and it complained - tried it again and now seems to work just fine. Switching it to `segments?.size` while it's not complaining anymore.

2023-01-27 16:11 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/core/odp/odp_config.ts
> +      if (!setB.has(item)) isEqual = false;
So because we're limited to ES5 (AFAIK) and can't use for..of on Sets, I went with this approach to sidestep some other approaches.

I'll update this with an additional conditional for Set size check and also show what it looks like with a clean-ish short-circuit using Array.from to transform the sets first. (Unfortunately short-circuit doesn't work in .every or .forEach :c)

2023-01-27 16:11 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/core/odp/odp_config.ts
> +    let isEqual = true;
Will remove this variable altogether for the short-circuit approach.

2023-01-27 17:48 UTC, jaeopt requested changes
A suggestion to clean up redundant sdkKey in 2 places.

2023-01-27 17:48 UTC, jaeopt commented on packages/optimizely-sdk/lib/core/odp/odp_manager.ts
> +    segmentsCache?: LRUCache<string, Set<string>>,
Also if more convenient, we can keep the <array> definition everywhere instead of <set> after we build non-redundant array in projectConfig. After that in sdk and odp server will use good array segments (non-redundant).

2023-01-27 17:48 UTC, jaeopt commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +      const sdkKey = this.projectConfigManager.getConfig()?.sdkKey;
We have sdkKey here (not indirectly from projectConfigManager) in line 132.
We can consider remove "getSdkKey()" new method from projectConfigManager and use a local value.
Also, we have to change "sdkKey" is mandatory (not null), which may be a breaking change in the release.

2023-01-27 17:48 UTC, jaeopt commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +      if (sdkKey != null) {
if sdkKey is null, then it should log as error.

2023-02-01 11:22 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +      const sdkKey = this.projectConfigManager.getConfig()?.sdkKey;
Thanks for the catch - swapped out .getConfig()?sdkKey references with local config.sdkKey usage.

Regarding changing `sdkKey` to be mandatory, this will definitely be a breaking change - especially since there's some nuances (for example, the Lite bundle does not expect `sdkKey` to begin with). Brainstorming on this one.

2023-02-01 11:24 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/core/odp/odp_manager.ts
> +    options: Set<OptimizelySegmentOption>
Swapped everything back over to Arrays and refactored previously approved "Set" related code to arrays as well for a handful of variables related to segments such as allSegments, segmentsCache, and options.

2023-02-01 11:26 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/core/notification_center/notification_registry.ts
> +      notificationCenter = this._notificationCenters.get(sdkKey) || null;
The .get() here potentially returns "undefined" despite the .has() check above. Changed function return from `| null` to `| undefined` as a workaround in order to incorporate this suggestion.

2023-02-01 11:27 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/core/odp/odp_config.ts
> +      if (!setB.has(item)) isEqual = false;
Refactored out Sets for Arrays as per Jae's comments below.

2023-02-02 06:18 UTC, msohailhussain commented on packages/optimizely-sdk/lib/core/odp/odp_config.ts
> +      this.segmentsToCheck.length == config._segmentsToCheck.length &&
we are checking this condition in `checkArrayEquality`

2023-02-02 06:19 UTC, msohailhussain commented on packages/optimizely-sdk/lib/core/odp/odp_config.ts
> +  private checkArrayEquality(arrayA: string[], arrayB: string[]): boolean {
what about to add in utils?

2023-02-02 18:44 UTC, msohailhussain reviewed
have some questions, we may discuss offline.

2023-02-02 18:44 UTC, msohailhussain commented on packages/optimizely-sdk/lib/modules/datafile-manager/httpPollingDatafileManager.ts
> +        NotificationRegistry.getNotificationCenter(this.sdkKey, logger)?.sendNotifications(NOTIFICATION_TYPES.OPTIMIZELY_CONFIG_UPDATE)
Can you please bring this first and before emitting.

2023-02-02 18:44 UTC, msohailhussain commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +    if (config.odpManager != null) {
All this logic should come-up after the readyPromise? How config.sdkKey will be `non-null` if the datafile is still being fetched.

2023-02-02 18:44 UTC, msohailhussain commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +      if (this.projectConfigManager.getConfig() != null) {
is this the blocking call ?

2023-02-06 19:42 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +    if (config.odpManager != null) {
Moving logic into Promise.all.

Also, as discussed, this should catch for both cases where a new Optimizely instance is provided either an SDK Key  or manually includes a datafile.

2023-02-06 19:42 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +      if (this.projectConfigManager.getConfig() != null) {
This will be resolved by the patch mentioned above.

2023-02-07 00:16 UTC, jaeopt requested changes
A few changes suggested.

2023-02-07 16:34 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/core/odp/odp_config.ts
> +      this.segmentsToCheck.length == config._segmentsToCheck.length &&
Thanks, forgot to push this change - should be resolved now.

2023-02-07 16:35 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/core/project_config/index.ts
>      })
Same comment as above

2023-02-07 16:35 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/core/project_config/index.tests.js
> +        assert.deepEqual(config.allSegments, ['odp-segment-1', 'odp-segment-2', 'odp-segment-3'])
Same comment as above

2023-02-07 17:05 UTC, jaeopt approved these changes
LGTM

2023-02-07 17:36 UTC, merged