feat: Added ODP Manager Implementation
optimizely/javascript-sdk pull request #797
Opened 2023-02-11 02:57 UTC by opti-jnguyen

## Summary
Added ODPManager Implementation which does the following.
1. Initializes and provides access to ODPEventManager and ODPSegmentManager.
2. Provides updated ODPConfig settings to event manager and segment manager.
3. Stops Event Manager when closed.
4. Uses VUID for browser flavor of javascript SDK.

## Test plan
1. Manually tested thoroughly
2. Added unit tests.

## Issues
[FSSDK-8452](https://jira.sso.episerver.net/browse/FSSDK-8452)

2023-02-13 16:56 UTC, mikechu-optimizely requested changes
I have a few small questions listed.

2023-02-13 16:56 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/core/odp/odp_config.ts
> +    if (apiHost) this._apiHost = apiHost;
Could we use `??` with your default `''` ?

2023-02-13 16:56 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/core/odp/odp_config.ts
> +      if (config.segmentsToCheck) this._segmentsToCheck = config.segmentsToCheck;
Could we use something like `this._apiKey = config?.apiKey ?? ''`

2023-02-13 16:56 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/core/odp/odp_manager.ts
> +  private _segmentManager!: OdpSegmentManager;
Is it okay to use the non-null assertion operator here on these fields?

I've not seen this done before.

2023-02-13 16:56 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/core/project_config/index.ts
>      })
NIT: I think we may need to add the `;` at least for consistency.

2023-02-13 16:56 UTC, mikechu-optimizely commented on packages/optimizely-sdk/tests/odpSegmentApiManager.spec.ts
> +    if (segments) expect(segments.length).toEqual(0);
Does `segments?.length` work here similarly to L152?

2023-02-13 16:56 UTC, mikechu-optimizely commented on packages/optimizely-sdk/tests/odpSegmentApiManager.spec.ts
> +    if (segments) expect(segments.length).toEqual(0);
Same question as on L165.

2023-02-13 16:56 UTC, mikechu-optimizely commented on packages/optimizely-sdk/tests/vuidManager.spec.ts
> +    expect(VuidManager.isVuid('123')).toBe(false);
This is much nicer.  😁 👍

2023-02-13 18:32 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/core/odp/odp_config.ts
> +      if (config.segmentsToCheck) this._segmentsToCheck = config.segmentsToCheck;
@mikechu-optimizely - Agree with using `??` in the constructor, however using `config?.apiKey ?? ''` wouldn't work if, say, we only wanted to update the `apiHost` but not the `apiKey`, right?

i.e. with `?? ''`

Before:
```
apiKey = 'key-a'
apiHost = 'host-a'
```

```
update({
  apiHost: 'host-b'
})
```

After:
```
apiKey = ''
apiHost='host-b'
```

This doesn't seem to be the desired behavior so I'd rather keep the current approach unless there's other reasoning, or perhaps we wanted to consider refactoring all fields to be mandatory.

2023-02-13 18:37 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/core/odp/odp_manager.ts
> +  private _segmentManager!: OdpSegmentManager;
@mikechu-optimizely - good question.

The usage of it here is to skirt around TypeScript complaining about the short circuit return in `if (!this.enabled)` never leading to `_segmentManager` and `_eventManager` being instantiated.

If we remove the non-null assertion, TypeScript demands instantiation which doesn't seem necessary if ODPManager is not enabled. Let me know if that makes sense or if you have further thoughts - thanks!

2023-02-13 18:40 UTC, opti-jnguyen commented on packages/optimizely-sdk/tests/odpSegmentApiManager.spec.ts
> +    if (segments) expect(segments.length).toEqual(0);
Yes, you're right. Will patch those - thanks!

2023-02-13 18:40 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/core/project_config/index.ts
>      })
Nice catch, forgot to run format save on that one.

2023-02-13 18:41 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/core/odp/odp_config.ts
> +      if (config.segmentsToCheck) this._segmentsToCheck = config.segmentsToCheck;
Good point.  We want to selectively update.

2023-02-13 18:43 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/core/odp/odp_manager.ts
> +  private _segmentManager!: OdpSegmentManager;
Can we use a union type?  `OdpSegmentManager | undefined`?   Just thinking "out loud".  We can DM over this too.

2023-02-13 22:40 UTC, jaeopt requested changes
Looks good! A few changes suggested.

2023-02-13 22:40 UTC, jaeopt commented on packages/optimizely-sdk/lib/plugins/odp_manager/index.browser.ts
> +      segmentsCache,
```suggestion
      segmentsCache || BrowerLRUCache(),
```
Or not sure if you have a plan to inject BrowserLRUCache() always.

2023-02-13 22:40 UTC, jaeopt commented on packages/optimizely-sdk/lib/plugins/odp_manager/index.node.ts
> +      segmentsCache,
```suggestion
      segmentsCache || ServerLRUCache,
```

2023-02-13 22:40 UTC, jaeopt commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +      }
What if config does not have odpManager? Is it coming in a separate PR?

2023-02-16 22:20 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/plugins/odp_manager/index.browser.ts
> +    setTimeout(() => {
Been trying to wrap my head around this for the past day or so - both manager eventManager should be ready at this point, but I've been having issues verifying that the eventApiManager's `sendEvent` is successfully called in the test suite, even when manually flushing the queue to trigger sendEvent.

Will push what I have for now and keep on working at getting these last tests to pass, I'm probably missing something obvious.

2023-02-16 22:52 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/plugins/odp_manager/index.browser.ts
> +
Note: Extending a method in TS forces the parameters to remain the same between parent and child classes.

In this case, `userKey` will be kept, though it won't be used since we'll know if the key should either be VUID or FS_USER_ID based on .isVuid. Thoughts on making this a new method instead of extending the parent?

2023-02-16 23:09 UTC, jaeopt commented on packages/optimizely-sdk/lib/plugins/odp_manager/index.browser.ts
> +
@opti-jnguyen I see that a separate API (userId) will be clean here, but OptimizelyUserContext should call different APIs for browser and node. I think we can keep the current (userKey, userId) though userKey is ignored here.

2023-02-16 23:12 UTC, jaeopt commented on packages/optimizely-sdk/lib/plugins/odp_manager/index.browser.ts
> +
@opti-jnguyen Alternatively, we can change (userKey, userId) to (userId) in the parent OdpManager and decide "userKey" inside the parent OdpManager using 'isVuid`.

2023-02-16 23:45 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +      }
@jaeopt - those changes will be reserved for https://jira.sso.episerver.net/browse/FSSDK-8475 which includes User Context and Optimizely Client changes.

2023-02-17 22:25 UTC, jaeopt requested changes
All changes look great. Some small changes suggested.

2023-02-17 22:25 UTC, jaeopt commented on packages/optimizely-sdk/lib/plugins/odp_manager/index.browser.ts
> +      super.identifyUser('', userId);
We should not send empty fsUserId string. Please confirm this empty fsUserId is filtered out from the final event.

2023-02-17 22:25 UTC, jaeopt commented on packages/optimizely-sdk/lib/plugins/odp_manager/index.browser.ts
> +      this.vuid = userId;
I think we should not override the vuid. Other modules can call this api with other vuid values (different from the device vuid) as well (not likely, but possible in future).

2023-02-21 18:36 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/core/odp/odp_manager.ts
> +      this.eventManager.updateSettings(this.odpConfig);
Went back and changed line 97 to match instead to acknowledge the `private` nature of event manager's ODP Config.

Refactored Segment Manager's ODP Config to be a `private` variable instead.

2023-02-21 22:16 UTC, jaeopt requested changes
A couple of more suggestions.

2023-02-21 22:16 UTC, jaeopt commented on packages/optimizely-sdk/lib/core/odp/odp_manager.ts
> +    if (VuidManager.isVuid(userId)) {
I like this - "isVuid" check in odp_manager (instead of index.browser.ts), so we can remove most extra logic from index.browser.ts and index.node.ts.
I suggest to do the same thing for "identifyUser(userId)" (remove "vuid" from parameters) and isVuid differentiation here. It'll help to make it clean and remove extra codes from index.browser.ts and index.node.ts.

2023-02-22 01:33 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/plugins/odp_manager/index.browser.ts
> +      this.vuid = fsUserId;
Makes sense, will do!

2023-02-22 01:34 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/core/odp/odp_manager.ts
> +    if (VuidManager.isVuid(userId)) {
Agreed, will make the delegation of VUID check consistent - thanks!

2023-02-22 22:49 UTC, jaeopt approved these changes
LGTM

2023-02-24 17:49 UTC, opti-jnguyen commented
Merging without passing FSC for velocity, will address at a later point.

2023-02-24 17:49 UTC, merged