[FSSDK-8475] ODP Integration for Optimizely Client and User Context (Browser)
optimizely/javascript-sdk pull request #799
Opened 2023-03-01 13:32 UTC by opti-jnguyen

## Summary
- This PR integrates ODP with the Optimizely Client and User Context classes, allowing users to interface with ODP through the browser variant of the JavaScript Optimizely SDK.
- This PR includes additional tweaks and revisions to past naming and styling choices and builds on top of some previous features, such as including a localStorage fallback mechanism for non-browser environments.

## Test plan
- Manual testing, ensuring all previous tests also pass as well as new unit tests.
- Fix all tests that break as a result of these new changes.
- Tests in-flight will be resolved and additional tests will be added through the review process and beyond.

## Issues
- [FSSDK-8475](https://jira.sso.episerver.net/browse/FSSDK-8475)

2023-03-01 13:35 UTC, opti-jnguyen commented
Note: Putting this out for fast-track review and iteration despite some gaps in flight (such as TODO tests).

@jaeopt / @mikechu-optimizely, if you could give this a look and an initial round of review, it'd be much appreciated - thank you in advance!

2023-03-01 16:57 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/index.browser.tests.js
> +    describe('#odp', () => {
Curious: Are you indicating that the following block is testing the private ODP?

2023-03-01 16:57 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/optimizely_user_context/index.tests.js
> +        sinon.assert.calledOnce(stubLogHandler.log); // Called once in the case of User Context logging an error when failing to run identifyUser
Thanks for the // explanation comment, do we need to leave it in the codebase?

2023-03-01 16:57 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/optimizely_user_context/index.ts
> +    this.identifyUser();
Are we providing an optional param like `shouldIdentifyUser` https://github.com/optimizely/csharp-sdk/blob/master/OptimizelySDK/OptimizelyUserContext.cs#L79 & https://github.com/optimizely/java-sdk/blob/master/core-api/src/main/java/com/optimizely/ab/OptimizelyUserContext.java#L68

2023-03-01 16:57 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/optimizely_user_context/index.ts
> +    this.identifyUser();
I generally like to keep constructors without side effects.

2023-03-01 16:57 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/shared_types.ts
> +  odpServiceConfig?: OdpServiceConfig; // Configuration preferences for default OdpManager
If we're not using OdpServiceConfig...🤔

2023-03-01 16:57 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/utils/local_storage/tryLocalStorage.ts
> +  return typeof window !== 'undefined' ? window && window.localStorage && browserCallback(window.localStorage) : nonBrowserCallback();
Maybe? 🤔 
`return typeof window !== 'undefined' ? browserCallback(window?.localStorage) : nonBrowserCallback();`

2023-03-01 16:57 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/utils/local_storage/tryLocalStorage.ts
> +  return typeof window !== 'undefined' ? window && window.localStorage && browserCallback(window.localStorage) : nonBrowserCallback();
I thought we had an enum somewhere that indicated what execution context we were in.  🤷

2023-03-01 18:51 UTC, jaeopt requested changes
A good start!
Reviewed at the top level only and added a few major suggestions.

2023-03-01 18:51 UTC, jaeopt commented on packages/optimizely-sdk/lib/shared_types.ts
> +  fetchQualifiedSegments(userId: string, options: OptimizelySegmentOption[]): Promise<string[] | null>;
It looks like this interface for public customers. `identifyUser` and `fetchQualifiedSegments` will be called from OptimizelyUserContext only.

2023-03-02 18:28 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/index.browser.tests.js
> +    describe('#odp', () => {
No, the `#` is not meant to indicate that the block is testing the private ODP.

The text is placeholder based on another suite that included `#` in front of features such as `activate`, `decide`, etc. in the `index.tests.js` file in the `/optimizely` folder.

Can change to be more descriptive - I assume it was previously used to help group similar tests for a particular feature.

2023-03-02 18:30 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/optimizely_user_context/index.tests.js
> +        sinon.assert.calledOnce(stubLogHandler.log); // Called once in the case of User Context logging an error when failing to run identifyUser
True, don't really see why we need it outside of maybe making sure it doesn't get called more than once. Will remove these for now.

2023-03-02 18:32 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/utils/local_storage/tryLocalStorage.ts
> +  return typeof window !== 'undefined' ? window && window.localStorage && browserCallback(window.localStorage) : nonBrowserCallback();
I mostly added this in to help with test cases that were failing as well as to provide some rails to safeguard in future implementations for React Native, etc.

2023-03-02 18:37 UTC, jaeopt commented on packages/optimizely-sdk/lib/optimizely_user_context/index.ts
> +  constructor({ optimizely, userId, attributes, qualifiedSegments }: OptimizelyUserContextConfig) {
@opti-jnguyen it looks like it's added for cloning support in java. It can be removed here since you already have clone solution.

2023-03-02 18:45 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/utils/local_storage/tryLocalStorage.ts
> +  return typeof window !== 'undefined' ? window && window.localStorage && browserCallback(window.localStorage) : nonBrowserCallback();
> return typeof window !== 'undefined' ? browserCallback(window?.localStorage) : nonBrowserCallback();

Hmm, I originally was following another instance of local storage check which utilized the former logic.

The suggested code returns a potentially null `localStorage` value to `browserCallback(localStorage)` which has the caveat of having to be caught by the calling function which has its pros and cons.

I think that ideally, tryWithLocalStorage's `browserCallback` should always guarantee a valid window.localStorage returned to the callback, but can imagine cases with the current implementation where that might break.

Will go ahead and implement your suggested approach for now and potentially revisit later.

2023-03-02 18:48 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/optimizely_user_context/index.ts
> +    this.identifyUser();
Agree on constructors without side effects. Regarding `shouldIdentifyUser`, I see that's been pretty much standardized at this point - will add.

2023-03-02 20:10 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/optimizely_user_context/index.ts
> +      logger.error(ERROR_MESSAGES.ODP_IDENTIFY_USER_FAILED_USER_CONTEXT_INITIALIZATION);
The try/catch here is mostly just a temporary stopgap to help ~320 test cases pass that fail otherwise. 

![image](https://user-images.githubusercontent.com/97256112/222541096-fc1a47e7-e82f-4a17-9dc5-7671ceb811bf.png)

Still looking into why this is the case, but will keep the try/catch here in the meantime.

2023-03-02 20:22 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/utils/lru_cache/browser_lru_cache.ts
> +      timeout: config?.timeout || BrowserLRUCacheConfig.DEFAULT_TIMEOUT_SECS * 1000,
Will change - generally speaking, the server changes I will be prioritizing less as those will generally be covered in the Node-specific tickets.

2023-03-02 20:24 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/optimizely_user_context/index.ts
> +  }
@jaeopt - this functionality was already added in a previous PR and thus doesn't show as additions in this PR. Here's the relevant code from the same file:

```

  public get qualifiedSegments(): string[] {
    return this._qualifiedSegments;
  }

  public set qualifiedSegments(qualifiedSegments: string[]) {
    this._qualifiedSegments = [...qualifiedSegments];
  }

```

2023-03-03 19:58 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/core/odp/odp_service_config.ts
> +export class OdpServiceConfig {
Thought more about this and decided to remove it in my round 2 iteration in favor of using odpManager instead.

Main reason for this is due to needing a totally different OdpManager anyway in the case of each variant (i.e. BrowserOdpManager implements VUID) and odpServiceConfig becomes less optimal as a result.

Will discuss further with Jae.

2023-03-03 19:59 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/optimizely_user_context/index.ts
> +      logger.error(ERROR_MESSAGES.ODP_IDENTIFY_USER_FAILED_USER_CONTEXT_INITIALIZATION);
Resolved in recent commit

2023-03-03 20:02 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +  /**
getVuid() added in a browser-specific implementation of Optimizely in recent commit, introducing new BrowserOptimizely.

2023-03-03 20:03 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/shared_types.ts
> +  odpServiceConfig?: OdpServiceConfig; // Configuration preferences for default OdpManager
Due to BrowserOdpManager being a different implementation that's injected as the OdpManager, decided to remove `odpServiceConfig` in favor of `odpManager` in recent commit.

2023-03-03 20:12 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +  }
Took a shot at this in a recent commit, let me know what you think.

Due to being unable to have multiple method signatures, made a new `createUserContext` in the new `BrowserOptimizely` that overrides the parent with optional `userId` and `attributes` fields and tries to populate with `vuid` if no `userId` is passed in.

2023-03-03 21:15 UTC, jaeopt requested changes
A few more suggestions. Let's discuss about top-level interface.

2023-03-03 22:04 UTC, mikechu-optimizely requested changes

2023-03-03 22:04 UTC, mikechu-optimizely commented on packages/optimizely-sdk/lib/plugins/key_value_cache/browserAsyncStorageCache.ts
>   * Copyright 2022, Optimizely
NIT: 2023?

2023-03-03 22:06 UTC, mikechu-optimizely approved these changes
LGTM, but I'll continue to help refine if more commits are added.

2023-03-03 22:25 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/optimizely_user_context/index.ts
> +  shouldIdentifyUser?: boolean;
Was considering backwards compatibility, though the default parameter value would work as well. Going to address this feedback along w/Jae's relevant feedback regarding flipping the default boolean value logic.

2023-03-03 22:28 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/optimizely_user_context/index.ts
> +    if (shouldIdentifyUser == null || shouldIdentifyUser) {
Originally included `shouldIdentifyUser == null` to run the default behavior of identifying users in legacy cases where `shouldIdentifyUser` is not defined. Will be reworking this with Jae's relevant feedback as well and likely go with your suggestion.

2023-03-03 22:30 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/shared_types.ts
> -  fetchQualifiedSegments(userId: string, options: OptimizelySegmentOption[]): Promise<string[] | null>;
True, though BrowserOptimizely is the only instance of Optimizely which will include those methods. May consider making a `BrowserClient` that extends the `Client` interface and adding it there instead.

2023-03-03 22:33 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/optimizely/index.ts
> +      shouldIdentifyUser: false,
Will change to `true` by default.

2023-03-03 22:44 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/optimizely/index.ts
>    public identifyUser(userId: string): void {
Removed public from User Context - keeping it in Optimizely for now as I'm not sure if there's any way to do internal access modifier on this method while keeping it accessible to User Context.

2023-03-03 23:02 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/index.browser.ts
> +      odpManager: config.odpManager || new BrowserOdpManager({ disable: false, logger }),
Resolved via call - thanks Jae!

2023-03-09 00:13 UTC, jaeopt requested changes
All changes look good! 
One remaining concern is to support all options for ODPManager.createInstance. See my comments and let's discuss.

2023-03-09 00:13 UTC, jaeopt commented on packages/optimizely-sdk/lib/plugins/odp_manager/index.browser.ts
> +      logger,
I can add these extra options in a separate PR. I do not see a clean solution to support `eventFlushInterval` and future options.

2023-03-09 03:22 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/plugins/odp_manager/index.browser.ts
> +      logger,
@jaeopt - thanks! Yeah, it's looking like it might get a bit clunky for those additions and beyond. Let's chat tomorrow.

2023-03-09 19:45 UTC, jaeopt commented on packages/optimizely-sdk/lib/plugins/odp_manager/index.browser.ts
> +      logger,
@opti-jnguyen as discussed, let's move this refactoring to a separate PR. I'll approve this as is.

2023-03-09 19:46 UTC, jaeopt approved these changes
We'll move remaining work for refactoring discussed into a separate PR.
Approved as is.

2023-03-09 19:54 UTC, opti-jnguyen commented
Merging without FSC passing - will work on failing FSC tests at a later date.

2023-03-09 19:55 UTC, merged