Add various OdpOptions for more granular configurations for odp
optimizely/javascript-sdk pull request #805
Opened 2023-03-17 18:38 UTC by opti-jnguyen

## Summary
- Add additional configuration options in `OdpOptions` to support granular configuration of:
  - `segmentsApiTimeout`
  - `segmentsRequestHandler`
  - `eventApiTimeout`
  - `eventFlushInterval`
  - `eventQueueSize`
  - `eventRequestHandler`

## Test plan
- TODO: Test permutations of new `OdpOptions` passed into the `createBrowserOdpManager()` method.
- All existing tests should pass

## Issues
- [FSSDK-8986](https://jira.sso.episerver.net/browse/FSSDK-8986)

Will unblock:
- [FSSDK-8793](https://jira.sso.episerver.net/browse/FSSDK-8793)
- [FSSDK-8690](https://jira.sso.episerver.net/browse/FSSDK-8690)

2023-03-20 21:56 UTC, jaeopt requested changes
It looks good, with full flexibility in config supported.  A concern is that I see redundant event and segment manager instantiations in multiple levels. Let's discuss about options to clean them up.

2023-03-20 21:56 UTC, jaeopt commented on packages/optimizely-sdk/lib/plugins/odp_manager/index.browser.ts
> +        new BrowserLRUCache<string, string[]>(),
```suggestion
        odpOptions?.segmentsCache || new BrowserLRUCache<string, string[]>(maxSize: odpOptions.segmentsCacheSize,
          timeout: odpOptions.segmentsCacheTimeout,),
```

It's possible they want to config Cache + ApiTimeout.

2023-03-20 21:56 UTC, jaeopt commented on packages/optimizely-sdk/lib/plugins/odp_manager/index.browser.ts
> +        new OdpConfig(),
This dummy odpConfig injection which will be overwritten on OdpManager constructor sounds odd.
We can consider to remove this parameter and instead, change to always call "updateSettings(opdConfig)" when odpEventManager and odpSegmentManager are instantiated.

2023-03-20 21:56 UTC, jaeopt commented on packages/optimizely-sdk/lib/plugins/odp_manager/index.browser.ts
> +      browserEventManager = new OdpEventManager({
We repeat this same EventManager instantiation in OdpManager as well, which looks redundant. Line 58 and 62 passing `RequestHandler` and `cache` also look redundant. We can consider passing `options` to `OdpManager` where we build all `OdpEventManager` and `OdpSegmentManager` in there. Let's discuss about other options.

2023-03-20 21:56 UTC, jaeopt commented on packages/optimizely-sdk/lib/plugins/odp_manager/index.browser.ts
> +        queueSize: odpOptions.eventQueueSize,
These size and timeout are platform dependent (browser or node). Do we determine their default values (when not defined in odpOptions) in the `OdpEventManager`, depending on the target platform? If so, the value of this separate `browser-odp-manger` here is not that significant.

2023-03-22 18:47 UTC, jaeopt requested changes
Looks much cleaner! A few more suggestions.

2023-03-22 18:47 UTC, jaeopt commented on packages/optimizely-sdk/lib/index.browser.ts
> +      odpManager: new BrowserOdpManager({ disable: true, logger, odpOptions: config.odpOptions }),
Why disable is true by default?  It is a part of odpOptions. Do we need this separate parameter?

2023-03-22 18:47 UTC, jaeopt commented on packages/optimizely-sdk/lib/core/odp/odp_manager.ts
>      this.enabled = !disable;
Can `odpOptions.disable` override this?  Still wondering if we need this separate `disable` parameter.

2023-03-22 18:47 UTC, jaeopt commented on packages/optimizely-sdk/lib/core/odp/odp_manager.ts
> +          new BrowserLRUCache<string, string[]>({
If we have `BrowserLRUCache` here at the common odp_manager, how can we support the node version?
We may use `LRUCache` (instead of `BrowserLRUCache`) since it can be different from the node version only by the size and timeout. We can feed target-specific size and timeout form `browser_odp_manager`.

2023-03-22 18:47 UTC, jaeopt commented on packages/optimizely-sdk/lib/core/odp/odp_manager.ts
> +        new OdpSegmentApiManager(odpOptions?.segmentsRequestHandler || defaultRequestHandler, this.logger)
I do not see support for `odpOptions.segmentApiTimeout`.

2023-03-22 18:47 UTC, jaeopt commented on packages/optimizely-sdk/lib/core/odp/odp_manager.ts
> +        customEventRequestHandler = new BrowserRequestHandler(this.logger, odpOptions.eventApiTimeout);
Same here. It's awkward to see `Browser-xxx` at this level. We can push this custom requesthandler to browser-odp-manager.

2023-03-22 19:08 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/core/odp/odp_manager.ts
>      this.enabled = !disable;
True, the disable param is redundant - will look into moving all disable logic into `odpOptions`.

2023-03-22 19:11 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/core/odp/odp_manager.ts
> +          new BrowserLRUCache<string, string[]>({
@jaeopt - I defaulted to `BrowserLRUCache` for now as LRUCache has no defaults for size and timeout.

Two possible approaches:
1. Do something similar to `defaultRequestHandler` and have a `defaultLRUCache` passed down from the implementation level as a required field.
2. Instantiate with LRUCache and consider setting the defaults to be (minimum?) values.

2023-03-22 19:13 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/core/odp/odp_manager.ts
> +        new OdpSegmentApiManager(odpOptions?.segmentsRequestHandler || defaultRequestHandler, this.logger)
Oops - let me add that in with the same logic as the custom Event Request Handler.

2023-03-22 20:44 UTC, jaeopt requested changes
Looks good! A couple of suggestions.

2023-03-22 20:44 UTC, jaeopt commented on packages/optimizely-sdk/lib/plugins/odp_manager/index.browser.ts
> +      eventRequestHandler: new BrowserRequestHandler(browserLogger),
```suggestion
      eventRequestHandler: customEventRequestHandler || new BrowserRequestHandler(browserLogger),
```

2023-03-22 20:44 UTC, jaeopt commented on packages/optimizely-sdk/lib/plugins/odp_manager/index.browser.ts
> +      eventRequestHandler: new BrowserRequestHandler(browserLogger),
Do we have all test cases covering different config options?  It won't be covered by FSC, so please make sure we have full coverage of config combination testing.

2023-03-22 20:44 UTC, jaeopt commented on packages/optimizely-sdk/lib/plugins/odp_manager/index.browser.ts
> +        new BrowserLRUCache<string, string[]>({
We do not have to fix for now, but I suggest to remove `BrowserLRUCache` and `NodeLRUCache` since they're identical in implementation with size/timeout injected.

2023-03-22 23:54 UTC, opti-jnguyen commented on packages/optimizely-sdk/lib/plugins/odp_manager/index.browser.ts
> +        new BrowserLRUCache<string, string[]>({
Agreed, perhaps the variant-specific default values can be handled by the variant-specific OdpManager implementations in the future instead.

2023-03-23 16:17 UTC, jaeopt approved these changes
LGTM!

2023-03-23 16:17 UTC, jaeopt commented on packages/optimizely-sdk/lib/core/odp/odp_event_manager.ts
> +      // TODO: Consider refactoring to use typeof process and combine w/above line
Alternatively, we can later change to push variant size down from the browser-odp-manager level

2023-03-23 16:44 UTC, merged