refactor: Refactored Odp Code to get rid of platform specific checks
optimizely/javascript-sdk pull request #813
Opened 2023-04-07 02:03 UTC by zashraf1985

## Summary
Refactored Odp Code to get rid of platform specific checks.

## Test plan
Not tested at all. Relying on John to test and fix unit tests if needed

## Issues

2023-04-07 17:13 UTC, jaeopt requested changes
Looks great! I see some platform dependent logic for segmentManager as well. If we can have consistent structure for both segmentManager and eventManager, it may look better.

2023-04-07 17:13 UTC, jaeopt commented on packages/optimizely-sdk/lib/plugins/odp_manager/index.node.ts
> +        apiManager: new NodeOdpEventApiManager(nodeRequestHandler, this.logger),
override with `customRequestHandler` if given.

2023-04-10 18:04 UTC, opti-jnguyen commented
@jaeopt - went ahead and resolved tests and finished splitting off odpmanager responsibilities into variant-specific implementations.

2023-04-10 20:13 UTC, jaeopt approved these changes
LGTM

2023-04-10 20:25 UTC, jaeopt commented on packages/optimizely-sdk/lib/index.node.ts
> -    }
I see this is for logx events only. No need to change :)

2023-04-10 21:09 UTC, merged