[FSSDK-8983] Specify package entry point using exports field
optimizely/javascript-sdk pull request #836
Opened 2023-07-21 13:34 UTC by raju-opti

## Summary
- specified package entry points  using the modern [exports field in package.json](https://nodejs.org/api/packages.html#package-entry-points)
- added an export for lite bundle. lite bundle can be now imported using `import optimizely from '@optimizely/optimizely-sdk/lite`

## Test plan
- all existing tests should pass

## Issues
- FSSDK-8983

2023-07-21 14:03 UTC, mikechu-optimizely requested changes
Just a couple of items/thoughts.

2023-07-21 14:03 UTC, mikechu-optimizely commented on packages/optimizely-sdk/package.json
Please update the Description > Tests section to include how you tested the imports (like with "lite") and the results of those test (did the prod bundle include just the expected dist files)

2023-07-21 14:03 UTC, mikechu-optimizely commented on packages/optimizely-sdk/package.json
> +      "import": "./dist/optimizely.lite.es.min.js",
I love that we can `import` specific part of the dist.  That really should help bundlers with shaking out unneeded code paths & files.

2023-07-21 14:03 UTC, mikechu-optimizely commented
@zashraf1985 Can you do a light review when you get a chance?

2023-07-21 14:08 UTC, raju-opti commented on packages/optimizely-sdk/package.json
> +    },
Probably. We should at some point clean up the public api of the package. Currently kept these cause someone might be importing them.

2023-07-21 14:13 UTC, raju-opti commented on packages/optimizely-sdk/package.json
updated

2023-07-21 16:38 UTC, zashraf1985 approved these changes
Generally looks great! But i have no idea about this new feature so i would recommend thorough testing using all possible known variants of user applications / supported JS versions before moving forward.

2023-07-21 18:16 UTC, mikechu-optimizely approved these changes
If Zeeshan says ok 😁

Be sure all checks are passing

2023-12-29 15:21 UTC, mikechu-optimizely commented
@raju-opti is this a good time to bring this PR into the code before AAT release?

2024-01-03 17:08 UTC, raju-opti commented
> @raju-opti is this a good time to bring this PR into the code before AAT release?

Yeah, I think it is!

2024-01-18 21:16 UTC, merged