FSSDK-8503: Update Github Issue Templates.
optimizely/javascript-sdk pull request #840
Opened 2023-07-31 17:21 UTC by yasirfolio3

## Summary
- Update Github Issue Templates

## Issues
- [8503](https://jira.sso.episerver.net/browse/FSSDK-8503)

2023-07-31 17:41 UTC, mikechu-optimizely approved these changes
LGTM

2023-08-01 18:23 UTC, mikechu-optimizely requested changes
Some suggestions.

2023-08-01 18:23 UTC, mikechu-optimizely commented on .github/ISSUE_TEMPLATE/BUG-REPORT.yml
> +labels: ["Bug", "Needs Triage"]
```suggestion
labels: ["bug", "needs-triage"]
```

2023-08-01 18:23 UTC, mikechu-optimizely commented on .github/ISSUE_TEMPLATE/ENHANCEMENT.yml
> +name: "Enhancement"
```suggestion
name: ✨Enhancement
```

2023-08-01 18:23 UTC, mikechu-optimizely commented on .github/ISSUE_TEMPLATE/config.yml
> +  - name: Feature Requests
```suggestion
  - name:  💡Feature Requests
```

2023-08-01 20:22 UTC, jaeopt approved these changes
LGTM

2023-08-01 20:37 UTC, merged