add sendBeacon event dispatcher support
optimizely/javascript-sdk pull request #866
Opened 2023-09-26 20:10 UTC by raju-opti

2023-09-26 21:37 UTC, jaeopt requested changes
Looks good! A couple of clarifications.

2023-09-26 21:37 UTC, jaeopt commented on lib/index.browser.ts
> +      closingDispatcher,
Wondering if we see any possible side-effect and need to make this configurable.

2023-09-26 21:37 UTC, jaeopt commented on lib/modules/event_processor/eventProcessor.ts
> +): EventQueue<ProcessableEvent> {
Don't we need the same beacon support for ODPEventDispatcher as well for consistency?

2023-09-27 10:18 UTC, raju-opti commented on lib/modules/event_processor/eventProcessor.ts
> +): EventQueue<ProcessableEvent> {
Currently, ODPEventManager for browser does not queue any events, it sends them immediately, so we don't have a similar use case.

2023-09-27 10:21 UTC, raju-opti commented on lib/index.browser.ts
> +      closingDispatcher,
Yeah, probably should make it configurable as well.

2023-09-27 15:36 UTC, jaeopt commented on lib/modules/event_processor/eventProcessor.ts
> +): EventQueue<ProcessableEvent> {
what is expected if we have back-2-back ODP events? 2nd one is discarded or blocking?

2023-09-27 19:08 UTC, raju-opti commented on lib/modules/event_processor/eventProcessor.ts
> +): EventQueue<ProcessableEvent> {
@jaeopt in that case both event will be sent immediately asynchronously, without blocking or waiting.

2023-09-29 14:50 UTC, alexparish commented
This is really great. 

In order to synchronise activations to a data platform I have created a custom event dispatcher that I pass to `createInstance`. Ultimately this custom event dispatcher calls `eventDispatcher.dispatchEvent(eventObject, callback)` with `eventDispatcher` imported from the SDK package.

Will this pull request support my use case or will I have to integrate `sendBeaconDispatcher` into my custom event dispatcher?

2023-09-29 19:40 UTC, raju-opti commented
> This is great, thanks for implementing the Beacon API.
> 
> In order to synchronise activations to a data platform I am using a custom event dispatcher that I pass to `createInstance`. Ultimately this custom event dispatcher calls `eventDispatcher.dispatchEvent(eventObject, callback)` with `eventDispatcher` imported from the SDK package.
> 
> Will people like myself using custom event dispatchers need to manually integrate`sendBeaconDispatcher`?

@alexparish yes, you will need to wrap the `sendBeaconEventDispatcher` similarly and pass it as `closingEventDispatcher` option to `createInstance`.

2023-09-29 20:08 UTC, mikechu-optimizely commented
@raju-opti and I are finishing our manual e2e acceptance testing (bug bashing) after the code review....

2023-09-29 21:08 UTC, mikechu-optimizely reviewed
Some questions

2023-10-02 11:38 UTC, raju-opti commented on lib/modules/event_processor/eventQueue.ts
> +    closingSink?: EventQueueSink<K>;
This is just a field in an object, so order should not matter.

2023-10-02 11:40 UTC, raju-opti commented on lib/modules/event_processor/v1/v1EventProcessor.ts
> +    closingDispatcher?: EventDispatcher
Order of optional arguments to a function matters in TS, they must come after all mandatory params. However, here closingDispatcher is a field of an object, not a parameter of the constructor itself. So order should not matter. And as it is an optional field, the change to API is non-breaking.

2023-10-02 11:53 UTC, raju-opti commented on lib/plugins/event_dispatcher/send_beacon_dispatcher.ts
> +  const url: string = eventObj.url;
updated

2023-10-02 12:54 UTC, mikechu-optimizely approved these changes
LGTM. 👍   Thanks.

2023-10-02 12:54 UTC, mikechu-optimizely commented
@jaeopt, Are you good with this PR?

2023-10-02 15:49 UTC, jaeopt requested changes
Changes look good to me! 
With this change, sendBeacon is not default any more, so clients should instantiate the custom handler to use it. Other option is to use it as the default and they can turn it off if they do not like it. WDYT?

2023-10-02 15:55 UTC, raju-opti commented
> Changes look good to me! With this change, sendBeacon is not default any more, so clients should instantiate the custom handler to use it. Other option is to use it as the default and they can turn it off if they do not like it. WDYT?

@jaeopt As this PR introduces option to use a separate dispatcher when closing the instance, this would break users using custom event dispatcher if used by default when closing, that's why we have to keep it optional.

2023-10-02 16:09 UTC, alexparish commented
Is there a reason why events cannot always be sent using `sendBeacon` in the browser? It would simplify the change, for example `closingEventDispatcher` would not need to be specified when using `createInstance`,.

2023-10-02 16:17 UTC, raju-opti commented
> Is there a reason why events cannot always be sent using `sendBeacon` in the browser? It would simplify the change, for example `closingEventDispatcher` would not need to be specified when calling `createInstance`.

Yes, sendBeacon does not provide any way of checking the HTTP response status. By default, we will want to check the response status and retry in case of 5xx status.

2023-10-04 12:32 UTC, mikechu-optimizely commented
Last commit, still LGTM.

2023-10-04 22:37 UTC, jaeopt approved these changes
LGTM

2023-10-05 19:35 UTC, merged

2023-10-05 19:55 UTC, mikechu-optimizely commented
Woot 🎉