[FSSDK-9607] add pixelUrl to OdpConfig
optimizely/javascript-sdk pull request #888
Opened 2024-01-12 19:09 UTC by andrewleap-optimizely

## Summary
- Changed the ODP pixelUrl to be read from the datafile instead of being hard coded in the SDK.

## Ticket
[FSSDK-9607](https://jira.sso.episerver.net/browse/FSSDK-9607)

2024-01-16 21:54 UTC, mikechu-optimizely commented on lib/index.browser.tests.js
> +        const pixelApiEndpoint = `${pixelHost}/v2/zaius.gif`;
Are we getting the full pixel URL (all the way to `zaius.gif`) from the datafile or just the host?  This test made me question.  

I mean I'm in favor of getting the FULL host + path + resource from datafile letting the server control this.

2024-01-16 22:19 UTC, andrewleap-optimizely commented on lib/index.browser.tests.js
> +        const pixelApiEndpoint = `${pixelHost}/v2/zaius.gif`;
Currently we're just getting the host- I'm not opposed to making that change though, can't think of any good reason not to...

2024-01-17 15:11 UTC, mikechu-optimizely approved these changes
Just some thoughts but nothing show-stopping.  LGTM.

2024-01-17 15:11 UTC, mikechu-optimizely commented on lib/core/project_config/project_config_schema.ts
>            }
NIT: Cool if we add a trailing `,` ? Maybe it's a linter prob 🤷

2024-01-17 15:11 UTC, mikechu-optimizely commented on lib/index.browser.tests.js
> +        const pixelApiEndpoint = `${pixelHost}/v2/zaius.gif`;
If we're only getting & using the pixelHost, is it worth renaming vars to pixelHost elsewhere? Just 🤔

2024-01-17 15:11 UTC, mikechu-optimizely commented on lib/plugins/odp/event_api_manager/index.browser.ts
> +    const pixelUrl = this.odpConfig.pixelUrl;
NIT: Yeah maybe this should be `pixelHost`  🤷

2024-01-17 15:35 UTC, raju-opti requested changes

2024-01-17 15:35 UTC, raju-opti commented on lib/plugins/odp/event_api_manager/index.browser.ts
> +    const pixelApiEndpoint = new URL(pixelApiPath, pixelUrl).href;
Is it currently possible to have a datafile that has odp apiHost but not the pixelUrl? (for example: some project whose datafile was generated a long time ago and not updated since? or someone who are are calling createInstance with a datafile generated before adding pixelUrl?). In that case, should we check if pixelUrl exists, and if not, fallback to `apiHost.replace('api', 'jumbe'))`?

2024-01-17 15:51 UTC, andrewleap-optimizely commented on lib/plugins/odp/event_api_manager/index.browser.ts
> +    const pixelUrl = this.odpConfig.pixelUrl;
You know I don't disagree, however it seems like the real fix is to make the change in the datafile.

Since we don't modify the value from the datafile, then it seems like the least confusing thing is to match the name from the datafile.

2024-01-17 16:37 UTC, andrewleap-optimizely commented on lib/plugins/odp/event_api_manager/index.browser.ts
> +    const pixelApiEndpoint = new URL(pixelApiPath, pixelUrl).href;
Good callout. This would have to be a beta customer- I just went through and checked all the beta datafiles and we're all good!

2024-01-17 16:55 UTC, raju-opti approved these changes
LGTM

2024-01-17 17:35 UTC, merged