Raju/odp refac
optimizely/javascript-sdk pull request #920
Opened 2024-04-02 16:23 UTC by raju-opti

## Summary
- The "what"; a concise description of each logical change
- Another change

The "why", or other context.

## Test plan

## Issues
- "THING-1234" or "Fixes #123"

2024-04-04 11:39 UTC, muzahidul-opti commented on lib/core/odp/odp_manager.ts
> +    console.log('foo is ', foo);
I think renaming `foo` to `fetchedSegtments` would improve the code readability.
 ```
 const fetchedSegments = await this.segmentManager.fetchQualifiedSegments(ODP_USER_KEY.FS_USER_ID, userId, options);
console.log('fetchedSegment is ', fetchedSegments);
return fetchedSegments;
```

2024-04-04 11:42 UTC, muzahidul-opti commented on lib/core/odp/odp_segment_manager.ts
> +    // if (!odpApiKey || !odpApiHost) {
Maybe we can remove the boiler code.

2024-04-04 12:00 UTC, raju-opti commented on lib/core/odp/odp_manager.ts
> +    console.log('foo is ', foo);
My bad, this was intended for debug purposes. removed

2024-04-04 12:07 UTC, raju-opti commented on lib/core/odp/odp_event_manager.ts
>    private processQueue(shouldFlush = false): void {
processQueue is synchronous, but it is called asynchronously when timeout occurs during flush. If a batch becomes full when sendEvent() is called, then it is called synchronously. But e. And the apiManger eventApiManager.sendEvents is called asynchronously (https://github.com/optimizely/javascript-sdk/blob/8cbb767abf12e38f971d7c177eef53797de35fad/lib/core/odp/odp_event_manager.ts#L395). Also, the eventApiManager.sendEvents itself is asynchronous. So the event loop will not be blocked.

2024-04-04 15:40 UTC, mikechu-optimizely approved these changes
That was a long one phew. Thanks for putting all your thoughts in. 

👇 are just some non-show stopping, thoughts/suggestions.

2024-04-04 15:40 UTC, mikechu-optimizely commented on lib/core/odp/odp_config.ts
> +  readonly apiHost: string;
NIT: Is it good to add the `public` access modifier for clarity?

2024-04-04 15:40 UTC, mikechu-optimizely commented on lib/core/odp/odp_config.ts
> +export const odpIntegrationEquals = (config1: OdpIntegrationConfig, config2: OdpIntegrationConfig): boolean => {
NIT
```suggestion
export const odpIntegrationAreEqual = (config1: OdpIntegrationConfig, config2: OdpIntegrationConfig): boolean => {
```

2024-04-04 15:40 UTC, mikechu-optimizely commented on lib/core/odp/odp_event_api_manager.ts
> +  async sendEvents(odpConfig: OdpConfig, events: OdpEvent[]): Promise<boolean> {
Maybe adding `public` becomes too verbose. Bah. Nevermind.

2024-04-04 15:40 UTC, mikechu-optimizely commented on lib/core/odp/odp_event_manager.ts
> -  PROCESSING,
Was `PROCESSING` used as a sort of lock while operating on an event queue?

2024-04-04 15:40 UTC, mikechu-optimizely commented on lib/core/odp/odp_event_manager.ts
> -  PROCESSING,
Oh maybe not ... the way we are taking on / processing batches to send.

2024-04-04 15:40 UTC, mikechu-optimizely commented on lib/core/odp/odp_event_manager.ts
> +        } while (shouldRetry && attemptNumber < this.retires);
NIT: `retries` 🛞🛞 😆

2024-04-04 15:40 UTC, mikechu-optimizely commented on lib/core/odp/odp_event_manager.ts
> +  }
super-NIT: Is it worthwhile to use a getter?

```suggestion
  public get queue(): OdpEvent[] {
     return this.queue;
    }
```

2024-04-04 15:40 UTC, mikechu-optimizely commented on lib/core/odp/odp_manager.ts
> +  public getStatus(): Status {
super-NIT: I love getters for semantic code, but I admit I'm being ridiculous. 😁

2024-04-04 15:40 UTC, mikechu-optimizely commented on lib/core/project_config/project_config_manager.tests.js
> +        var fakeDatafileManager = datafileManager.HttpPollingDatafileManager.getCall(0).returnValue;
Love these test updates. Thanks.  

Is it worth moving to `let`?

2024-04-04 15:40 UTC, mikechu-optimizely commented on lib/optimizely/index.ts
> +    this.readyPromise = Promise.all([
I was considering, in the React SDK, if we should use `Promise.allSettled`.

2024-04-04 15:40 UTC, mikechu-optimizely commented on lib/optimizely/index.ts
> +    this.readyPromise = Promise.all([
No wait. That's only if we were using `reject` correctly in React.

2024-04-04 15:40 UTC, mikechu-optimizely commented on tests/odpManager.spec.ts
> +  // const odpManagerInstance = (config?: OdpConfig) =>
I'd say delete this unless you think we'll need to come back to it.

2024-04-04 15:40 UTC, mikechu-optimizely commented on tests/odpManager.spec.ts
> +  // const odpManagerInstance = (config?: OdpConfig) =>
Oh or did you move these?

2024-04-04 15:51 UTC, muzahidul-opti commented on lib/core/odp/odp_event_manager.ts
>    private processQueue(shouldFlush = false): void {
Thanks for the explanation. Totally agree with this.

2024-04-04 17:56 UTC, raju-opti commented on lib/core/odp/odp_config.ts
> +  readonly apiHost: string;
we don't have any consistent convention in our codebase yet. I prefer omitting the public though

2024-04-04 18:17 UTC, raju-opti commented on lib/core/odp/odp_event_manager.ts
> +  }
I think having the same name for the property and getter will cause problem, and didn't want to rename the property, hence ..

2024-04-04 18:19 UTC, raju-opti commented on lib/core/project_config/project_config_manager.tests.js
> +        var fakeDatafileManager = datafileManager.HttpPollingDatafileManager.getCall(0).returnValue;
yeah, but this is an old JS test file and var is used everywhere, should change everything at once

2024-04-04 18:32 UTC, raju-opti commented on lib/optimizely/index.ts
> +    this.readyPromise = Promise.all([
We want the readyPromise to reject if any of them fail. But admittedly, this is not done consistently, for example, currently the promise can resolve with { success: false }

2024-04-04 18:35 UTC, raju-opti commented on lib/core/odp/odp_config.ts
> +export const odpIntegrationEquals = (config1: OdpIntegrationConfig, config2: OdpIntegrationConfig): boolean => {
updated

2024-04-04 18:36 UTC, raju-opti commented on lib/core/odp/odp_event_manager.ts
> +        } while (shouldRetry && attemptNumber < this.retires);
updated

2024-04-05 13:04 UTC, mikechu-optimizely approved these changes
LGTM

2024-04-05 20:32 UTC, jaeopt requested changes
One clarification - I see the updateOdpConfig on config change is broken. Can you take a look?

2024-04-05 20:32 UTC, jaeopt commented on lib/optimizely/index.ts
> -          )?.addNotificationListener(NOTIFICATION_TYPES.OPTIMIZELY_CONFIG_UPDATE, () => this.updateOdpSettings());
If you remove this, how do we get new odpconfig to ODPManager on changes?

2024-04-05 20:34 UTC, raju-opti commented on lib/core/odp/odp_event_manager.ts
> +    const hasNecessaryIdentifiers = this.hasNecessaryIdentifiers;
this was added for debugging, (ts-mockito was not behaving correctly with this method mocking cause this is method of the subclass), removing

2024-04-05 21:07 UTC, raju-opti commented on lib/core/odp/odp_event_manager.ts
> +      this.setNewTimeout();
this was in the previous implementation. I just wrapped it in the if, should I change it in any other way?

2024-04-05 21:11 UTC, raju-opti commented on lib/optimizely/index.ts
> -          )?.addNotificationListener(NOTIFICATION_TYPES.OPTIMIZELY_CONFIG_UPDATE, () => this.updateOdpSettings());
this code segment iteself is inside a listener that is fired on project config update. you can see `      `this.updateOdpSettings();` immediately below this code snippet, which will update the odp config each time project config manager fires onUpdate

2024-04-05 21:14 UTC, raju-opti commented on lib/core/odp/odp_event_manager.ts
> +      return;
This code just ensure to typescirpt that this.odpCofig is not undefined in the code that follows. This function is guaranteed to be not called when the event manager is not running

2024-04-05 21:14 UTC, raju-opti commented on lib/core/odp/odp_event_manager.ts
> +    this.clearCurrentTimeout();
updated

2024-04-05 21:26 UTC, jaeopt commented on lib/optimizely/index.ts
> -          )?.addNotificationListener(NOTIFICATION_TYPES.OPTIMIZELY_CONFIG_UPDATE, () => this.updateOdpSettings());
I see. You just removed the redundant event handler. It looks good!

2024-04-05 21:27 UTC, jaeopt approved these changes
LGTM

2024-04-05 21:44 UTC, merged