Junaed/fssdk 10198 - making isOdpIntegrated public
optimizely/javascript-sdk pull request #930
Opened 2024-05-17 17:10 UTC by junaed-optimizely

## Summary
Client should contain public facing API to provide information about ODP integration

## Test plan
Existing test should pass
## Issues
- [FSSDK-10198](https://jira.sso.episerver.net/browse/FSSDK-10198)

2024-05-17 20:12 UTC, mikechu-optimizely requested changes
Small necessary change, but looks good.

2024-05-17 20:12 UTC, mikechu-optimizely commented on lib/optimizely/index.ts
> +  public isOdpIntegrated(): boolean {
Now that we're making it public facing, can you add jsdoc?

2024-05-17 21:40 UTC, jaeopt requested changes
One required change

2024-05-17 21:40 UTC, jaeopt commented on lib/core/odp/odp_manager.ts
> +      this.logger.log(LogLevel.INFO, ERROR_MESSAGES.ODP_NOT_INTEGRATED);
This change looks good. We also need to change ERROR -> to INFO for "registerVuid()" api call as well.

2024-05-20 12:11 UTC, mikechu-optimizely commented on lib/optimizely/index.ts
> +   * @returns { boolean }
```suggestion
   * @returns { boolean } `true` if ODP settings were found in the datafile otherwise `false`
```

2024-05-20 12:12 UTC, mikechu-optimizely approved these changes
LGTM.

2024-05-20 15:47 UTC, jaeopt approved these changes
LGTM

2024-05-20 16:06 UTC, merged