[FSSDK-10711] Make use of VUID as an opt-in
optimizely/javascript-sdk pull request #950
Opened 2024-10-11 19:45 UTC by mikechu-optimizely

## Summary
- Client-side use of the visitor user ID (VUID) should be opt-in
- I made some additional devX and doc improvements

⚠️ NOTE: this is not being merged to the `master` branch yet, but will be released.  We'll need to cherry-pick later.

## Test plan

- Existing tests should pass
- New tests should also pass
- FSC end-to-end tests should pass

## Issues
[FSSDK-10711](https://jira.sso.episerver.net/browse/FSSDK-10711)

2024-10-14 13:09 UTC, raju-opti requested changes
We also need to handle the following requirement from the TDD:
* createUserContext() will be rejected when userId is not provided

2024-10-14 17:24 UTC, mikechu-optimizely commented on lib/plugins/odp_manager/index.browser.ts
> +  vuid?: string = "";
Ah. I was taking a cue from other tests that [look for empty string for user ID](https://github.com/optimizely/javascript-sdk/blob/5.x.x/lib/optimizely/index.tests.js#L6436) (flag key, etc) and added my unit tests to match.  

I'll update `vuid` to be `undefined` or a value....

2024-10-15 16:39 UTC, raju-opti requested changes

2024-10-15 16:39 UTC, raju-opti commented on lib/index.browser.ts
> +      vuidManager: await VuidManager.instance(cache, vuidManagerOptions),
let's get rid of this VuidManager.instance. We don't need to have it as a singleton. In the VuidManager, we will keep the vuidEnabled option in a class field. Here can just use new VuidManager(cache, option).

Let's move the initialization in a init() method in VuidManager. This is async. In the optimizely class, we should add vuidManager.init() in the readyPromise dependency.

2024-10-15 16:39 UTC, raju-opti commented on lib/plugins/vuid_manager/index.ts
> +  static async instance(cache: PersistentKeyValueCache, options: VuidManagerOptions): Promise<VuidManager> {
let's rename this to init() make it an instance method, not a static one. Also add this to the VuidManager interface.

2024-10-15 16:39 UTC, raju-opti commented on lib/core/odp/odp_manager.ts
> -        this.registerVuid();
this needs to move to the optimizely class. Let's make the registerVuid method below part of the OdpManager interface, and make it take the vuid as a parameter. Then in the optimizely constructor, we should do this

`this.onReady().then(() => {
  if (this.isVuidEnabled() && this.odpManager) {
    this.odpManager.registerVuid(this.vuidManager.vuid)
  }
})`

2024-10-15 16:39 UTC, raju-opti commented on lib/core/odp/odp_manager.ts
> -  private registerVuid() {
let make it `public registerVuid(vuid: string)`

2024-10-15 16:39 UTC, raju-opti commented on lib/index.browser.ts
> +// TODO: @raju-opti I'm not sure how to handle async VuidManager.instance() making createInstance async
suggested changes in other comments. This should stay sync.

2024-10-15 19:10 UTC, raju-opti commented on lib/plugins/vuid_manager/index.ts
> +import { VuidManagerOptions } from '../../shared_types';
We might want to have few other parameters in future, like whether already cached vuid should be removed from localstorage etc.

2024-10-15 21:21 UTC, raju-opti approved these changes
A few non critical comments

2024-10-15 21:21 UTC, raju-opti commented on lib/core/odp/odp_manager.ts
> +  registerVuid(vuid: string | undefined): void;
can we make the parameter just string?

2024-10-15 21:21 UTC, raju-opti commented on lib/index.react_native.ts
> +    const cache = new BrowserAsyncStorageCache();
There is ReactNativeAsyncStorageCache, we should probably use that instead

2024-10-15 21:21 UTC, raju-opti commented on lib/plugins/odp_manager/index.browser.ts
> +    if (!vuid || !VuidManager.isVuid(vuid)) {
can we remove this check by removing undefined from the vuid parameter type and assuming the caller mast pass a valid vuid?

2024-10-15 22:40 UTC, jaeopt requested changes
I see most issues fixed. A few more comments.

2024-10-15 22:40 UTC, jaeopt commented on lib/plugins/vuid_manager/index.ts
> +      this.logger.log(LogLevel.ERROR, 'VUID is not initialized. Please call initialize() before accessing the VUID.');
Wondering if we need error log here. Also, it looks like redudnant log for getVuid() function above.

2024-10-15 22:40 UTC, jaeopt commented on lib/plugins/vuid_manager/index.ts
> +      await this.load(this.cache);
It looks like this load creates/saves _vuid. We should skip it if vuid disabled.

2024-10-16 13:57 UTC, mikechu-optimizely commented on lib/plugins/vuid_manager/index.ts
> +      await this.load(this.cache);
Is the early return above on L110 a good way to skip the load?

2024-10-16 17:19 UTC, jaeopt commented on lib/plugins/vuid_manager/index.ts
> +      await this.load(this.cache);
Looks like. should skip any vuid action other than remove you did  in 110.

2024-10-16 17:27 UTC, jaeopt approved these changes
LGTM

2024-10-16 20:35 UTC, merged