[FSSDK-10935] Refactor log object export
optimizely/javascript-sdk pull request #976
Opened 2024-12-11 13:24 UTC by junaed-optimizely

## Summary
Conversion of log message object to log message variable for size reduction!

## Test plan
Existing tests have been modified to fit with the changes.

## Issues
- [FSSDK-10935](https://jira.sso.episerver.net/browse/FSSDK-10935)

2025-01-02 15:05 UTC, raju-opti requested changes
added a few comments

2025-01-02 15:05 UTC, raju-opti commented on lib/utils/import.react_native/@react-native-async-storage/async-storage.ts
> +    throw new Error(MODULE_NOT_FOUND_REACT_NATIVE_ASYNC_STORAGE);
as this will be exclusively used with react native, we can keep the string literal here and remove the MODULE_NOT_FOUND_REACT_NATIVE_ASYNC_STORAGE value form exception_messages file

2025-01-02 19:03 UTC, junaed-optimizely commented on tests/index.react_native.spec.ts
> +          throw new Error(INVALID_CONFIG_OR_SOMETHING);
Done!

2025-01-02 19:03 UTC, junaed-optimizely commented on lib/core/audience_evaluator/index.ts
> -      logger.log(LOG_LEVEL.WARNING, LOG_MESSAGES.UNKNOWN_CONDITION_TYPE, MODULE_NAME, JSON.stringify(condition));
Done!

2025-01-02 19:04 UTC, junaed-optimizely commented on lib/core/audience_evaluator/odp_segment_condition_evaluator/index.ts
> -    logger.warn(LOG_MESSAGES.UNKNOWN_MATCH_TYPE, MODULE_NAME, JSON.stringify(condition));
Done!

2025-01-02 19:04 UTC, junaed-optimizely commented on lib/core/bucketer/index.ts
> +          USER_NOT_IN_ANY_EXPERIMENT,
Done!

2025-01-02 19:04 UTC, junaed-optimizely commented on lib/event_processor/event_processor_factory.react_native.spec.ts
> +      throw new Error(MODULE_NOT_FOUND_REACT_NATIVE_NETINFO);
Done!

2025-01-02 19:04 UTC, junaed-optimizely commented on lib/index.browser.tests.js
> +    console.error(UNABLE_TO_OVERWRITE_GLOBAL_WINDOW);
Done!

2025-01-02 19:04 UTC, junaed-optimizely commented on lib/odp/odp_manager.spec.ts
> +    eventManagerPromise.reject(new Error(FAILED_TO_START));
Done!

2025-01-02 19:04 UTC, junaed-optimizely commented on lib/odp/segment_manager/odp_segment_api_manager.spec.ts
> -      responsePromise: Promise.reject(new Error('Request timed out')),
Done!

2025-01-02 19:04 UTC, junaed-optimizely commented on lib/project_config/config_manager_factory.react_native.spec.ts
> +      MODULE_NOT_FOUND_REACT_NATIVE_ASYNC_STORAGE
Done!

2025-01-02 19:04 UTC, junaed-optimizely commented on lib/project_config/project_config_manager.spec.ts
> +          const onRunning = Promise.reject(new Error(ONRUNNING_ERROR));
Done!

2025-01-02 19:04 UTC, junaed-optimizely commented on lib/utils/import.react_native/@react-native-async-storage/async-storage.ts
> +    throw new Error(MODULE_NOT_FOUND_REACT_NATIVE_ASYNC_STORAGE);
Done!

2025-01-03 11:33 UTC, raju-opti approved these changes
lgtm

2025-01-03 14:48 UTC, merged